export const browserCoreExamples = [
  "aletheia browser status",
  "aletheia browser start",
  "aletheia browser stop",
  "aletheia browser tabs",
  "aletheia browser open https://example.com",
  "aletheia browser focus abcd1234",
  "aletheia browser close abcd1234",
  "aletheia browser screenshot",
  "aletheia browser screenshot --full-page",
  "aletheia browser screenshot --ref 12",
  "aletheia browser snapshot",
  "aletheia browser snapshot --format aria --limit 200",
  "aletheia browser snapshot --efficient",
  "aletheia browser snapshot --labels",
];

export const browserActionExamples = [
  "aletheia browser navigate https://example.com",
  "aletheia browser resize 1280 720",
  "aletheia browser click 12 --double",
  'aletheia browser type 23 "hello" --submit',
  "aletheia browser press Enter",
  "aletheia browser hover 44",
  "aletheia browser drag 10 11",
  "aletheia browser select 9 OptionA OptionB",
  "aletheia browser upload /tmp/file.pdf",
  'aletheia browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aletheia browser dialog --accept",
  'aletheia browser wait --text "Done"',
  "aletheia browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aletheia browser console --level error",
  "aletheia browser pdf",
];
