/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.rs"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          DEFAULT: "var(--bg)",
          surface: "var(--bg-surface)",
          "surface-bright": "var(--bg-surface-bright)",
          "surface-dim": "var(--bg-surface-dim)",
          overlay: "var(--bg-overlay)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          inverse: "var(--text-inverse)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          dim: "var(--accent-dim)",
        },
        border: {
          DEFAULT: "var(--border)",
          focused: "var(--border-focused)",
          separator: "var(--border-separator)",
          selected: "var(--border-selected)",
        },
        status: {
          success: "var(--status-success)",
          warning: "var(--status-warning)",
          error: "var(--status-error)",
          info: "var(--status-info)",
          "success-bg": "var(--status-success-bg)",
          "warning-bg": "var(--status-warning-bg)",
          "error-bg": "var(--status-error-bg)",
          "info-bg": "var(--status-info-bg)",
        },
        role: {
          user: "var(--role-user)",
          assistant: "var(--role-assistant)",
          system: "var(--role-system)",
        },
        code: {
          fg: "var(--code-fg)",
          bg: "var(--code-bg)",
          lang: "var(--code-lang)",
        },
        syntax: {
          keyword: "var(--syntax-keyword)",
          string: "var(--syntax-string)",
          comment: "var(--syntax-comment)",
          function: "var(--syntax-function)",
          type: "var(--syntax-type)",
          number: "var(--syntax-number)",
          operator: "var(--syntax-operator)",
        },
        dye: {
          aima: "var(--aima)",
          "aima-bg": "var(--aima-bg)",
          thanatochromia: "var(--thanatochromia)",
          "thanatochromia-bg": "var(--thanatochromia-bg)",
          aporia: "var(--aporia)",
          "aporia-bg": "var(--aporia-bg)",
          natural: "var(--natural)",
          "natural-bg": "var(--natural-bg)",
        },
      },
      fontFamily: {
        mono: ["IBM Plex Mono", "ui-monospace", "monospace"],
        display: ["Cormorant Garamond", "Garamond", "Georgia", "serif"],
        body: [
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Helvetica Neue",
          "sans-serif",
        ],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        md: "var(--text-md)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        12: "var(--space-12)",
        16: "var(--space-16)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        inset: "var(--shadow-inset)",
      },
      transitionDuration: {
        quick: "150ms",
        measured: "300ms",
      },
      transitionTimingFunction: {
        DEFAULT: "ease",
      },
    },
  },
  plugins: [],
};
