// WHY: PipelineContext is the single value threaded through all pipeline stages.
// Stages read from it to get their inputs and write back their outputs so later
// stages can consume them. This keeps stage signatures uniform (all take &mut
// PipelineContext) and avoids passing a growing argument list as the pipeline
// grows.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

use tokio_util::sync::CancellationToken;

use crate::budget::Budget;
use crate::cost_ledger::CostLedger;
use crate::dag::{PromptDag, compute_frontier};
use crate::engine::DispatchEngine;
use crate::orchestrator::OrchestratorConfig;
use crate::prompt::PromptSpec;
use crate::qa::QaGate;
use crate::resume::ResumePolicy;
use crate::session::options::EngineConfig;
use crate::types::{DispatchResult, DispatchSpec, SessionOutcome};

/// State threaded through all pipeline stages for a single dispatch run.
///
/// Stages populate fields in execution order.  Downstream stages may assume
/// that fields written by prior stages are valid.
pub(crate) struct PipelineContext {
    // --- Inputs set at construction ---

    /// The dispatch specification (project, prompt numbers, concurrency cap).
    pub(crate) spec: DispatchSpec,
    /// Full prompt set for this dispatch.
    pub(crate) prompts: Vec<PromptSpec>,
    /// Session execution backend.
    pub(crate) engine: Arc<dyn DispatchEngine>,
    /// Quality assurance gate.
    pub(crate) qa: Arc<dyn QaGate>,
    /// Orchestrator-level configuration (concurrency, budget defaults).
    pub(crate) config: OrchestratorConfig,
    /// State persistence store, if attached.
    #[cfg(feature = "storage-fjall")]
    pub(crate) store: Option<Arc<crate::store::EnergeiaStore>>,

    // --- Set by preparation stage ---

    /// Unique identifier for this dispatch run (ULID string).
    pub(crate) dispatch_id: String,
    /// Wall-clock start time for the entire dispatch.
    pub(crate) start: Instant,
    /// Resolved prompt dependency DAG.
    pub(crate) dag: Option<PromptDag>,
    /// Topological frontier groups computed from the DAG.
    pub(crate) frontier: Vec<Vec<u32>>,
    /// Prompt lookup by number for O(1) access during execution.
    pub(crate) prompt_map: HashMap<u32, PromptSpec>,
    /// Shared atomic budget tracker.
    pub(crate) budget: Option<Arc<Budget>>,
    /// Per-blast-radius cost attribution ledger.
    pub(crate) cost_ledger: Option<Arc<CostLedger>>,
    /// Cancellation token for graceful abort.
    pub(crate) cancel: CancellationToken,
    /// Multi-stage resume escalation policy.
    pub(crate) resume_policy: ResumePolicy,
    /// Session-level engine configuration.
    pub(crate) engine_config: Option<EngineConfig>,
    /// Resolved maximum concurrent sessions.
    pub(crate) max_concurrent: usize,
    /// Dispatch record ID in the store (set by preparation if store is attached).
    #[cfg(feature = "storage-fjall")]
    pub(crate) store_dispatch_id: Option<crate::store::records::DispatchId>,

    // --- Accumulated during execution stage ---

    /// Per-prompt outcomes collected across all groups.
    pub(crate) outcomes: Vec<SessionOutcome>,
    /// Corrective prompts generated by QA for the next execution group.
    pub(crate) correctives: Vec<PromptSpec>,
    /// Whether the dispatch was aborted (budget exceeded or cancelled).
    pub(crate) aborted: bool,

    // --- Set by post-processing stage ---

    /// Final aggregate result, set by post-processing.
    pub(crate) result: Option<DispatchResult>,
}

impl PipelineContext {
    /// Construct a fresh context from the dispatch inputs.
    ///
    /// Fields that are populated by individual stages start as `None`, empty,
    /// or their zero value.
    pub(crate) fn new(
        spec: DispatchSpec,
        prompts: Vec<PromptSpec>,
        engine: Arc<dyn DispatchEngine>,
        qa: Arc<dyn QaGate>,
        config: OrchestratorConfig,
        #[cfg(feature = "storage-fjall")] store: Option<Arc<crate::store::EnergeiaStore>>,
    ) -> Self {
        Self {
            spec,
            prompts,
            engine,
            qa,
            config,
            #[cfg(feature = "storage-fjall")]
            store,
            dispatch_id: String::new(),
            start: Instant::now(),
            dag: None,
            frontier: Vec::new(),
            prompt_map: HashMap::new(),
            budget: None,
            cost_ledger: None,
            cancel: CancellationToken::new(),
            resume_policy: ResumePolicy::default(),
            engine_config: None,
            max_concurrent: 1,
            #[cfg(feature = "storage-fjall")]
            store_dispatch_id: None,
            outcomes: Vec::new(),
            correctives: Vec::new(),
            aborted: false,
            result: None,
        }
    }

    /// Convenience accessor — returns the frontier (panics if preparation has not run).
    ///
    /// Only used from execution stage where preparation is guaranteed to have run.
    pub(crate) fn frontier(&self) -> &[Vec<u32>] {
        &self.frontier
    }

    /// Mutable borrow of the DAG (panics if preparation has not run).
    pub(crate) fn dag_mut(&mut self) -> &mut PromptDag {
        self.dag
            .as_mut()
            .expect("dag accessed before preparation stage completed")
    }

    /// Budget Arc — panics if preparation has not run.
    pub(crate) fn budget(&self) -> &Arc<Budget> {
        self.budget
            .as_ref()
            .expect("budget accessed before preparation stage completed")
    }

    /// Cost ledger Arc — panics if preparation has not run.
    pub(crate) fn cost_ledger(&self) -> &Arc<CostLedger> {
        self.cost_ledger
            .as_ref()
            .expect("cost_ledger accessed before preparation stage completed")
    }

    /// Engine config ref — panics if preparation has not run.
    pub(crate) fn engine_config(&self) -> &EngineConfig {
        self.engine_config
            .as_ref()
            .expect("engine_config accessed before preparation stage completed")
    }
}

// Provide a computable frontier accessor that constructs it from the dag when
// needed. Used by the preparation stage.
impl PipelineContext {
    /// Build and cache the frontier from the resolved DAG.
    ///
    /// Called by the preparation stage after the DAG is built.
    pub(crate) fn set_dag_and_compute_frontier(&mut self, dag: PromptDag) {
        let frontier = compute_frontier(&dag);
        self.dag = Some(dag);
        self.frontier = frontier;
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use crate::engine::AgentOptions;
    use crate::http::mock::MockEngine;
    use crate::orchestrator::OrchestratorConfig;
    use crate::prompt::PromptSpec;
    use crate::qa::QaGate;
    use crate::session::options::EngineConfig;
    use crate::types::{DispatchSpec, MechanicalIssue, QaResult, QaVerdict};

    use super::*;

    struct AlwaysPassQa;

    impl QaGate for AlwaysPassQa {
        fn evaluate<'a>(
            &'a self,
            prompt: &'a crate::qa::PromptSpec,
            pr_number: u64,
            _diff: &'a str,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = crate::error::Result<QaResult>> + Send + 'a>,
        > {
            use jiff::Timestamp;
            Box::pin(async move {
                Ok(QaResult {
                    prompt_number: prompt.prompt_number,
                    pr_number,
                    verdict: QaVerdict::Pass,
                    criteria_results: vec![],
                    mechanical_issues: vec![],
                    cost_usd: 0.0,
                    evaluated_at: Timestamp::now(),
                    semantic_evaluated: false,
                })
            })
        }

        fn mechanical_check(
            &self,
            _diff: &str,
            _prompt: &crate::qa::PromptSpec,
        ) -> Vec<MechanicalIssue> {
            vec![]
        }
    }

    fn make_context() -> PipelineContext {
        let engine = Arc::new(MockEngine::new(vec![]));
        let qa = Arc::new(AlwaysPassQa);
        let spec = DispatchSpec::new("acme".to_owned(), vec![1]);
        let prompts = vec![PromptSpec {
            number: 1,
            description: "test".to_owned(),
            depends_on: vec![],
            acceptance_criteria: vec![],
            blast_radius: vec![],
            body: "do the thing".to_owned(),
        }];
        PipelineContext::new(
            spec,
            prompts,
            engine,
            qa,
            OrchestratorConfig::default(),
            #[cfg(feature = "storage-fjall")]
            None,
        )
    }

    #[test]
    fn new_context_has_empty_outcomes() {
        let ctx = make_context();
        assert!(ctx.outcomes.is_empty());
        assert!(ctx.correctives.is_empty());
        assert!(!ctx.aborted);
        assert!(ctx.result.is_none());
    }

    #[test]
    fn set_dag_and_compute_frontier_populates_frontier() {
        let mut ctx = make_context();
        let mut dag = PromptDag::new();
        dag.add_node(1, vec![]).unwrap();
        dag.add_node(2, vec![1]).unwrap();

        ctx.set_dag_and_compute_frontier(dag);

        assert!(ctx.dag.is_some());
        assert_eq!(ctx.frontier.len(), 2); // two groups: [1] then [2]
    }

    #[test]
    fn engine_config_accessor_returns_set_value() {
        let mut ctx = make_context();
        ctx.engine_config = Some(EngineConfig::new(AgentOptions::new()));
        let _ = ctx.engine_config(); // should not panic
    }
}
