// kanon:ignore RUST/file-too-long — static parameter registry: single data declaration of 50+ ParameterSpec entries
//! Static parameter registry: metadata for every tunable constant.
//!
//! Each [`ParameterSpec`] describes one knob in the configuration surface:
//! what it controls, its valid range, whether agents can self-tune it, and
//! what outcome signal a tuning loop should optimise for.

use std::sync::LazyLock;

/// Classification of who should tune a parameter and when.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[non_exhaustive]
pub enum ParameterTier {
    /// Operator sets at deployment time; not self-tunable.
    Deployment,
    /// Operator or agent may override per-agent via config.
    PerAgent,
    /// Eligible for automated tuning by the self-tuning loop.
    SelfTuning,
}

impl std::fmt::Display for ParameterTier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Deployment => f.write_str("deployment"),
            Self::PerAgent => f.write_str("per-agent"),
            Self::SelfTuning => f.write_str("self-tuning"),
        }
    }
}

/// Hint for which direction improves the outcome signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
// kanon:ignore RUST/non-exhaustive-enum — stable registry classification enum; variant additions are breaking changes by design
pub enum TuningDirection {
    /// Increasing the value generally improves the outcome signal.
    Higher,
    /// Decreasing the value generally improves the outcome signal.
    Lower,
    /// Optimal direction depends on deployment context.
    Contextual,
}

impl std::fmt::Display for TuningDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Higher => f.write_str("higher"),
            Self::Lower => f.write_str("lower"),
            Self::Contextual => f.write_str("contextual"),
        }
    }
}

/// A typed default value for a parameter.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(untagged)]
// kanon:ignore RUST/non-exhaustive-enum — stable registry value enum; variant additions are breaking changes by design
pub enum ParameterValue {
    /// Integer parameter.
    Int(i64),
    /// Floating-point parameter.
    Float(f64),
    /// Boolean toggle.
    Bool(bool),
    /// String-valued parameter.
    Str(&'static str),
    /// Duration in the unit described by the parameter key (seconds, milliseconds, etc.).
    Duration(u64),
}

impl std::fmt::Display for ParameterValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Int(v) => write!(f, "{v}"),
            Self::Float(v) => write!(f, "{v}"),
            Self::Bool(v) => write!(f, "{v}"),
            Self::Str(v) => write!(f, "{v}"),
            Self::Duration(v) => write!(f, "{v}"),
        }
    }
}

/// Metadata for a single tunable parameter.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ParameterSpec {
    /// Dotted config key (e.g. `"agents.defaults.behavior.distillationContextTokenTrigger"`).
    pub key: &'static str,
    /// Config section this parameter lives in.
    pub section: &'static str,
    /// Who should tune this parameter.
    pub tier: ParameterTier,
    /// Default value compiled into the binary.
    pub default: ParameterValue,
    /// Optional `(min, max)` numeric bounds.
    pub bounds: Option<(f64, f64)>,
    /// Whether the parameter can be changed without restarting.
    pub hot_reloadable: bool,
    /// Human-readable description.
    pub description: &'static str,
    /// Which subsystem behavior this parameter affects.
    pub affects: &'static str,
    /// Outcome signal that a tuning loop should optimise for.
    pub outcome_signal: &'static str,
    /// What evidence is needed before changing this parameter.
    pub evidence_required: &'static str,
    /// Hint for which direction improves the outcome signal.
    pub direction_hint: TuningDirection,
}

/// Return every registered parameter spec.
#[must_use]
pub fn all_specs() -> &'static [ParameterSpec] {
    &REGISTRY
}

/// Return specs whose `section` matches `section`.
#[must_use]
pub fn specs_by_section(section: &str) -> Vec<&'static ParameterSpec> {
    REGISTRY.iter().filter(|s| s.section == section).collect()
}

/// Return specs whose `affects` field contains `outcome`.
#[must_use]
pub fn specs_affecting(outcome: &str) -> Vec<&'static ParameterSpec> {
    REGISTRY
        .iter()
        .filter(|s| s.affects.contains(outcome))
        .collect()
}

/// Look up a single spec by its dotted key.
#[must_use]
pub fn spec_by_key(key: &str) -> Option<&'static ParameterSpec> {
    REGISTRY.iter().find(|s| s.key == key)
}

// ── Static registry — populated at first access via LazyLock ──

static REGISTRY: LazyLock<Vec<ParameterSpec>> = LazyLock::new(build_registry);

#[expect(
    clippy::too_many_lines,
    reason = "static data declaration: one Vec literal of 50+ ParameterSpec entries"
)]
fn build_registry() -> Vec<ParameterSpec> {
    vec![
        // ── Process-lifetime structural config ──
        // WHY: these paths determine process binding, registration, or sandbox
        // policy at startup; changing them requires a restart. They are kept in
        // the registry so RESTART_PREFIXES can be derived from a single source.
        ParameterSpec {
            key: "gateway.port",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(18_789),
            bounds: Some((1.0, 65_535.0)),
            hot_reloadable: false,
            description: "TCP port the HTTP gateway listens on",
            affects: "gateway_binding",
            outcome_signal: "gateway_startup_success",
            evidence_required: "Port availability and binding analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "gateway.bind",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Str("localhost"),
            bounds: None,
            hot_reloadable: false,
            description: "Network interface binding mode for the gateway",
            affects: "gateway_binding",
            outcome_signal: "gateway_startup_success",
            evidence_required: "Network interface and exposure analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "gateway.tls",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(false),
            bounds: None,
            hot_reloadable: false,
            description: "TLS termination settings for the gateway",
            affects: "gateway_binding",
            outcome_signal: "gateway_startup_success",
            evidence_required: "TLS certificate and termination analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "gateway.auth.mode",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Str("token"),
            bounds: None,
            hot_reloadable: false,
            description: "Gateway authentication mode",
            affects: "gateway_auth",
            outcome_signal: "auth_failure_rate",
            evidence_required: "Authentication mode and threat model analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "gateway.csrf",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(true),
            bounds: None,
            hot_reloadable: false,
            description: "CSRF protection settings for the gateway",
            affects: "gateway_auth",
            outcome_signal: "csrf_rejection_rate",
            evidence_required: "CSRF policy and client compatibility analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "gateway.bodyLimit",
            section: "gateway",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_048_576),
            bounds: Some((1_024.0, 1_000_000_000.0)),
            hot_reloadable: false,
            description: "Maximum request body size in bytes",
            affects: "gateway_binding",
            outcome_signal: "request_size_rejection_rate",
            evidence_required: "Request size distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "channels",
            section: "channels",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(true),
            bounds: None,
            hot_reloadable: false,
            description: "Messaging transport configuration",
            affects: "messaging_transport",
            outcome_signal: "channel_startup_success",
            evidence_required: "Messaging transport requirement analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "workspace.root",
            section: "workspace",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Str(""),
            bounds: None,
            hot_reloadable: false,
            description: "Root directory served by the workspace file API",
            affects: "workspace_files",
            outcome_signal: "workspace_access_error_rate",
            evidence_required: "Workspace directory and permission analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "sandbox",
            section: "sandbox",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(true),
            bounds: None,
            hot_reloadable: false,
            description: "Sandbox policy for tool command execution",
            affects: "tool_sandbox",
            outcome_signal: "sandbox_violation_rate",
            evidence_required: "Sandbox policy and enforcement analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "tools",
            section: "tools",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(false),
            bounds: None,
            hot_reloadable: false,
            description: "Runtime-bridged external tool declarations",
            affects: "external_tools",
            outcome_signal: "tool_registration_failure_rate",
            evidence_required: "External tool availability and registration analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Distillation ──
        ParameterSpec {
            key: "agents.defaults.behavior.distillationContextTokenTrigger",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Int(120_000),
            bounds: Some((10_000.0, 500_000.0)),
            hot_reloadable: true,
            description: "Context token count that triggers automatic distillation",
            affects: "distillation_frequency",
            outcome_signal: "turn_quality_post_distillation",
            evidence_required: "A/B comparison of turn quality and cost before/after threshold change",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationMessageCountTrigger",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Int(150),
            bounds: Some((10.0, 1000.0)),
            hot_reloadable: true,
            description: "Message count that triggers distillation",
            affects: "distillation_frequency",
            outcome_signal: "turn_quality_post_distillation",
            evidence_required: "Session length distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationStaleSessionDays",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Duration(7),
            bounds: Some((1.0, 90.0)),
            hot_reloadable: true,
            description: "Days idle before a session is considered stale for distillation",
            affects: "distillation_frequency",
            outcome_signal: "stale_session_cleanup_rate",
            evidence_required: "Session idle time distribution",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationStaleMinMessages",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(20),
            bounds: Some((1.0, 200.0)),
            hot_reloadable: true,
            description: "Minimum messages required for stale-session distillation",
            affects: "distillation_frequency",
            outcome_signal: "stale_session_cleanup_rate",
            evidence_required: "Session length distribution",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationNeverDistilledTrigger",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(30),
            bounds: Some((5.0, 500.0)),
            hot_reloadable: true,
            description: "Message count trigger for sessions never distilled",
            affects: "distillation_frequency",
            outcome_signal: "first_distillation_quality",
            evidence_required: "First-distillation quality metrics",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationMaxBackoffTurns",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Int(8),
            bounds: Some((1.0, 50.0)),
            hot_reloadable: true,
            description: "Maximum backoff turns before distillation is forced",
            affects: "distillation_frequency",
            outcome_signal: "distillation_backoff_effectiveness",
            evidence_required: "Backoff-vs-force distillation quality comparison",
            direction_hint: TuningDirection::Higher,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.distillationMaxToolResultLen",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(500),
            bounds: Some((50.0, 5000.0)),
            hot_reloadable: true,
            description: "Maximum character length for truncated tool results in distillation prompts",
            affects: "distillation_quality",
            outcome_signal: "distillation_summary_fidelity",
            evidence_required: "Comparison of distillation accuracy at different truncation points",
            direction_hint: TuningDirection::Higher,
        },
        // ── Competence scoring ──
        ParameterSpec {
            key: "agents.defaults.behavior.competenceCorrectionPenalty",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.05),
            bounds: Some((0.001, 0.5)),
            hot_reloadable: true,
            description: "Competence score penalty per correction",
            affects: "competence_scoring",
            outcome_signal: "correction_rate_trend",
            evidence_required: "Correction frequency and severity over 100+ turns",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceSuccessBonus",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.02),
            bounds: Some((0.001, 0.2)),
            hot_reloadable: true,
            description: "Competence score bonus per successful turn",
            affects: "competence_scoring",
            outcome_signal: "competence_score_stability",
            evidence_required: "Score trajectory analysis over 200+ turns",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceDisagreementPenalty",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.01),
            bounds: Some((0.001, 0.2)),
            hot_reloadable: true,
            description: "Competence score penalty per user disagreement",
            affects: "competence_scoring",
            outcome_signal: "user_satisfaction_correlation",
            evidence_required: "User feedback correlation analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceMinScore",
            section: "agents.defaults.behavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Float(0.1),
            bounds: Some((0.0, 0.5)),
            hot_reloadable: true,
            description: "Competence score floor",
            affects: "competence_scoring",
            outcome_signal: "recovery_from_low_competence",
            evidence_required: "Agent recovery behavior at minimum score",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceMaxScore",
            section: "agents.defaults.behavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Float(0.95),
            bounds: Some((0.5, 1.0)),
            hot_reloadable: true,
            description: "Competence score ceiling",
            affects: "competence_scoring",
            outcome_signal: "score_distribution_shape",
            evidence_required: "Long-term score distribution analysis",
            direction_hint: TuningDirection::Higher,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceDefaultScore",
            section: "agents.defaults.behavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Float(0.5),
            bounds: Some((0.1, 0.95)),
            hot_reloadable: true,
            description: "Initial competence score for a new agent",
            affects: "competence_scoring",
            outcome_signal: "new_agent_calibration_speed",
            evidence_required: "Time-to-accurate-score for new agents",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.competenceEscalationFailureThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Float(0.30),
            bounds: Some((0.05, 0.8)),
            hot_reloadable: true,
            description: "Competence score below which escalation fires",
            affects: "competence_scoring",
            outcome_signal: "escalation_precision",
            evidence_required: "False-positive and false-negative escalation rates",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Knowledge — conflict resolution ──
        ParameterSpec {
            key: "knowledge.conflictIntraBatchDedupThreshold",
            section: "knowledge",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.95),
            bounds: Some((0.5, 1.0)),
            hot_reloadable: true,
            description: "Similarity threshold above which intra-batch candidates are merged",
            affects: "knowledge_dedup",
            outcome_signal: "duplicate_fact_rate",
            evidence_required: "Duplicate fact rate at different thresholds",
            direction_hint: TuningDirection::Higher,
        },
        ParameterSpec {
            key: "knowledge.conflictCandidateDistanceThreshold",
            section: "knowledge",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.28),
            bounds: Some((0.05, 0.8)),
            hot_reloadable: true,
            description: "Maximum vector distance for a fact to be a conflict candidate",
            affects: "knowledge_conflict_resolution",
            outcome_signal: "conflict_detection_recall",
            evidence_required: "Conflict detection recall/precision at different thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "knowledge.conflictMaxCandidates",
            section: "knowledge",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(5),
            bounds: Some((1.0, 50.0)),
            hot_reloadable: true,
            description: "Maximum conflict candidates evaluated per fact",
            affects: "knowledge_conflict_resolution",
            outcome_signal: "conflict_resolution_latency",
            evidence_required: "Latency and accuracy tradeoff at different candidate counts",
            direction_hint: TuningDirection::Higher,
        },
        ParameterSpec {
            key: "knowledge.decayReinforcementBoost",
            section: "knowledge",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.02),
            bounds: Some((0.001, 0.2)),
            hot_reloadable: true,
            description: "Confidence boost per reinforcement event",
            affects: "knowledge_confidence",
            outcome_signal: "fact_confidence_calibration",
            evidence_required: "Confidence vs. accuracy correlation analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "knowledge.decayCrossAgentBonusPerAgent",
            section: "knowledge",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.15),
            bounds: Some((0.0, 0.5)),
            hot_reloadable: true,
            description: "Confidence bonus per additional corroborating agent",
            affects: "knowledge_confidence",
            outcome_signal: "cross_agent_fact_accuracy",
            evidence_required: "Multi-agent corroboration accuracy metrics",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "knowledge.decayMaxCrossAgentMultiplier",
            section: "knowledge",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Float(1.75),
            bounds: Some((1.0, 5.0)),
            hot_reloadable: true,
            description: "Cap on total cross-agent confidence multiplier",
            affects: "knowledge_confidence",
            outcome_signal: "cross_agent_fact_accuracy",
            evidence_required: "Multi-agent confidence distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Knowledge — dedup weights ──
        ParameterSpec {
            key: "agents.defaults.behavior.knowledgeDedupWeightName",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.4),
            bounds: Some((0.0, 1.0)),
            hot_reloadable: true,
            description: "Weight of name similarity in dedup scoring",
            affects: "knowledge_dedup",
            outcome_signal: "dedup_precision_recall",
            evidence_required: "Dedup accuracy at different weight combinations",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.knowledgeDedupWeightEmbed",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.3),
            bounds: Some((0.0, 1.0)),
            hot_reloadable: true,
            description: "Weight of embedding similarity in dedup scoring",
            affects: "knowledge_dedup",
            outcome_signal: "dedup_precision_recall",
            evidence_required: "Dedup accuracy at different weight combinations",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.knowledgeDedupJwThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.85),
            bounds: Some((0.5, 1.0)),
            hot_reloadable: true,
            description: "Jaro-Winkler score above which strings are considered similar",
            affects: "knowledge_dedup",
            outcome_signal: "dedup_precision_recall",
            evidence_required: "Name-match accuracy at different JW thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.knowledgeDedupEmbedThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.80),
            bounds: Some((0.5, 1.0)),
            hot_reloadable: true,
            description: "Cosine similarity above which embeddings are considered similar",
            affects: "knowledge_dedup",
            outcome_signal: "dedup_precision_recall",
            evidence_required: "Embedding-match accuracy at different thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Knowledge — fact lifecycle thresholds ──
        ParameterSpec {
            key: "agents.defaults.behavior.factActiveThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.7),
            bounds: Some((0.3, 1.0)),
            hot_reloadable: true,
            description: "Confidence above which a fact is considered Active",
            affects: "knowledge_fact_lifecycle",
            outcome_signal: "fact_stage_distribution",
            evidence_required: "Fact lifecycle stage distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.factFadingThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.3),
            bounds: Some((0.05, 0.7)),
            hot_reloadable: true,
            description: "Confidence below which a fact is considered Fading",
            affects: "knowledge_fact_lifecycle",
            outcome_signal: "fact_stage_distribution",
            evidence_required: "Fact lifecycle stage distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.factDormantThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.1),
            bounds: Some((0.0, 0.3)),
            hot_reloadable: true,
            description: "Confidence below which a fact is considered Dormant",
            affects: "knowledge_fact_lifecycle",
            outcome_signal: "fact_stage_distribution",
            evidence_required: "Dormant fact recovery rate analysis",
            direction_hint: TuningDirection::Lower,
        },
        // ── Tool limits ──
        ParameterSpec {
            key: "toolLimits.maxPatternLength",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_000),
            bounds: Some((10.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum character length for glob patterns",
            affects: "tool_filesystem",
            outcome_signal: "glob_timeout_rate",
            evidence_required: "Pattern length vs. execution time distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.subprocessTimeoutSecs",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(60),
            bounds: Some((5.0, 600.0)),
            hot_reloadable: true,
            description: "Timeout in seconds for filesystem subprocess commands",
            affects: "tool_filesystem",
            outcome_signal: "subprocess_timeout_rate",
            evidence_required: "Subprocess execution time distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.maxWriteBytes",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(10_485_760),
            bounds: Some((1024.0, 104_857_600.0)),
            hot_reloadable: true,
            description: "Maximum bytes per workspace write operation (default 10 MiB)",
            affects: "tool_workspace",
            outcome_signal: "write_rejection_rate",
            evidence_required: "Write size distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.maxReadBytes",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(52_428_800),
            bounds: Some((1024.0, 524_288_000.0)),
            hot_reloadable: true,
            description: "Maximum bytes per workspace read operation (default 50 MiB)",
            affects: "tool_workspace",
            outcome_signal: "read_rejection_rate",
            evidence_required: "Read size distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.maxCommandLength",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(10_000),
            bounds: Some((100.0, 1_000_000.0)),
            hot_reloadable: true,
            description: "Maximum character length of a shell command",
            affects: "tool_workspace",
            outcome_signal: "command_rejection_rate",
            evidence_required: "Command length distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.messageMaxLen",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(4_000),
            bounds: Some((100.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum characters per intra-session message",
            affects: "tool_communication",
            outcome_signal: "message_truncation_rate",
            evidence_required: "Message length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.interSessionMaxMessageLen",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(100_000),
            bounds: Some((1000.0, 1_000_000.0)),
            hot_reloadable: true,
            description: "Maximum characters per inter-session message",
            affects: "tool_communication",
            outcome_signal: "inter_session_message_truncation_rate",
            evidence_required: "Inter-session message length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "toolLimits.interSessionMaxTimeoutSecs",
            section: "toolLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((10.0, 3600.0)),
            hot_reloadable: true,
            description: "Maximum wait timeout in seconds for inter-session messages",
            affects: "tool_communication",
            outcome_signal: "inter_session_timeout_rate",
            evidence_required: "Inter-session response time distribution",
            direction_hint: TuningDirection::Contextual,
        },
        // ── API limits ──
        ParameterSpec {
            key: "apiLimits.maxSessionNameLen",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(255),
            bounds: Some((1.0, 10_000.0)),
            hot_reloadable: true,
            description: "Maximum characters in a session name",
            affects: "api_validation",
            outcome_signal: "session_name_rejection_rate",
            evidence_required: "Session-name length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxIdentifierBytes",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(256),
            bounds: Some((1.0, 10_000.0)),
            hot_reloadable: true,
            description: "Maximum bytes in a request identifier",
            affects: "api_validation",
            outcome_signal: "identifier_rejection_rate",
            evidence_required: "Identifier length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxMessageBytes",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(262_144),
            bounds: Some((1024.0, 10_485_760.0)),
            hot_reloadable: true,
            description: "Maximum bytes per streaming message body (default 256 KiB)",
            affects: "api_message_handling",
            outcome_signal: "message_rejection_rate",
            evidence_required: "Message size distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxHistoryLimit",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_000),
            bounds: Some((1.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum messages returned by the history endpoint",
            affects: "api_history",
            outcome_signal: "history_request_latency",
            evidence_required: "History endpoint latency vs. limit analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxFactsLimit",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_000),
            bounds: Some((1.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum facts returned by a knowledge list request",
            affects: "api_knowledge_query",
            outcome_signal: "knowledge_list_latency",
            evidence_required: "Knowledge list latency vs. limit analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxSearchLimit",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_000),
            bounds: Some((1.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum search results returned by a knowledge search request",
            affects: "api_knowledge_search",
            outcome_signal: "knowledge_search_latency",
            evidence_required: "Knowledge search latency vs. limit analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.maxImportBatchSize",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(1_000),
            bounds: Some((1.0, 100_000.0)),
            hot_reloadable: true,
            description: "Maximum facts in a single bulk-import request",
            affects: "api_knowledge_import",
            outcome_signal: "import_throughput",
            evidence_required: "Import batch size vs. throughput and error rate",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.idempotencyTtlSecs",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((10.0, 86_400.0)),
            hot_reloadable: true,
            description: "TTL in seconds for idempotency key cache entries",
            affects: "api_idempotency",
            outcome_signal: "idempotency_cache_hit_rate",
            evidence_required: "Retry timing distribution analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "apiLimits.idempotencyCapacity",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(10_000),
            bounds: Some((100.0, 10_000_000.0)),
            hot_reloadable: false,
            description: "Maximum idempotency cache entries (LRU cap)",
            affects: "api_idempotency",
            outcome_signal: "idempotency_cache_eviction_rate",
            evidence_required: "Cache utilization and eviction rate analysis",
            direction_hint: TuningDirection::Higher,
        },
        ParameterSpec {
            key: "apiLimits.idempotencyMaxKeyLength",
            section: "apiLimits",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(64),
            bounds: Some((1.0, 1024.0)),
            hot_reloadable: true,
            description: "Maximum character length of an idempotency key",
            affects: "api_idempotency",
            outcome_signal: "idempotency_key_rejection_rate",
            evidence_required: "Idempotency key length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Timeouts and retry ──
        ParameterSpec {
            key: "timeouts.llmCallSecs",
            section: "timeouts",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((30.0, 3600.0)),
            hot_reloadable: true,
            description: "Maximum wall-clock seconds for a single LLM API call",
            affects: "llm_latency",
            outcome_signal: "llm_timeout_rate",
            evidence_required: "LLM call duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "retry.maxAttempts",
            section: "retry",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(3),
            bounds: Some((0.0, 10.0)),
            hot_reloadable: true,
            description: "Maximum number of retry attempts after an initial transient failure",
            affects: "llm_reliability",
            outcome_signal: "retry_success_rate",
            evidence_required: "Retry success rate by attempt number",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "retry.backoffBaseMs",
            section: "retry",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(1_000),
            bounds: Some((100.0, 30_000.0)),
            hot_reloadable: true,
            description: "Initial exponential backoff delay in milliseconds",
            affects: "llm_reliability",
            outcome_signal: "retry_success_rate",
            evidence_required: "Retry timing vs. success rate analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "retry.backoffMaxMs",
            section: "retry",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(30_000),
            bounds: Some((100.0, 300_000.0)),
            hot_reloadable: true,
            description: "Maximum backoff delay cap in milliseconds",
            affects: "llm_reliability",
            outcome_signal: "retry_success_rate",
            evidence_required: "Backoff ceiling vs. retry outcome analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Safety ──
        ParameterSpec {
            key: "agents.defaults.behavior.safetyLoopDetectionThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(3),
            bounds: Some((1.0, 20.0)),
            hot_reloadable: true,
            description: "Consecutive identical tool-call sequences before loop detection fires",
            affects: "safety_loop_detection",
            outcome_signal: "loop_detection_precision",
            evidence_required: "False-positive loop detection rate",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.safetyConsecutiveErrorThreshold",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(4),
            bounds: Some((1.0, 20.0)),
            hot_reloadable: true,
            description: "Consecutive errors before the pipeline aborts with a safety interrupt",
            affects: "safety_error_handling",
            outcome_signal: "unnecessary_abort_rate",
            evidence_required: "Abort necessity analysis at different thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "agents.defaults.behavior.safetySessionTokenCap",
            section: "agents.defaults.behavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(500_000),
            bounds: Some((10_000.0, 5_000_000.0)),
            hot_reloadable: true,
            description: "Hard token cap for a single session",
            affects: "safety_cost_control",
            outcome_signal: "session_cost_distribution",
            evidence_required: "Session token usage distribution",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Compaction ──
        ParameterSpec {
            key: "agents.defaults.behavior.compactionStrategy",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Str("uniform_tail"),
            bounds: None,
            hot_reloadable: true,
            description: "Context compaction preserved-tail strategy: uniform_tail | step_positional",
            affects: "compaction_quality",
            outcome_signal: "post_compaction_turn_quality",
            evidence_required: "A/B comparison of decision retention across strategies",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Capacity ──
        ParameterSpec {
            key: "capacity.maxToolOutputBytes",
            section: "capacity",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(51_200),
            bounds: Some((0.0, 10_485_760.0)),
            hot_reloadable: true,
            description: "Maximum bytes returned by a single tool call before truncation (0 to disable)",
            affects: "tool_output_quality",
            outcome_signal: "tool_output_truncation_rate",
            evidence_required: "Tool output size distribution",
            direction_hint: TuningDirection::Higher,
        },
        // ── Nous behavior ──
        ParameterSpec {
            key: "nousBehavior.degradedPanicThreshold",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(5),
            bounds: Some((1.0, 100.0)),
            hot_reloadable: true,
            description: "Panics within the degraded-mode window before degraded mode activates",
            affects: "agent_resilience",
            outcome_signal: "degraded_mode_precision",
            evidence_required: "Panic frequency and degraded-mode activation analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.degradedWindowSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(600),
            bounds: Some((1.0, 86_400.0)),
            hot_reloadable: true,
            description: "Window in seconds for counting panics toward degraded mode",
            affects: "agent_resilience",
            outcome_signal: "degraded_mode_precision",
            evidence_required: "Panic clustering over time",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.inboxRecvTimeoutSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(30),
            bounds: Some((1.0, 3600.0)),
            hot_reloadable: true,
            description: "Actor inbox receive timeout in seconds before warning",
            affects: "agent_message_loop",
            outcome_signal: "inbox_timeout_warning_rate",
            evidence_required: "Actor receive latency distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.maxSpawnedTasks",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(8),
            bounds: Some((1.0, 1_000.0)),
            hot_reloadable: true,
            description: "Maximum concurrently spawned tasks per agent",
            affects: "agent_concurrency",
            outcome_signal: "spawned_task_saturation_rate",
            evidence_required: "Concurrent task count and latency analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.loopDetectionWindow",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(50),
            bounds: Some((5.0, 500.0)),
            hot_reloadable: true,
            description: "Number of recent tool calls scanned for loop detection",
            affects: "safety_loop_detection",
            outcome_signal: "loop_detection_precision",
            evidence_required: "Window size vs. detection accuracy analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.cycleDetectionMaxLen",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(10),
            bounds: Some((1.0, 100.0)),
            hot_reloadable: true,
            description: "Maximum sequence length examined for repeating tool-call cycles",
            affects: "safety_loop_detection",
            outcome_signal: "cycle_detection_precision",
            evidence_required: "Cycle length distribution and false-positive analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.selfAuditEventThreshold",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(50),
            bounds: Some((1.0, 10_000.0)),
            hot_reloadable: true,
            description: "Events accumulated before self-audit runs",
            affects: "agent_self_audit",
            outcome_signal: "self_audit_latency",
            evidence_required: "Event accumulation vs. audit usefulness analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.gcIntervalSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((30.0, 3600.0)),
            hot_reloadable: true,
            description: "Completed-task garbage collection interval in seconds",
            affects: "resource_management",
            outcome_signal: "memory_usage_trend",
            evidence_required: "Memory usage vs. GC interval analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.managerHealthIntervalSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(30),
            bounds: Some((5.0, 300.0)),
            hot_reloadable: true,
            description: "Agent health poll interval in seconds",
            affects: "agent_health_monitoring",
            outcome_signal: "failure_detection_latency",
            evidence_required: "Time-to-detect-failure at different poll intervals",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "nousBehavior.managerPingTimeoutSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(5),
            bounds: Some((1.0, 60.0)),
            hot_reloadable: true,
            description: "Timeout in seconds for manager health-ping responses",
            affects: "agent_health_monitoring",
            outcome_signal: "false_dead_agent_rate",
            evidence_required: "Ping latency and false-positive restart analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.managerMaxRestartBackoffSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((1.0, 86_400.0)),
            hot_reloadable: true,
            description: "Maximum restart backoff duration for failed agents",
            affects: "agent_restart",
            outcome_signal: "agent_recovery_time",
            evidence_required: "Restart backoff and recovery timing analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.managerRestartDrainTimeoutSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(30),
            bounds: Some((1.0, 600.0)),
            hot_reloadable: true,
            description: "Seconds to wait for an agent to drain before restart",
            affects: "agent_restart",
            outcome_signal: "restart_abort_rate",
            evidence_required: "Drain duration distribution during restarts",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.managerRestartDecayWindowSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(3_600),
            bounds: Some((60.0, 86_400.0)),
            hot_reloadable: true,
            description: "Window in seconds over which restart failure count decays",
            affects: "agent_restart",
            outcome_signal: "restart_suppression_accuracy",
            evidence_required: "Restart recurrence timing analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "nousBehavior.shutdownTimeoutSecs",
            section: "nousBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(30),
            bounds: Some((1.0, 3600.0)),
            hot_reloadable: true,
            description: "Seconds manager waits for actors during graceful shutdown",
            affects: "agent_shutdown",
            outcome_signal: "shutdown_abort_rate",
            evidence_required: "Shutdown duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Provider behavior ──
        ParameterSpec {
            key: "providerBehavior.nonStreamingTimeoutSecs",
            section: "providerBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(120),
            bounds: Some((10.0, 600.0)),
            hot_reloadable: false,
            description: "Timeout in seconds for non-streaming LLM requests",
            affects: "llm_latency",
            outcome_signal: "non_streaming_timeout_rate",
            evidence_required: "Non-streaming request duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.sseDefaultRetryMs",
            section: "providerBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(1_000),
            bounds: Some((100.0, 60_000.0)),
            hot_reloadable: true,
            description: "Default retry delay from SSE stream retry fields",
            affects: "llm_stream_recovery",
            outcome_signal: "stream_retry_success_rate",
            evidence_required: "SSE retry timing and recovery analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.concurrencyEwmaAlpha",
            section: "providerBehavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(0.8),
            bounds: Some((0.0, 1.0)),
            hot_reloadable: true,
            description: "EWMA smoothing factor for adaptive provider concurrency",
            affects: "llm_concurrency",
            outcome_signal: "provider_latency_stability",
            evidence_required: "Concurrency limit response under latency changes",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.concurrencyLatencyThresholdSecs",
            section: "providerBehavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Float(30.0),
            bounds: Some((1.0, 300.0)),
            hot_reloadable: true,
            description: "Latency threshold above which adaptive concurrency is reduced",
            affects: "llm_concurrency",
            outcome_signal: "provider_timeout_rate",
            evidence_required: "Provider latency and timeout correlation analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.complexityRoutingEnabled",
            section: "providerBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Bool(false),
            bounds: None,
            hot_reloadable: true,
            description: "Enable per-turn complexity scoring to select configured model tiers",
            affects: "model_routing",
            outcome_signal: "model_routing_cost_quality_tradeoff",
            evidence_required: "Quality and cost comparison before enabling tiered routing",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.complexityLowThreshold",
            section: "providerBehavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Int(30),
            bounds: Some((0.0, 100.0)),
            hot_reloadable: true,
            description: "Enabled-routing score at or below which Haiku-class model is selected",
            affects: "model_routing",
            outcome_signal: "model_routing_cost_quality_tradeoff",
            evidence_required: "Quality and cost comparison across routing thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "providerBehavior.complexityHighThreshold",
            section: "providerBehavior",
            tier: ParameterTier::SelfTuning,
            default: ParameterValue::Int(70),
            bounds: Some((0.0, 100.0)),
            hot_reloadable: true,
            description: "Enabled-routing score at or above which Opus-class model is selected",
            affects: "model_routing",
            outcome_signal: "model_routing_cost_quality_tradeoff",
            evidence_required: "Quality and cost comparison across routing thresholds",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Messaging ──
        ParameterSpec {
            key: "messaging.pollIntervalMs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(2_000),
            bounds: Some((100.0, 60_000.0)),
            hot_reloadable: false,
            description: "How often Semeion polls for new channel messages in milliseconds",
            affects: "message_latency",
            outcome_signal: "message_delivery_latency",
            evidence_required: "Message delivery latency distribution",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "messaging.bufferCapacity",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(100),
            bounds: Some((1.0, 100_000.0)),
            hot_reloadable: false,
            description: "Inbound message buffer size per channel",
            affects: "message_backpressure",
            outcome_signal: "message_drop_or_block_rate",
            evidence_required: "Channel buffer utilization analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.circuitBreakerThreshold",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(5),
            bounds: Some((1.0, 100.0)),
            hot_reloadable: true,
            description: "Consecutive channel errors before the channel is halted",
            affects: "message_reliability",
            outcome_signal: "channel_availability",
            evidence_required: "Channel error patterns and recovery times",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.haltedHealthCheckIntervalSecs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(60),
            bounds: Some((1.0, 3600.0)),
            hot_reloadable: true,
            description: "Health-check interval for halted messaging channels",
            affects: "message_recovery",
            outcome_signal: "halted_channel_recovery_time",
            evidence_required: "Channel recovery timing analysis",
            direction_hint: TuningDirection::Lower,
        },
        ParameterSpec {
            key: "messaging.rpcTimeoutSecs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(10),
            bounds: Some((1.0, 300.0)),
            hot_reloadable: true,
            description: "Timeout in seconds for Semeion RPC calls",
            affects: "message_rpc",
            outcome_signal: "rpc_timeout_rate",
            evidence_required: "Semeion RPC duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.healthTimeoutSecs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(2),
            bounds: Some((1.0, 60.0)),
            hot_reloadable: true,
            description: "Timeout in seconds for messaging health checks",
            affects: "message_health_checks",
            outcome_signal: "health_check_timeout_rate",
            evidence_required: "Health check latency distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.receiveTimeoutSecs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(15),
            bounds: Some((1.0, 300.0)),
            hot_reloadable: true,
            description: "Timeout in seconds waiting for a Semeion response",
            affects: "message_receive",
            outcome_signal: "receive_timeout_rate",
            evidence_required: "Receive wait duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.agentDispatchTimeoutSecs",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((10.0, 3600.0)),
            hot_reloadable: true,
            description: "Default timeout in seconds for agent-dispatch tool calls",
            affects: "message_agent_dispatch",
            outcome_signal: "agent_dispatch_timeout_rate",
            evidence_required: "Agent dispatch duration distribution",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "messaging.maxConcurrentHandlers",
            section: "messaging",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(64),
            bounds: Some((1.0, 10_000.0)),
            hot_reloadable: true,
            description: "Maximum concurrent inbound-message handler tasks",
            affects: "message_concurrency",
            outcome_signal: "handler_queue_latency",
            evidence_required: "Handler concurrency and latency analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Daemon behavior ──
        ParameterSpec {
            key: "daemonBehavior.prosocheAnomalySampleSize",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(15),
            bounds: Some((2.0, 1000.0)),
            hot_reloadable: true,
            description: "Samples used for prosoche anomaly detection",
            affects: "daemon_prosoche",
            outcome_signal: "anomaly_detection_precision",
            evidence_required: "Prosoche anomaly sample size analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "daemonBehavior.runnerOutputMode",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Str("summary"),
            bounds: None,
            hot_reloadable: true,
            description: "Daemon task output logging policy: summary, brief, or explicit unsafe full",
            affects: "daemon_runner_output",
            outcome_signal: "runner_output_privacy",
            evidence_required: "Private deployment diagnostics need full redacted output",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "daemonBehavior.runnerOutputBriefHeadLines",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(5),
            bounds: Some((1.0, 100.0)),
            hot_reloadable: true,
            description: "Task output head lines included in runner brief summaries",
            affects: "daemon_runner_output",
            outcome_signal: "runner_summary_usefulness",
            evidence_required: "Runner output summary review",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "daemonBehavior.runnerOutputBriefTailLines",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(3),
            bounds: Some((1.0, 100.0)),
            hot_reloadable: true,
            description: "Task output tail lines included in runner brief summaries",
            affects: "daemon_runner_output",
            outcome_signal: "runner_summary_usefulness",
            evidence_required: "Runner output summary review",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "daemonBehavior.watchdogBackoffBaseSecs",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(2),
            bounds: Some((1.0, 60.0)),
            hot_reloadable: true,
            description: "Base duration in seconds for watchdog restart backoff",
            affects: "daemon_reliability",
            outcome_signal: "restart_recovery_time",
            evidence_required: "Restart backoff vs. recovery time analysis",
            direction_hint: TuningDirection::Contextual,
        },
        ParameterSpec {
            key: "daemonBehavior.watchdogBackoffCapSecs",
            section: "daemonBehavior",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(300),
            bounds: Some((10.0, 3600.0)),
            hot_reloadable: true,
            description: "Maximum watchdog restart backoff duration in seconds",
            affects: "daemon_reliability",
            outcome_signal: "restart_recovery_time",
            evidence_required: "Maximum downtime tolerance analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Knowledge — content limits ──
        ParameterSpec {
            key: "knowledge.maxContentLength",
            section: "knowledge",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Int(102_400),
            bounds: Some((1_024.0, 10_485_760.0)),
            hot_reloadable: true,
            description: "Maximum byte length for fact content strings",
            affects: "knowledge_storage_capacity",
            outcome_signal: "content_truncation_rate",
            evidence_required: "Fact content length distribution",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Manifest — memory entries ──
        ParameterSpec {
            key: "agents.defaults.behavior.manifestMaxEntries",
            section: "agents.defaults.behavior",
            tier: ParameterTier::PerAgent,
            default: ParameterValue::Int(200),
            bounds: Some((10.0, 10_000.0)),
            hot_reloadable: true,
            description: "Maximum memory entries in a single manifest for side-query pre-filtering",
            affects: "recall_quality",
            outcome_signal: "side_query_recall_precision",
            evidence_required: "Manifest size vs. recall precision analysis",
            direction_hint: TuningDirection::Contextual,
        },
        // ── Credential — refresh threshold ──
        ParameterSpec {
            key: "credential.refreshThresholdSecs",
            section: "credential",
            tier: ParameterTier::Deployment,
            default: ParameterValue::Duration(3_600),
            bounds: Some((60.0, 86_400.0)),
            hot_reloadable: true,
            description: "Refresh token when less than this many seconds remain before expiry",
            affects: "credential_management",
            outcome_signal: "token_refresh_failure_rate",
            evidence_required: "Token expiry distribution and refresh success rates",
            direction_hint: TuningDirection::Contextual,
        },
    ]
}

#[cfg(test)]
#[path = "registry_tests.rs"]
mod registry_tests;
