//! Streaming chat component state machine.
//!
//! This module implements the state management logic for a streaming chat
//! component in Dioxus. It processes `StreamEvent`s into renderable state,
//! with 100ms debounce for text deltas to avoid excessive re-renders.
//!
//! # Architecture
//!
//! ```text
//!   ┌─────────────┐     stream_turn()     ┌──────────────┐
//!   │  User Input  │ ───────────────────►  │  SSE Stream   │
//!   │  Component   │                       │  (per-turn)   │
//!   └─────────────┘                       └──────┬───────┘
//!                                                │
//!                                    StreamEvent  │
//!                                                ▼
//!   ┌─────────────┐   100ms debounce   ┌──────────────┐
//!   │   Rendered   │ ◄──────────────── │  ChatState    │
//!   │   Output     │                   │  (signals)    │
//!   └─────────────┘                    └──────────────┘
//! ```
//!
//! # Signal-based state
//!
//! In Dioxus, each piece of mutable UI state is a `Signal<T>`. When
//! written, dependents re-render. The `ChatState` below models what
//! signals would hold; in production, each field becomes a `Signal<T>`
//! inside a Dioxus component scope.
//!
//! # Debounce strategy
//!
//! Text deltas arrive at high frequency (every few tokens). Writing to
//! the signal on every delta causes excessive re-renders. Instead:
//!
//! 1. Accumulate deltas into a local buffer.
//! 2. Flush to the signal when 100ms elapses or a non-delta event arrives.
//! 3. Also flush on newlines (users notice line breaks immediately).
//!
//! This mirrors the TUI's 64-byte/newline markdown cache invalidation
//! but is tuned for Dioxus's virtual DOM diffing cost.

use std::time::{Duration, Instant};

use theatron_core::events::StreamEvent;
use theatron_core::id::NousId;

use crate::state::events::{ConnectionState, StreamingState, ToolCallInfo};
use crate::state::tools::{
    PlanCardState, PlanStatus, PlanStepState, RiskLevel, StepStatus, ToolApprovalState,
    ToolCallState, ToolStatus,
};

/// Debounce interval when the stream is delivering tokens rapidly.
const TEXT_DEBOUNCE_FAST: Duration = Duration::from_millis(100);
/// Debounce interval when the stream is slow (>500 ms between deltas).
///
/// WHY: Reducing to 50 ms when the stream pauses improves perceived
/// responsiveness -- partial words appear sooner instead of waiting a full
/// 100 ms after a long inter-token gap.
const TEXT_DEBOUNCE_SLOW: Duration = Duration::from_millis(50);
/// Inter-delta gap above which the stream is classified as "slow".
const SLOW_STREAM_THRESHOLD: Duration = Duration::from_millis(500);

/// A committed chat message in the conversation history.
#[derive(Debug, Clone)]
pub struct ChatMessage {
    /// Who sent this message.
    pub role: MessageRole,
    /// The message text content.
    pub content: String,
    /// Model that generated this message, if from an assistant.
    pub model: Option<String>,
    /// Number of tool calls made during this turn.
    pub tool_calls: u32,
    /// Input tokens consumed by this turn.
    pub input_tokens: u32,
    /// Output tokens produced by this turn.
    pub output_tokens: u32,
    /// Thinking/reasoning content captured during the turn.
    pub thinking: Option<String>,
    /// Rich tool call details for panel display in committed messages.
    pub tool_call_details: Vec<ToolCallState>,
    /// Planning cards associated with this message.
    pub plans: Vec<PlanCardState>,
}

/// Who produced a chat message.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum MessageRole {
    /// Message sent by the user.
    User,
    /// Message generated by the assistant.
    Assistant,
}

/// Complete chat state that drives the Dioxus component tree.
///
/// In a Dioxus component, each field here becomes a `Signal<T>`:
///
/// ```text
/// let messages = use_signal(Vec::new);
/// let streaming = use_signal(StreamingState::default);
/// let connection = use_signal(|| ConnectionState::Disconnected);
/// ```
///
/// The `ChatStateManager` below manages transitions; the signals
/// propagate changes to the rendered output.
#[derive(Debug, Clone)]
pub struct ChatState {
    /// Committed conversation history.
    pub messages: Vec<ChatMessage>,
    /// In-flight streaming state for the active turn.
    pub streaming: StreamingState,
    /// Global SSE connection state.
    pub connection: ConnectionState,
    /// Agent currently being chatted with.
    pub agent_id: Option<NousId>,
    /// Active session key.
    pub session_key: Option<String>,
}

impl Default for ChatState {
    fn default() -> Self {
        Self {
            messages: Vec::new(),
            streaming: StreamingState::default(),
            connection: ConnectionState::Disconnected,
            agent_id: None,
            session_key: None,
        }
    }
}

/// Manages `ChatState` transitions in response to `StreamEvent`s.
///
/// Encapsulates the debounce buffer and flush logic. In a Dioxus component,
/// this runs inside a `use_coroutine` that reads from the stream receiver
/// and writes into signals.
pub(crate) struct ChatStateManager {
    /// Pending text delta buffer: not yet flushed to state.
    text_buffer: String,
    /// Pending thinking delta buffer.
    thinking_buffer: String,
    /// Last time the text buffer was flushed.
    last_flush: Instant,
    /// Time of the most recent delta arrival -- used for adaptive debounce.
    last_delta: Instant,
}

impl Default for ChatStateManager {
    fn default() -> Self {
        Self::new()
    }
}

impl ChatStateManager {
    /// Create a new manager with empty buffers.
    #[must_use]
    pub(crate) fn new() -> Self {
        let now = Instant::now();
        Self {
            text_buffer: String::new(),
            thinking_buffer: String::new(),
            last_flush: now,
            last_delta: now,
        }
    }

    /// Effective debounce interval based on observed inter-delta gap.
    fn effective_debounce(&self) -> Duration {
        if self.last_delta.elapsed() >= SLOW_STREAM_THRESHOLD {
            TEXT_DEBOUNCE_SLOW
        } else {
            TEXT_DEBOUNCE_FAST
        }
    }

    /// Process a stream event and apply it to the chat state.
    ///
    /// Returns `true` if the state was modified in a way that should
    /// trigger a re-render (i.e., the signal should be written to).
    /// Returns `false` if the delta was buffered and no flush is needed yet.
    #[must_use]
    pub(crate) fn apply(&mut self, event: StreamEvent, state: &mut ChatState) -> bool {
        match event {
            StreamEvent::TurnStart {
                turn_id,
                session_id: _,
                nous_id: _,
            } => {
                state.streaming = StreamingState {
                    text: String::new(),
                    thinking: String::new(),
                    tool_calls: Vec::new(),
                    tool_call_details: Vec::new(),
                    approvals: Vec::new(),
                    plans: Vec::new(),
                    is_streaming: true,
                    turn_id: Some(turn_id),
                    error: None,
                };
                self.text_buffer.clear();
                self.thinking_buffer.clear();
                self.last_flush = Instant::now();
                true
            }
            StreamEvent::TextDelta(delta) => {
                let has_newline = delta.contains('\n');
                self.text_buffer.push_str(&delta);
                // WHY: Measure the effective debounce using the gap from the
                // PREVIOUS delta before resetting last_delta. Updating first
                // would always show a ~0ms gap and defeat the slow-stream detection.
                let flushed = self.maybe_flush_text(state, has_newline);
                self.last_delta = Instant::now();
                flushed
            }
            StreamEvent::ThinkingDelta(delta) => {
                let has_newline = delta.contains('\n');
                self.thinking_buffer.push_str(&delta);
                let flushed = self.maybe_flush_thinking(state, has_newline);
                self.last_delta = Instant::now();
                flushed
            }
            StreamEvent::ToolStart {
                tool_name,
                tool_id,
                input,
            } => {
                // Flush any pending text before recording tool start.
                self.flush_text(state);
                self.flush_thinking(state);
                state.streaming.tool_calls.push(ToolCallInfo {
                    tool_name: tool_name.clone(),
                    tool_id: tool_id.clone(),
                    is_error: false,
                    duration_ms: None,
                    completed: false,
                    input: input.clone(),
                    output: None,
                    error_message: None,
                });
                state.streaming.tool_call_details.push(ToolCallState {
                    tool_id,
                    tool_name,
                    status: ToolStatus::Running,
                    input,
                    output: None,
                    error_message: None,
                    duration_ms: None,
                });
                true
            }
            StreamEvent::ToolResult {
                tool_id,
                is_error,
                duration_ms,
                tool_name: _,
                result,
            } => {
                if let Some(tc) = state
                    .streaming
                    .tool_calls
                    .iter_mut()
                    .find(|tc| tc.tool_id == tool_id)
                {
                    tc.is_error = is_error;
                    tc.duration_ms = Some(duration_ms);
                    tc.completed = true;
                    tc.output = result.clone();
                    if is_error {
                        tc.error_message = result.clone();
                    }
                }
                if let Some(detail) = state
                    .streaming
                    .tool_call_details
                    .iter_mut()
                    .find(|d| d.tool_id == tool_id)
                {
                    detail.status = if is_error {
                        ToolStatus::Error
                    } else {
                        ToolStatus::Success
                    };
                    detail.duration_ms = Some(duration_ms);
                    if is_error {
                        detail.error_message = result;
                    } else {
                        detail.output = result;
                    }
                }
                true
            }
            StreamEvent::TurnComplete { outcome } => {
                // Flush remaining buffered text.
                self.flush_text(state);
                self.flush_thinking(state);

                let thinking = if state.streaming.thinking.is_empty() {
                    None
                } else {
                    Some(std::mem::take(&mut state.streaming.thinking))
                };
                let message = ChatMessage {
                    role: MessageRole::Assistant,
                    content: std::mem::take(&mut state.streaming.text),
                    model: Some(outcome.model),
                    tool_calls: outcome.tool_calls,
                    input_tokens: outcome.input_tokens,
                    output_tokens: outcome.output_tokens,
                    thinking,
                    tool_call_details: std::mem::take(&mut state.streaming.tool_call_details),
                    plans: std::mem::take(&mut state.streaming.plans),
                };
                state.messages.push(message);
                state.streaming = StreamingState::default();
                true
            }
            StreamEvent::TurnAbort { reason } => {
                self.flush_text(state);
                self.flush_thinking(state);
                tracing::info!(reason, "turn aborted");
                // Preserve partial text in history if any was generated.
                if !state.streaming.text.is_empty() {
                    let thinking = if state.streaming.thinking.is_empty() {
                        None
                    } else {
                        Some(std::mem::take(&mut state.streaming.thinking))
                    };
                    let message = ChatMessage {
                        role: MessageRole::Assistant,
                        content: std::mem::take(&mut state.streaming.text),
                        model: None,
                        tool_calls: 0,
                        input_tokens: 0,
                        output_tokens: 0,
                        thinking,
                        tool_call_details: std::mem::take(&mut state.streaming.tool_call_details),
                        plans: std::mem::take(&mut state.streaming.plans),
                    };
                    state.messages.push(message);
                }
                state.streaming = StreamingState::default();
                true
            }
            StreamEvent::Error(msg) => {
                self.flush_text(state);
                state.streaming.error = Some(msg);
                state.streaming.is_streaming = false;
                true
            }
            StreamEvent::ToolApprovalRequired {
                turn_id,
                tool_name,
                tool_id,
                input,
                risk,
                reason,
            } => {
                state.streaming.approvals.push(ToolApprovalState {
                    turn_id,
                    tool_id,
                    tool_name,
                    input,
                    risk: RiskLevel::from_str_lossy(&risk),
                    reason,
                    resolved: false,
                });
                true
            }
            StreamEvent::ToolApprovalResolved { tool_id, .. } => {
                if let Some(approval) = state
                    .streaming
                    .approvals
                    .iter_mut()
                    .find(|a| a.tool_id == tool_id)
                {
                    approval.resolved = true;
                }
                true
            }
            StreamEvent::PlanProposed { plan } => {
                let steps = plan
                    .steps
                    .iter()
                    .map(|s| PlanStepState {
                        id: s.id,
                        label: s.label.clone(),
                        status: parse_step_status(&s.status),
                        result: s.result.clone(),
                    })
                    .collect();
                state.streaming.plans.push(PlanCardState {
                    plan_id: plan.id,
                    steps,
                    status: PlanStatus::Proposed,
                });
                true
            }
            StreamEvent::PlanStepStart { plan_id, step_id } => {
                if let Some(plan) = state
                    .streaming
                    .plans
                    .iter_mut()
                    .find(|p| p.plan_id == plan_id)
                {
                    plan.status = PlanStatus::InProgress;
                    if let Some(step) = plan.steps.iter_mut().find(|s| s.id == step_id) {
                        step.status = StepStatus::InProgress;
                    }
                }
                true
            }
            StreamEvent::PlanStepComplete {
                plan_id,
                step_id,
                status,
            } => {
                if let Some(plan) = state
                    .streaming
                    .plans
                    .iter_mut()
                    .find(|p| p.plan_id == plan_id)
                {
                    if let Some(step) = plan.steps.iter_mut().find(|s| s.id == step_id) {
                        step.status = parse_step_status(&status);
                    }
                }
                true
            }
            StreamEvent::PlanComplete { plan_id, status } => {
                if let Some(plan) = state
                    .streaming
                    .plans
                    .iter_mut()
                    .find(|p| p.plan_id == plan_id)
                {
                    plan.status = PlanStatus::Complete { status };
                }
                true
            }
            // Future non-exhaustive variants: no state change.
            _ => false,
        }
    }

    /// Flush buffered text if the debounce interval has elapsed or a
    /// newline was received.
    #[must_use]
    fn maybe_flush_text(&mut self, state: &mut ChatState, has_newline: bool) -> bool {
        if has_newline || self.last_flush.elapsed() >= self.effective_debounce() {
            self.flush_text(state);
            return true;
        }
        false
    }

    /// Flush buffered thinking text with the same debounce logic.
    #[must_use]
    fn maybe_flush_thinking(&mut self, state: &mut ChatState, has_newline: bool) -> bool {
        if has_newline || self.last_flush.elapsed() >= self.effective_debounce() {
            self.flush_thinking(state);
            return true;
        }
        false
    }

    /// Unconditionally move buffered text into state.
    fn flush_text(&mut self, state: &mut ChatState) {
        if !self.text_buffer.is_empty() {
            state.streaming.text.push_str(&self.text_buffer);
            self.text_buffer.clear();
            self.last_flush = Instant::now();
        }
    }

    /// Unconditionally move buffered thinking text into state.
    fn flush_thinking(&mut self, state: &mut ChatState) {
        if !self.thinking_buffer.is_empty() {
            state.streaming.thinking.push_str(&self.thinking_buffer);
            self.thinking_buffer.clear();
        }
    }

    /// Force-flush all buffered text. Call this on a timer tick (100ms)
    /// from the Dioxus coroutine to ensure text is never stuck in the
    /// buffer longer than the debounce interval.
    #[must_use]
    pub(crate) fn tick(&mut self, state: &mut ChatState) -> bool {
        let mut changed = false;
        if !self.text_buffer.is_empty() {
            self.flush_text(state);
            changed = true;
        }
        if !self.thinking_buffer.is_empty() {
            self.flush_thinking(state);
            changed = true;
        }
        changed
    }
}

/// Map a server step-status string to a [`StepStatus`] enum value.
fn parse_step_status(s: &str) -> StepStatus {
    match s.to_ascii_lowercase().as_str() {
        "complete" | "completed" | "success" => StepStatus::Complete,
        "in_progress" | "running" | "active" => StepStatus::InProgress,
        "failed" | "error" => StepStatus::Failed,
        _ => StepStatus::Pending,
    }
}

/// Apply a connection state change from the global SSE stream.
pub(crate) fn apply_connection_event(state: &mut ChatState, connected: bool) {
    state.connection = if connected {
        ConnectionState::Connected
    } else {
        match &state.connection {
            ConnectionState::Reconnecting { attempt } => ConnectionState::Reconnecting {
                attempt: attempt + 1,
            },
            _ => ConnectionState::Reconnecting { attempt: 1 },
        }
    };
}

#[cfg(test)]
mod tests;
