//! Chat session and message state for the desktop chat view.

use theatron_core::id::{NousId, SessionId};

/// Role of a chat message sender.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Role {
    /// Message sent by the user.
    User,
    /// Response generated by the assistant.
    Assistant,
    /// System-level message (context, errors).
    System,
}


/// A single chat message in the conversation history.
#[derive(Debug, Clone, PartialEq)]
pub struct ChatMessage {
    /// Unique message identifier (index-based or server-provided).
    pub id: u64,
    /// Who sent this message.
    pub role: Role,
    /// Raw markdown content.
    pub content: String,
    /// Unix timestamp in seconds.
    pub timestamp: i64,
    /// Agent that produced this message (assistant messages only).
    pub agent_id: Option<NousId>,
    /// Number of tool calls made during this turn.
    pub tool_calls: u32,
    /// Extended thinking content, if any.
    pub thinking_content: Option<String>,
    /// Whether this message is still being streamed.
    pub is_streaming: bool,
    /// Model that generated this message.
    pub model: Option<String>,
    /// Input tokens consumed.
    pub input_tokens: u32,
    /// Output tokens produced.
    pub output_tokens: u32,
}

/// A chat session: one conversation with an agent.
#[derive(Debug, Clone)]
pub struct ChatSession {
    next_id: u64,
}

/// Store managing all chat sessions.
#[derive(Debug, Clone, Default)]
pub struct ChatStore;




/// Format a Unix timestamp as a relative time string.
#[must_use]
pub(crate) fn relative_time(timestamp: i64) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| {
            #[expect(clippy::as_conversions, reason = "epoch seconds fit in i64 until year 292B")]
            let secs = d.as_secs() as i64;
            secs
        })
        .unwrap_or(0);

    let delta = now - timestamp;
    if delta < 0 {
        return "just now".to_string();
    }

    #[expect(clippy::as_conversions, reason = "delta verified non-negative above")]
    let delta = delta as u64;
    match delta {
        0..=59 => "just now".to_string(),
        60..=3599 => {
            let m = delta / 60;
            format!("{m}m ago")
        }
        3600..=86399 => {
            let h = delta / 3600;
            format!("{h}h ago")
        }
        86400..=604799 => {
            let d = delta / 86400;
            format!("{d}d ago")
        }
        _ => {
            let w = delta / 604800;
            format!("{w}w ago")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relative_time_just_now() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now), "just now");
    }

    #[test]
    fn relative_time_minutes() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now - 120), "2m ago");
    }

    #[test]
    fn relative_time_hours() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now - 7200), "2h ago");
    }

    #[test]
    fn relative_time_future_is_just_now() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now + 600), "just now");
    }

}
