//! Node index abstraction.
//!
//! Defines [`Idx`] — the trait that all node index types must implement.
//! Implemented for `u8`, `u16`, `u32`, `u64`, `usize` and their signed equivalents.
//! The blanket impl is generated by the `impl_idx!` macro.

use std::fmt::Debug;
use std::iter::Sum;
use std::ops::{Range, RangeInclusive};
use std::sync::atomic::Ordering;

use atoi::FromRadix10;
use atomic::Atomic;

/// Abstraction over integer types used as node indices.
///
/// Implemented for all primitive integer types (`u8` through `usize`, `i8` through `isize`).
/// Choose `u32` for graphs with up to 4 billion nodes and `usize` when node ids
/// must interoperate with Rust slice indices on 64-bit platforms.
pub trait Idx:
    Copy
    + std::ops::Add<Output = Self>
    + std::ops::AddAssign
    + std::ops::Sub<Output = Self>
    + std::ops::Div<Output = Self>
    + std::ops::Mul<Output = Self>
    + Ord
    + Debug
    + Send
    + Sum
    + Sync
    + Sized
    + 'static
{
    /// Creates an index from a `usize`.
    ///
    /// Panics in debug builds if `idx` exceeds `Self::MAX`.
    fn new(idx: usize) -> Self;

    /// Returns the zero value for this index type.
    fn zero() -> Self;

    /// Converts the index to `usize` for use as a slice offset.
    fn index(self) -> usize;

    /// Iterator type returned by [`Idx::range`].
    type RangeIter: Iterator<Item = Self>;

    /// Returns an iterator over `self..end`.
    fn range(self, end: Self) -> Self::RangeIter;

    /// Iterator type returned by [`Idx::range_inclusive`].
    type RangeInclusiveIter: Iterator<Item = Self>;

    /// Returns an iterator over `self..=end`.
    fn range_inclusive(self, end: Self) -> Self::RangeInclusiveIter;

    /// Parses an index from a decimal byte slice.
    ///
    /// Returns `(value, bytes_consumed)`.
    fn parse(bytes: &[u8]) -> (Self, usize);

    /// Atomically loads the current value and increments it by one.
    fn get_and_increment(this: &Atomic<Self>, order: Ordering) -> Self {
        Self::fetch_add(this, Self::new(1), order)
    }

    /// Atomically adds `val` to `this` and returns the previous value.
    fn fetch_add(this: &Atomic<Self>, val: Self, order: Ordering) -> Self;
}

macro_rules! impl_idx {
    ($TYPE:ty) => {
        impl Idx for $TYPE {
            #[inline]
            fn new(idx: usize) -> Self {
                assert!(idx <= <$TYPE>::MAX as usize);
                idx as $TYPE
            }

            #[inline]
            fn zero() -> Self {
                0
            }

            #[inline]
            fn index(self) -> usize {
                self as usize
            }

            type RangeIter = Range<Self>;

            #[inline]
            fn range(self, end: Self) -> Self::RangeIter {
                self..end
            }

            type RangeInclusiveIter = RangeInclusive<Self>;

            #[inline]
            fn range_inclusive(self, end: Self) -> Self::RangeInclusiveIter {
                self..=end
            }

            #[inline]
            fn parse(bytes: &[u8]) -> (Self, usize) {
                FromRadix10::from_radix_10(bytes)
            }

            #[inline]
            fn fetch_add(this: &Atomic<$TYPE>, val: $TYPE, order: Ordering) -> $TYPE {
                this.fetch_add(val, order)
            }
        }
    };
}

impl_idx!(u8);
impl_idx!(u16);
impl_idx!(u32);
impl_idx!(u64);
impl_idx!(usize);

impl_idx!(i8);
impl_idx!(i16);
impl_idx!(i32);
impl_idx!(i64);
impl_idx!(isize);
