//! Stop word lists — KO, KU, LA, LT, LV, MS, MR, NO, FA, PL, PT, RO.

pub(crate) const KO: &[&str] = &[
    r#"!"#, r#"""#, r#"$"#, r#"%"#, r#"&"#, r#"'"#,
    r#"("#, r#")"#, r#"*"#, r#"+"#, r#","#, r#"-"#,
    r#"."#, r#"..."#, r#"0"#, r#"1"#, r#"2"#, r#"3"#,
    r#"4"#, r#"5"#, r#"6"#, r#"7"#, r#"8"#, r#"9"#,
    r#";"#, r#"<"#, r#"="#, r#">"#, r#"?"#, r#"@"#,
    r#"\"#, r#"^"#, r#"_"#, r#"`"#, r#"|"#, r#"~"#,
    r#"·"#, r#"—"#, r#"——"#, r#"‘"#, r#"’"#, r#"“"#,
    r#"”"#, r#"…"#, r#"、"#, r#"。"#, r#"〈"#, r#"〉"#,
    r#"《"#, r#"》"#, r#"가"#, r#"가까스로"#, r#"가령"#, r#"각"#,
    r#"각각"#, r#"각자"#, r#"각종"#, r#"갖고말하자면"#, r#"같다"#, r#"같이"#,
    r#"개의치않고"#, r#"거니와"#, r#"거바"#, r#"거의"#, r#"것"#, r#"것과 같이"#,
    r#"것들"#, r#"게다가"#, r#"게우다"#, r#"겨우"#, r#"견지에서"#, r#"결과에 이르다"#,
    r#"결국"#, r#"결론을 낼 수 있다"#, r#"겸사겸사"#, r#"고려하면"#, r#"고로"#, r#"곧"#,
    r#"공동으로"#, r#"과"#, r#"과연"#, r#"관계가 있다"#, r#"관계없이"#, r#"관련이 있다"#,
    r#"관하여"#, r#"관한"#, r#"관해서는"#, r#"구"#, r#"구체적으로"#, r#"구토하다"#,
    r#"그"#, r#"그들"#, r#"그때"#, r#"그래"#, r#"그래도"#, r#"그래서"#,
    r#"그러나"#, r#"그러니"#, r#"그러니까"#, r#"그러면"#, r#"그러므로"#, r#"그러한즉"#,
    r#"그런 까닭에"#, r#"그런데"#, r#"그런즉"#, r#"그럼"#, r#"그럼에도 불구하고"#, r#"그렇게 함으로써"#,
    r#"그렇지"#, r#"그렇지 않다면"#, r#"그렇지 않으면"#, r#"그렇지만"#, r#"그렇지않으면"#, r#"그리고"#,
    r#"그리하여"#, r#"그만이다"#, r#"그에 따르는"#, r#"그위에"#, r#"그저"#, r#"그중에서"#,
    r#"그치지 않다"#, r#"근거로"#, r#"근거하여"#, r#"기대여"#, r#"기점으로"#, r#"기준으로"#,
    r#"기타"#, r#"까닭으로"#, r#"까악"#, r#"까지"#, r#"까지 미치다"#, r#"까지도"#,
    r#"꽈당"#, r#"끙끙"#, r#"끼익"#, r#"나"#, r#"나머지는"#, r#"남들"#,
    r#"남짓"#, r#"너"#, r#"너희"#, r#"너희들"#, r#"네"#, r#"넷"#,
    r#"년"#, r#"논하지 않다"#, r#"놀라다"#, r#"누가 알겠는가"#, r#"누구"#, r#"다른"#,
    r#"다른 방면으로"#, r#"다만"#, r#"다섯"#, r#"다소"#, r#"다수"#, r#"다시 말하자면"#,
    r#"다시말하면"#, r#"다음"#, r#"다음에"#, r#"다음으로"#, r#"단지"#, r#"답다"#,
    r#"당신"#, r#"당장"#, r#"대로 하다"#, r#"대하면"#, r#"대하여"#, r#"대해 말하자면"#,
    r#"대해서"#, r#"댕그"#, r#"더구나"#, r#"더군다나"#, r#"더라도"#, r#"더불어"#,
    r#"더욱더"#, r#"더욱이는"#, r#"도달하다"#, r#"도착하다"#, r#"동시에"#, r#"동안"#,
    r#"된바에야"#, r#"된이상"#, r#"두번째로"#, r#"둘"#, r#"둥둥"#, r#"뒤따라"#,
    r#"뒤이어"#, r#"든간에"#, r#"들"#, r#"등"#, r#"등등"#, r#"딩동"#,
    r#"따라"#, r#"따라서"#, r#"따위"#, r#"따지지 않다"#, r#"딱"#, r#"때"#,
    r#"때가 되어"#, r#"때문에"#, r#"또"#, r#"또한"#, r#"뚝뚝"#, r#"라 해도"#,
    r#"령"#, r#"로"#, r#"로 인하여"#, r#"로부터"#, r#"로써"#, r#"륙"#,
    r#"를"#, r#"마음대로"#, r#"마저"#, r#"마저도"#, r#"마치"#, r#"막론하고"#,
    r#"만 못하다"#, r#"만약"#, r#"만약에"#, r#"만은 아니다"#, r#"만이 아니다"#, r#"만일"#,
    r#"만큼"#, r#"말하자면"#, r#"말할것도 없고"#, r#"매"#, r#"매번"#, r#"메쓰겁다"#,
    r#"몇"#, r#"모"#, r#"모두"#, r#"무렵"#, r#"무릎쓰고"#, r#"무슨"#,
    r#"무엇"#, r#"무엇때문에"#, r#"물론"#, r#"및"#, r#"바꾸어말하면"#, r#"바꾸어말하자면"#,
    r#"바꾸어서 말하면"#, r#"바꾸어서 한다면"#, r#"바꿔 말하면"#, r#"바로"#, r#"바와같이"#, r#"밖에 안된다"#,
    r#"반대로"#, r#"반대로 말하자면"#, r#"반드시"#, r#"버금"#, r#"보는데서"#, r#"보다더"#,
    r#"보드득"#, r#"본대로"#, r#"봐"#, r#"봐라"#, r#"부류의 사람들"#, r#"부터"#,
    r#"불구하고"#, r#"불문하고"#, r#"붕붕"#, r#"비걱거리다"#, r#"비교적"#, r#"비길수 없다"#,
    r#"비로소"#, r#"비록"#, r#"비슷하다"#, r#"비추어 보아"#, r#"비하면"#, r#"뿐만 아니라"#,
    r#"뿐만아니라"#, r#"뿐이다"#, r#"삐걱"#, r#"삐걱거리다"#, r#"사"#, r#"삼"#,
    r#"상대적으로 말하자면"#, r#"생각한대로"#, r#"설령"#, r#"설마"#, r#"설사"#, r#"셋"#,
    r#"소생"#, r#"소인"#, r#"솨"#, r#"쉿"#, r#"습니까"#, r#"습니다"#,
    r#"시각"#, r#"시간"#, r#"시작하여"#, r#"시초에"#, r#"시키다"#, r#"실로"#,
    r#"심지어"#, r#"아"#, r#"아니"#, r#"아니나다를가"#, r#"아니라면"#, r#"아니면"#,
    r#"아니었다면"#, r#"아래윗"#, r#"아무거나"#, r#"아무도"#, r#"아야"#, r#"아울러"#,
    r#"아이"#, r#"아이고"#, r#"아이구"#, r#"아이야"#, r#"아이쿠"#, r#"아하"#,
    r#"아홉"#, r#"안 그러면"#, r#"않기 위하여"#, r#"않기 위해서"#, r#"알 수 있다"#, r#"알았어"#,
    r#"앗"#, r#"앞에서"#, r#"앞의것"#, r#"야"#, r#"약간"#, r#"양자"#,
    r#"어"#, r#"어기여차"#, r#"어느"#, r#"어느 년도"#, r#"어느것"#, r#"어느곳"#,
    r#"어느때"#, r#"어느쪽"#, r#"어느해"#, r#"어디"#, r#"어때"#, r#"어떠한"#,
    r#"어떤"#, r#"어떤것"#, r#"어떤것들"#, r#"어떻게"#, r#"어떻해"#, r#"어이"#,
    r#"어째서"#, r#"어쨋든"#, r#"어쩔수 없다"#, r#"어찌"#, r#"어찌됏든"#, r#"어찌됏어"#,
    r#"어찌하든지"#, r#"어찌하여"#, r#"언제"#, r#"언젠가"#, r#"얼마"#, r#"얼마 안 되는 것"#,
    r#"얼마간"#, r#"얼마나"#, r#"얼마든지"#, r#"얼마만큼"#, r#"얼마큼"#, r#"엉엉"#,
    r#"에"#, r#"에 가서"#, r#"에 달려 있다"#, r#"에 대해"#, r#"에 있다"#, r#"에 한하다"#,
    r#"에게"#, r#"에서"#, r#"여"#, r#"여기"#, r#"여덟"#, r#"여러분"#,
    r#"여보시오"#, r#"여부"#, r#"여섯"#, r#"여전히"#, r#"여차"#, r#"연관되다"#,
    r#"연이서"#, r#"영"#, r#"영차"#, r#"옆사람"#, r#"예"#, r#"예를 들면"#,
    r#"예를 들자면"#, r#"예컨대"#, r#"예하면"#, r#"오"#, r#"오로지"#, r#"오르다"#,
    r#"오자마자"#, r#"오직"#, r#"오호"#, r#"오히려"#, r#"와"#, r#"와 같은 사람들"#,
    r#"와르르"#, r#"와아"#, r#"왜"#, r#"왜냐하면"#, r#"외에도"#, r#"요만큼"#,
    r#"요만한 것"#, r#"요만한걸"#, r#"요컨대"#, r#"우르르"#, r#"우리"#, r#"우리들"#,
    r#"우선"#, r#"우에 종합한것과같이"#, r#"운운"#, r#"월"#, r#"위에서 서술한바와같이"#, r#"위하여"#,
    r#"위해서"#, r#"윙윙"#, r#"육"#, r#"으로"#, r#"으로 인하여"#, r#"으로서"#,
    r#"으로써"#, r#"을"#, r#"응"#, r#"응당"#, r#"의"#, r#"의거하여"#,
    r#"의지하여"#, r#"의해"#, r#"의해되다"#, r#"의해서"#, r#"이"#, r#"이 되다"#,
    r#"이 때문에"#, r#"이 밖에"#, r#"이 외에"#, r#"이 정도의"#, r#"이것"#, r#"이곳"#,
    r#"이때"#, r#"이라면"#, r#"이래"#, r#"이러이러하다"#, r#"이러한"#, r#"이런"#,
    r#"이럴정도로"#, r#"이렇게 많은 것"#, r#"이렇게되면"#, r#"이렇게말하자면"#, r#"이렇구나"#, r#"이로 인하여"#,
    r#"이르기까지"#, r#"이리하여"#, r#"이만큼"#, r#"이번"#, r#"이봐"#, r#"이상"#,
    r#"이어서"#, r#"이었다"#, r#"이와 같다"#, r#"이와 같은"#, r#"이와 반대로"#, r#"이와같다면"#,
    r#"이외에도"#, r#"이용하여"#, r#"이유만으로"#, r#"이젠"#, r#"이지만"#, r#"이쪽"#,
    r#"이천구"#, r#"이천육"#, r#"이천칠"#, r#"이천팔"#, r#"인 듯하다"#, r#"인젠"#,
    r#"일"#, r#"일것이다"#, r#"일곱"#, r#"일단"#, r#"일때"#, r#"일반적으로"#,
    r#"일지라도"#, r#"임에 틀림없다"#, r#"입각하여"#, r#"입장에서"#, r#"잇따라"#, r#"있다"#,
    r#"자"#, r#"자기"#, r#"자기집"#, r#"자마자"#, r#"자신"#, r#"잠깐"#,
    r#"잠시"#, r#"저"#, r#"저것"#, r#"저것만큼"#, r#"저기"#, r#"저쪽"#,
    r#"저희"#, r#"전부"#, r#"전자"#, r#"전후"#, r#"점에서 보아"#, r#"정도에 이르다"#,
    r#"제"#, r#"제각기"#, r#"제외하고"#, r#"조금"#, r#"조차"#, r#"조차도"#,
    r#"졸졸"#, r#"좀"#, r#"좋아"#, r#"좍좍"#, r#"주룩주룩"#, r#"주저하지 않고"#,
    r#"줄은 몰랏다"#, r#"줄은모른다"#, r#"중에서"#, r#"중의하나"#, r#"즈음하여"#, r#"즉"#,
    r#"즉시"#, r#"지든지"#, r#"지만"#, r#"지말고"#, r#"진짜로"#, r#"쪽으로"#,
    r#"차라리"#, r#"참"#, r#"참나"#, r#"첫번째로"#, r#"쳇"#, r#"총적으로"#,
    r#"총적으로 말하면"#, r#"총적으로 보면"#, r#"칠"#, r#"콸콸"#, r#"쾅쾅"#, r#"쿵"#,
    r#"타다"#, r#"타인"#, r#"탕탕"#, r#"토하다"#, r#"통하여"#, r#"툭"#,
    r#"퉤"#, r#"틈타"#, r#"팍"#, r#"팔"#, r#"퍽"#, r#"펄렁"#,
    r#"하"#, r#"하게될것이다"#, r#"하게하다"#, r#"하겠는가"#, r#"하고 있다"#, r#"하고있었다"#,
    r#"하곤하였다"#, r#"하구나"#, r#"하기 때문에"#, r#"하기 위하여"#, r#"하기는한데"#, r#"하기만 하면"#,
    r#"하기보다는"#, r#"하기에"#, r#"하나"#, r#"하느니"#, r#"하는 김에"#, r#"하는 편이 낫다"#,
    r#"하는것도"#, r#"하는것만 못하다"#, r#"하는것이 낫다"#, r#"하는바"#, r#"하더라도"#, r#"하도다"#,
    r#"하도록시키다"#, r#"하도록하다"#, r#"하든지"#, r#"하려고하다"#, r#"하마터면"#, r#"하면 할수록"#,
    r#"하면된다"#, r#"하면서"#, r#"하물며"#, r#"하여금"#, r#"하여야"#, r#"하자마자"#,
    r#"하지 않는다면"#, r#"하지 않도록"#, r#"하지마"#, r#"하지마라"#, r#"하지만"#, r#"하하"#,
    r#"한 까닭에"#, r#"한 이유는"#, r#"한 후"#, r#"한다면"#, r#"한다면 몰라도"#, r#"한데"#,
    r#"한마디"#, r#"한적이있다"#, r#"한켠으로는"#, r#"한항목"#, r#"할 따름이다"#, r#"할 생각이다"#,
    r#"할 줄 안다"#, r#"할 지경이다"#, r#"할 힘이 있다"#, r#"할때"#, r#"할만하다"#, r#"할망정"#,
    r#"할뿐"#, r#"할수있다"#, r#"할수있어"#, r#"할줄알다"#, r#"할지라도"#, r#"할지언정"#,
    r#"함께"#, r#"해도된다"#, r#"해도좋다"#, r#"해봐요"#, r#"해서는 안된다"#, r#"해야한다"#,
    r#"해요"#, r#"했어요"#, r#"향하다"#, r#"향하여"#, r#"향해서"#, r#"허"#,
    r#"허걱"#, r#"허허"#, r#"헉"#, r#"헉헉"#, r#"헐떡헐떡"#, r#"형식으로 쓰여"#,
    r#"혹시"#, r#"혹은"#, r#"혼자"#, r#"훨씬"#, r#"휘익"#, r#"휴"#,
    r#"흐흐"#, r#"흥"#, r#"힘입어"#, r#"︿"#, r#"！"#, r#"＃"#,
    r#"＄"#, r#"％"#, r#"＆"#, r#"（"#, r#"）"#, r#"＊"#,
    r#"＋"#, r#"，"#, r#"０"#, r#"１"#, r#"２"#, r#"３"#,
    r#"４"#, r#"５"#, r#"６"#, r#"７"#, r#"８"#, r#"９"#,
    r#"："#, r#"；"#, r#"＜"#, r#"＞"#, r#"？"#, r#"＠"#,
    r#"［"#, r#"］"#, r#"｛"#, r#"｜"#, r#"｝"#, r#"～"#,
    r#"￥"#,
];

pub(crate) const KU: &[&str] = &[
    r#"ئێمە"#, r#"ئێوە"#, r#"ئەم"#, r#"ئەو"#, r#"ئەوان"#, r#"ئەوەی"#,
    r#"بۆ"#, r#"بێ"#, r#"بێجگە"#, r#"بە"#, r#"بەبێ"#, r#"بەدەم"#,
    r#"بەردەم"#, r#"بەرلە"#, r#"بەرەوی"#, r#"بەرەوە"#, r#"بەلای"#, r#"بەپێی"#,
    r#"تۆ"#, r#"تێ"#, r#"جگە"#, r#"دوای"#, r#"دوو"#, r#"دە"#,
    r#"دەکات"#, r#"دەگەڵ"#, r#"سەر"#, r#"لێ"#, r#"لە"#, r#"لەبابەت"#,
    r#"لەباتی"#, r#"لەبارەی"#, r#"لەبرێتی"#, r#"لەبن"#, r#"لەبەر"#, r#"لەبەینی"#,
    r#"لەدەم"#, r#"لەرێ"#, r#"لەرێگا"#, r#"لەرەوی"#, r#"لەسەر"#, r#"لەلایەن"#,
    r#"لەناو"#, r#"لەنێو"#, r#"لەو"#, r#"لەپێناوی"#, r#"لەژێر"#, r#"لەگەڵ"#,
    r#"من"#, r#"ناو"#, r#"نێوان"#, r#"هەر"#, r#"هەروەها"#, r#"و"#,
    r#"وەک"#, r#"پاش"#, r#"پێ"#, r#"پێش"#, r#"چەند"#, r#"کرد"#,
    r#"کە"#, r#"ی"#,
];

pub(crate) const LA: &[&str] = &[
    r#"a"#, r#"ab"#, r#"ac"#, r#"ad"#, r#"at"#, r#"atque"#,
    r#"aut"#, r#"autem"#, r#"cum"#, r#"de"#, r#"dum"#, r#"e"#,
    r#"erant"#, r#"erat"#, r#"est"#, r#"et"#, r#"etiam"#, r#"ex"#,
    r#"haec"#, r#"hic"#, r#"hoc"#, r#"in"#, r#"ita"#, r#"me"#,
    r#"nec"#, r#"neque"#, r#"non"#, r#"per"#, r#"qua"#, r#"quae"#,
    r#"quam"#, r#"qui"#, r#"quibus"#, r#"quidem"#, r#"quo"#, r#"quod"#,
    r#"re"#, r#"rebus"#, r#"rem"#, r#"res"#, r#"sed"#, r#"si"#,
    r#"sic"#, r#"sunt"#, r#"tamen"#, r#"tandem"#, r#"te"#, r#"ut"#,
    r#"vel"#,
];

pub(crate) const LT: &[&str] = &[
    r#"abi"#, r#"abidvi"#, r#"abiejose"#, r#"abiejuose"#, r#"abiejø"#, r#"abiem"#,
    r#"abigaliai"#, r#"abipus"#, r#"abu"#, r#"abudu"#, r#"ai"#, r#"ana"#,
    r#"anaiptol"#, r#"anaisiais"#, r#"anajai"#, r#"anajam"#, r#"anajame"#, r#"anapus"#,
    r#"anas"#, r#"anasai"#, r#"anasis"#, r#"anei"#, r#"aniedvi"#, r#"anieji"#,
    r#"aniesiems"#, r#"anoji"#, r#"anojo"#, r#"anojoje"#, r#"anokia"#, r#"anoks"#,
    r#"anosiomis"#, r#"anosioms"#, r#"anosios"#, r#"anosiose"#, r#"anot"#, r#"ant"#,
    r#"antai"#, r#"anuodu"#, r#"anuoju"#, r#"anuosiuose"#, r#"anuosius"#, r#"anàja"#,
    r#"anàjà"#, r#"anàjá"#, r#"anàsias"#, r#"anøjø"#, r#"apie"#, r#"aplink"#,
    r#"ar"#, r#"arba"#, r#"argi"#, r#"arti"#, r#"aukðèiau"#, r#"að"#,
    r#"be"#, r#"bei"#, r#"beje"#, r#"bemaþ"#, r#"bent"#, r#"bet"#,
    r#"betgi"#, r#"beveik"#, r#"dar"#, r#"dargi"#, r#"daugmaþ"#, r#"deja"#,
    r#"dëka"#, r#"dël"#, r#"dëlei"#, r#"dëlto"#, r#"ech"#, r#"et"#,
    r#"gal"#, r#"galbût"#, r#"galgi"#, r#"gan"#, r#"gana"#, r#"gi"#,
    r#"greta"#, r#"idant"#, r#"iki"#, r#"ir"#, r#"irgi"#, r#"it"#,
    r#"itin"#, r#"ið"#, r#"iðilgai"#, r#"iðvis"#, r#"jaisiais"#, r#"jajai"#,
    r#"jajam"#, r#"jajame"#, r#"jei"#, r#"jeigu"#, r#"ji"#, r#"jiedu"#,
    r#"jiedvi"#, r#"jieji"#, r#"jiesiems"#, r#"jinai"#, r#"jis"#, r#"jisai"#,
    r#"jog"#, r#"joji"#, r#"jojo"#, r#"jojoje"#, r#"jokia"#, r#"joks"#,
    r#"josiomis"#, r#"josioms"#, r#"josios"#, r#"josiose"#, r#"judu"#, r#"judvi"#,
    r#"juk"#, r#"jumis"#, r#"jums"#, r#"jumyse"#, r#"juodu"#, r#"juoju"#,
    r#"juosiuose"#, r#"juosius"#, r#"jus"#, r#"jàja"#, r#"jàjà"#, r#"jàsias"#,
    r#"jájá"#, r#"jøjø"#, r#"jûs"#, r#"jûsiðkis"#, r#"jûsiðkë"#, r#"jûsø"#,
    r#"kad"#, r#"kada"#, r#"kadangi"#, r#"kai"#, r#"kaip"#, r#"kaipgi"#,
    r#"kas"#, r#"katra"#, r#"katras"#, r#"katriedvi"#, r#"katruodu"#, r#"kaþin"#,
    r#"kaþkas"#, r#"kaþkatra"#, r#"kaþkatras"#, r#"kaþkokia"#, r#"kaþkoks"#, r#"kaþkuri"#,
    r#"kaþkuris"#, r#"kiaurai"#, r#"kiek"#, r#"kiekvienas"#, r#"kieno"#, r#"kita"#,
    r#"kitas"#, r#"kitokia"#, r#"kitoks"#, r#"kodël"#, r#"kokia"#, r#"koks"#,
    r#"kol"#, r#"kolei"#, r#"kone"#, r#"kuomet"#, r#"kur"#, r#"kurgi"#,
    r#"kuri"#, r#"kuriedvi"#, r#"kuris"#, r#"kuriuodu"#, r#"lai"#, r#"lig"#,
    r#"ligi"#, r#"link"#, r#"lyg"#, r#"man"#, r#"manaisiais"#, r#"manajai"#,
    r#"manajam"#, r#"manajame"#, r#"manas"#, r#"manasai"#, r#"manasis"#, r#"mane"#,
    r#"manieji"#, r#"maniesiems"#, r#"manim"#, r#"manimi"#, r#"maniðkis"#, r#"maniðkë"#,
    r#"mano"#, r#"manoji"#, r#"manojo"#, r#"manojoje"#, r#"manosiomis"#, r#"manosioms"#,
    r#"manosios"#, r#"manosiose"#, r#"manuoju"#, r#"manuosiuose"#, r#"manuosius"#, r#"manyje"#,
    r#"manàja"#, r#"manàjà"#, r#"manàjá"#, r#"manàsias"#, r#"manæs"#, r#"manøjø"#,
    r#"mat"#, r#"maþdaug"#, r#"maþne"#, r#"mes"#, r#"mudu"#, r#"mudvi"#,
    r#"mumis"#, r#"mums"#, r#"mumyse"#, r#"mus"#, r#"mûsiðkis"#, r#"mûsiðkë"#,
    r#"mûsø"#, r#"na"#, r#"nagi"#, r#"ne"#, r#"nebe"#, r#"nebent"#,
    r#"negi"#, r#"negu"#, r#"nei"#, r#"nejau"#, r#"nejaugi"#, r#"nekaip"#,
    r#"nelyginant"#, r#"nes"#, r#"net"#, r#"netgi"#, r#"netoli"#, r#"neva"#,
    r#"nors"#, r#"nuo"#, r#"në"#, r#"o"#, r#"ogi"#, r#"oi"#,
    r#"paeiliui"#, r#"pagal"#, r#"pakeliui"#, r#"palaipsniui"#, r#"palei"#, r#"pas"#,
    r#"pasak"#, r#"paskos"#, r#"paskui"#, r#"paskum"#, r#"pat"#, r#"pati"#,
    r#"patiems"#, r#"paties"#, r#"pats"#, r#"patys"#, r#"patá"#, r#"paèiais"#,
    r#"paèiam"#, r#"paèiame"#, r#"paèiu"#, r#"paèiuose"#, r#"paèius"#, r#"paèiø"#,
    r#"per"#, r#"pernelyg"#, r#"pirm"#, r#"pirma"#, r#"pirmiau"#, r#"po"#,
    r#"prie"#, r#"prieð"#, r#"prieðais"#, r#"pro"#, r#"pusiau"#, r#"rasi"#,
    r#"rodos"#, r#"sau"#, r#"savaisiais"#, r#"savajai"#, r#"savajam"#, r#"savajame"#,
    r#"savas"#, r#"savasai"#, r#"savasis"#, r#"save"#, r#"savieji"#, r#"saviesiems"#,
    r#"savimi"#, r#"saviðkis"#, r#"saviðkë"#, r#"savo"#, r#"savoji"#, r#"savojo"#,
    r#"savojoje"#, r#"savosiomis"#, r#"savosioms"#, r#"savosios"#, r#"savosiose"#, r#"savuoju"#,
    r#"savuosiuose"#, r#"savuosius"#, r#"savyje"#, r#"savàja"#, r#"savàjà"#, r#"savàjá"#,
    r#"savàsias"#, r#"savæs"#, r#"savøjø"#, r#"skersai"#, r#"skradþiai"#, r#"staèiai"#,
    r#"su"#, r#"sulig"#, r#"ta"#, r#"tad"#, r#"tai"#, r#"taigi"#,
    r#"taip"#, r#"taipogi"#, r#"taisiais"#, r#"tajai"#, r#"tajam"#, r#"tajame"#,
    r#"tamsta"#, r#"tarp"#, r#"tarsi"#, r#"tartum"#, r#"tarytum"#, r#"tas"#,
    r#"tasai"#, r#"tau"#, r#"tavaisiais"#, r#"tavajai"#, r#"tavajam"#, r#"tavajame"#,
    r#"tavas"#, r#"tavasai"#, r#"tavasis"#, r#"tave"#, r#"tavieji"#, r#"taviesiems"#,
    r#"tavimi"#, r#"taviðkis"#, r#"taviðkë"#, r#"tavo"#, r#"tavoji"#, r#"tavojo"#,
    r#"tavojoje"#, r#"tavosiomis"#, r#"tavosioms"#, r#"tavosios"#, r#"tavosiose"#, r#"tavuoju"#,
    r#"tavuosiuose"#, r#"tavuosius"#, r#"tavyje"#, r#"tavàja"#, r#"tavàjà"#, r#"tavàjá"#,
    r#"tavàsias"#, r#"tavæs"#, r#"tavøjø"#, r#"taèiau"#, r#"te"#, r#"tegu"#,
    r#"tegul"#, r#"tiedvi"#, r#"tieji"#, r#"ties"#, r#"tiesiems"#, r#"tiesiog"#,
    r#"tik"#, r#"tikriausiai"#, r#"tiktai"#, r#"toji"#, r#"tojo"#, r#"tojoje"#,
    r#"tokia"#, r#"toks"#, r#"tol"#, r#"tolei"#, r#"toliau"#, r#"tosiomis"#,
    r#"tosioms"#, r#"tosios"#, r#"tosiose"#, r#"tu"#, r#"tuodu"#, r#"tuoju"#,
    r#"tuosiuose"#, r#"tuosius"#, r#"turbût"#, r#"tàja"#, r#"tàjà"#, r#"tàjá"#,
    r#"tàsias"#, r#"tøjø"#, r#"tûlas"#, r#"uþ"#, r#"uþtat"#, r#"uþvis"#,
    r#"va"#, r#"vai"#, r#"viduj"#, r#"vidury"#, r#"vien"#, r#"vienas"#,
    r#"vienokia"#, r#"vienoks"#, r#"vietoj"#, r#"virð"#, r#"virðuj"#, r#"virðum"#,
    r#"vis"#, r#"vis dëlto"#, r#"visa"#, r#"visas"#, r#"visgi"#, r#"visokia"#,
    r#"visoks"#, r#"vos"#, r#"vël"#, r#"vëlgi"#, r#"ypaè"#, r#"á"#,
    r#"ákypai"#, r#"ástriþai"#, r#"ðalia"#, r#"ðe"#, r#"ði"#, r#"ðiaisiais"#,
    r#"ðiajai"#, r#"ðiajam"#, r#"ðiajame"#, r#"ðiapus"#, r#"ðiedvi"#, r#"ðieji"#,
    r#"ðiesiems"#, r#"ðioji"#, r#"ðiojo"#, r#"ðiojoje"#, r#"ðiokia"#, r#"ðioks"#,
    r#"ðiosiomis"#, r#"ðiosioms"#, r#"ðiosios"#, r#"ðiosiose"#, r#"ðis"#, r#"ðisai"#,
    r#"ðit"#, r#"ðita"#, r#"ðitas"#, r#"ðitiedvi"#, r#"ðitokia"#, r#"ðitoks"#,
    r#"ðituodu"#, r#"ðiuodu"#, r#"ðiuoju"#, r#"ðiuosiuose"#, r#"ðiuosius"#, r#"ðiàja"#,
    r#"ðiàjà"#, r#"ðiàsias"#, r#"ðiøjø"#, r#"ðtai"#, r#"ðájá"#, r#"þemiau"#,
];

pub(crate) const LV: &[&str] = &[
    r#"aiz"#, r#"ap"#, r#"apakš"#, r#"apakšpus"#, r#"ar"#, r#"arī"#,
    r#"augšpus"#, r#"bet"#, r#"bez"#, r#"bija"#, r#"biji"#, r#"biju"#,
    r#"bijām"#, r#"bijāt"#, r#"būs"#, r#"būsi"#, r#"būsiet"#, r#"būsim"#,
    r#"būt"#, r#"būšu"#, r#"caur"#, r#"diemžēl"#, r#"diezin"#, r#"droši"#,
    r#"dēļ"#, r#"esam"#, r#"esat"#, r#"esi"#, r#"esmu"#, r#"gan"#,
    r#"gar"#, r#"iekam"#, r#"iekams"#, r#"iekām"#, r#"iekāms"#, r#"iekš"#,
    r#"iekšpus"#, r#"ik"#, r#"ir"#, r#"it"#, r#"itin"#, r#"iz"#,
    r#"ja"#, r#"jau"#, r#"jeb"#, r#"jebšu"#, r#"jel"#, r#"jo"#,
    r#"jā"#, r#"ka"#, r#"kamēr"#, r#"kaut"#, r#"kolīdz"#, r#"kopš"#,
    r#"kā"#, r#"kļuva"#, r#"kļuvi"#, r#"kļuvu"#, r#"kļuvām"#, r#"kļuvāt"#,
    r#"kļūs"#, r#"kļūsi"#, r#"kļūsiet"#, r#"kļūsim"#, r#"kļūst"#, r#"kļūstam"#,
    r#"kļūstat"#, r#"kļūsti"#, r#"kļūstu"#, r#"kļūt"#, r#"kļūšu"#, r#"labad"#,
    r#"lai"#, r#"lejpus"#, r#"līdz"#, r#"līdzko"#, r#"ne"#, r#"nebūt"#,
    r#"nedz"#, r#"nekā"#, r#"nevis"#, r#"nezin"#, r#"no"#, r#"nu"#,
    r#"nē"#, r#"otrpus"#, r#"pa"#, r#"par"#, r#"pat"#, r#"pie"#,
    r#"pirms"#, r#"pret"#, r#"priekš"#, r#"pār"#, r#"pēc"#, r#"starp"#,
    r#"tad"#, r#"tak"#, r#"tapi"#, r#"taps"#, r#"tapsi"#, r#"tapsiet"#,
    r#"tapsim"#, r#"tapt"#, r#"tapāt"#, r#"tapšu"#, r#"taču"#, r#"te"#,
    r#"tiec"#, r#"tiek"#, r#"tiekam"#, r#"tiekat"#, r#"tieku"#, r#"tik"#,
    r#"tika"#, r#"tikai"#, r#"tiki"#, r#"tikko"#, r#"tiklab"#, r#"tiklīdz"#,
    r#"tiks"#, r#"tiksiet"#, r#"tiksim"#, r#"tikt"#, r#"tiku"#, r#"tikvien"#,
    r#"tikām"#, r#"tikāt"#, r#"tikšu"#, r#"tomēr"#, r#"topat"#, r#"turpretim"#,
    r#"turpretī"#, r#"tā"#, r#"tādēļ"#, r#"tālab"#, r#"tāpēc"#, r#"un"#,
    r#"uz"#, r#"vai"#, r#"var"#, r#"varat"#, r#"varēja"#, r#"varēji"#,
    r#"varēju"#, r#"varējām"#, r#"varējāt"#, r#"varēs"#, r#"varēsi"#, r#"varēsiet"#,
    r#"varēsim"#, r#"varēt"#, r#"varēšu"#, r#"vien"#, r#"virs"#, r#"virspus"#,
    r#"vis"#, r#"viņpus"#, r#"zem"#, r#"ārpus"#, r#"šaipus"#,
];

pub(crate) const MS: &[&str] = &[
    r#"abdul"#, r#"abdullah"#, r#"acara"#, r#"ada"#, r#"adalah"#, r#"ahmad"#,
    r#"air"#, r#"akan"#, r#"akhbar"#, r#"akhir"#, r#"aktiviti"#, r#"alam"#,
    r#"amat"#, r#"amerika"#, r#"anak"#, r#"anggota"#, r#"antara"#, r#"antarabangsa"#,
    r#"apa"#, r#"apabila"#, r#"april"#, r#"as"#, r#"asas"#, r#"asean"#,
    r#"asia"#, r#"asing"#, r#"atas"#, r#"atau"#, r#"australia"#, r#"awal"#,
    r#"awam"#, r#"bagaimanapun"#, r#"bagi"#, r#"bahagian"#, r#"bahan"#, r#"baharu"#,
    r#"bahawa"#, r#"baik"#, r#"bandar"#, r#"bank"#, r#"banyak"#, r#"barangan"#,
    r#"baru"#, r#"baru-baru"#, r#"bawah"#, r#"beberapa"#, r#"bekas"#, r#"beliau"#,
    r#"belum"#, r#"berada"#, r#"berakhir"#, r#"berbanding"#, r#"berdasarkan"#, r#"berharap"#,
    r#"berikutan"#, r#"berjaya"#, r#"berjumlah"#, r#"berkaitan"#, r#"berkata"#, r#"berkenaan"#,
    r#"berlaku"#, r#"bermula"#, r#"bernama"#, r#"bernilai"#, r#"bersama"#, r#"berubah"#,
    r#"besar"#, r#"bhd"#, r#"bidang"#, r#"bilion"#, r#"bn"#, r#"boleh"#,
    r#"bukan"#, r#"bulan"#, r#"bursa"#, r#"cadangan"#, r#"china"#, r#"dagangan"#,
    r#"dalam"#, r#"dan"#, r#"dana"#, r#"dapat"#, r#"dari"#, r#"daripada"#,
    r#"dasar"#, r#"datang"#, r#"datuk"#, r#"demikian"#, r#"dengan"#, r#"depan"#,
    r#"derivatives"#, r#"dewan"#, r#"di"#, r#"diadakan"#, r#"dibuka"#, r#"dicatatkan"#,
    r#"dijangka"#, r#"diniagakan"#, r#"dis"#, r#"disember"#, r#"ditutup"#, r#"dolar"#,
    r#"dr"#, r#"dua"#, r#"dunia"#, r#"ekonomi"#, r#"eksekutif"#, r#"eksport"#,
    r#"empat"#, r#"enam"#, r#"faedah"#, r#"feb"#, r#"global"#, r#"hadapan"#,
    r#"hanya"#, r#"harga"#, r#"hari"#, r#"hasil"#, r#"hingga"#, r#"hubungan"#,
    r#"ia"#, r#"iaitu"#, r#"ialah"#, r#"indeks"#, r#"india"#, r#"indonesia"#,
    r#"industri"#, r#"ini"#, r#"islam"#, r#"isnin"#, r#"isu"#, r#"itu"#,
    r#"jabatan"#, r#"jalan"#, r#"jan"#, r#"jawatan"#, r#"jawatankuasa"#, r#"jepun"#,
    r#"jika"#, r#"jualan"#, r#"juga"#, r#"julai"#, r#"jumaat"#, r#"jumlah"#,
    r#"jun"#, r#"juta"#, r#"kadar"#, r#"kalangan"#, r#"kali"#, r#"kami"#,
    r#"kata"#, r#"katanya"#, r#"kaunter"#, r#"kawasan"#, r#"ke"#, r#"keadaan"#,
    r#"kecil"#, r#"kedua"#, r#"kedua-dua"#, r#"kedudukan"#, r#"kekal"#, r#"kementerian"#,
    r#"kemudahan"#, r#"kenaikan"#, r#"kenyataan"#, r#"kepada"#, r#"kepentingan"#, r#"keputusan"#,
    r#"kerajaan"#, r#"kerana"#, r#"kereta"#, r#"kerja"#, r#"kerjasama"#, r#"kes"#,
    r#"keselamatan"#, r#"keseluruhan"#, r#"kesihatan"#, r#"ketika"#, r#"ketua"#, r#"keuntungan"#,
    r#"kewangan"#, r#"khamis"#, r#"kini"#, r#"kira-kira"#, r#"kita"#, r#"klci"#,
    r#"klibor"#, r#"komposit"#, r#"kontrak"#, r#"kos"#, r#"kuala"#, r#"kuasa"#,
    r#"kukuh"#, r#"kumpulan"#, r#"lagi"#, r#"lain"#, r#"langkah"#, r#"laporan"#,
    r#"lebih"#, r#"lepas"#, r#"lima"#, r#"lot"#, r#"luar"#, r#"lumpur"#,
    r#"mac"#, r#"mahkamah"#, r#"mahu"#, r#"majlis"#, r#"makanan"#, r#"maklumat"#,
    r#"malam"#, r#"malaysia"#, r#"mana"#, r#"manakala"#, r#"masa"#, r#"masalah"#,
    r#"masih"#, r#"masing-masing"#, r#"masyarakat"#, r#"mata"#, r#"media"#, r#"mei"#,
    r#"melalui"#, r#"melihat"#, r#"memandangkan"#, r#"memastikan"#, r#"membantu"#, r#"membawa"#,
    r#"memberi"#, r#"memberikan"#, r#"membolehkan"#, r#"membuat"#, r#"mempunyai"#, r#"menambah"#,
    r#"menarik"#, r#"menawarkan"#, r#"mencapai"#, r#"mencatatkan"#, r#"mendapat"#, r#"mendapatkan"#,
    r#"menerima"#, r#"menerusi"#, r#"mengadakan"#, r#"mengambil"#, r#"mengenai"#, r#"menggalakkan"#,
    r#"menggunakan"#, r#"mengikut"#, r#"mengumumkan"#, r#"mengurangkan"#, r#"meningkat"#, r#"meningkatkan"#,
    r#"menjadi"#, r#"menjelang"#, r#"menokok"#, r#"menteri"#, r#"menunjukkan"#, r#"menurut"#,
    r#"menyaksikan"#, r#"menyediakan"#, r#"mereka"#, r#"merosot"#, r#"merupakan"#, r#"mesyuarat"#,
    r#"minat"#, r#"minggu"#, r#"minyak"#, r#"modal"#, r#"mohd"#, r#"mudah"#,
    r#"mungkin"#, r#"naik"#, r#"najib"#, r#"nasional"#, r#"negara"#, r#"negara-negara"#,
    r#"negeri"#, r#"niaga"#, r#"nilai"#, r#"nov"#, r#"ogos"#, r#"okt"#,
    r#"oleh"#, r#"operasi"#, r#"orang"#, r#"pada"#, r#"pagi"#, r#"paling"#,
    r#"pameran"#, r#"papan"#, r#"para"#, r#"paras"#, r#"parlimen"#, r#"parti"#,
    r#"pasaran"#, r#"pasukan"#, r#"pegawai"#, r#"pejabat"#, r#"pekerja"#, r#"pelabur"#,
    r#"pelaburan"#, r#"pelancongan"#, r#"pelanggan"#, r#"pelbagai"#, r#"peluang"#, r#"pembangunan"#,
    r#"pemberita"#, r#"pembinaan"#, r#"pemimpin"#, r#"pendapatan"#, r#"pendidikan"#, r#"penduduk"#,
    r#"penerbangan"#, r#"pengarah"#, r#"pengeluaran"#, r#"pengerusi"#, r#"pengguna"#, r#"pengurusan"#,
    r#"peniaga"#, r#"peningkatan"#, r#"penting"#, r#"peratus"#, r#"perdagangan"#, r#"perdana"#,
    r#"peringkat"#, r#"perjanjian"#, r#"perkara"#, r#"perkhidmatan"#, r#"perladangan"#, r#"perlu"#,
    r#"permintaan"#, r#"perniagaan"#, r#"persekutuan"#, r#"persidangan"#, r#"pertama"#, r#"pertubuhan"#,
    r#"pertumbuhan"#, r#"perusahaan"#, r#"peserta"#, r#"petang"#, r#"pihak"#, r#"pilihan"#,
    r#"pinjaman"#, r#"polis"#, r#"politik"#, r#"presiden"#, r#"prestasi"#, r#"produk"#,
    r#"program"#, r#"projek"#, r#"proses"#, r#"proton"#, r#"pukul"#, r#"pula"#,
    r#"pusat"#, r#"rabu"#, r#"rakan"#, r#"rakyat"#, r#"ramai"#, r#"rantau"#,
    r#"raya"#, r#"rendah"#, r#"ringgit"#, r#"rumah"#, r#"sabah"#, r#"sahaja"#,
    r#"saham"#, r#"sama"#, r#"sarawak"#, r#"satu"#, r#"sawit"#, r#"saya"#,
    r#"sdn"#, r#"sebagai"#, r#"sebahagian"#, r#"sebanyak"#, r#"sebarang"#, r#"sebelum"#,
    r#"sebelumnya"#, r#"sebuah"#, r#"secara"#, r#"sedang"#, r#"segi"#, r#"sehingga"#,
    r#"sejak"#, r#"sekarang"#, r#"sektor"#, r#"sekuriti"#, r#"selain"#, r#"selama"#,
    r#"selasa"#, r#"selatan"#, r#"selepas"#, r#"seluruh"#, r#"semakin"#, r#"semalam"#,
    r#"semasa"#, r#"sementara"#, r#"semua"#, r#"semula"#, r#"sen"#, r#"sendiri"#,
    r#"seorang"#, r#"sepanjang"#, r#"seperti"#, r#"sept"#, r#"september"#, r#"serantau"#,
    r#"seri"#, r#"serta"#, r#"sesi"#, r#"setiap"#, r#"setiausaha"#, r#"sidang"#,
    r#"singapura"#, r#"sini"#, r#"sistem"#, r#"sokongan"#, r#"sri"#, r#"sudah"#,
    r#"sukan"#, r#"suku"#, r#"sumber"#, r#"supaya"#, r#"susut"#, r#"syarikat"#,
    r#"syed"#, r#"tahap"#, r#"tahun"#, r#"tan"#, r#"tanah"#, r#"tanpa"#,
    r#"tawaran"#, r#"teknologi"#, r#"telah"#, r#"tempat"#, r#"tempatan"#, r#"tempoh"#,
    r#"tenaga"#, r#"tengah"#, r#"tentang"#, r#"terbaik"#, r#"terbang"#, r#"terbesar"#,
    r#"terbuka"#, r#"terdapat"#, r#"terhadap"#, r#"termasuk"#, r#"tersebut"#, r#"terus"#,
    r#"tetapi"#, r#"thailand"#, r#"tiada"#, r#"tidak"#, r#"tiga"#, r#"timbalan"#,
    r#"timur"#, r#"tindakan"#, r#"tinggi"#, r#"tun"#, r#"tunai"#, r#"turun"#,
    r#"turut"#, r#"umno"#, r#"unit"#, r#"untuk"#, r#"untung"#, r#"urus"#,
    r#"usaha"#, r#"utama"#, r#"walaupun"#, r#"wang"#, r#"wanita"#, r#"wilayah"#,
    r#"yang"#,
];

pub(crate) const MR: &[&str] = &[
    r#"अधिक"#, r#"अनेक"#, r#"अशी"#, r#"असलयाचे"#, r#"असलेल्या"#, r#"असा"#,
    r#"असून"#, r#"असे"#, r#"आज"#, r#"आणि"#, r#"आता"#, r#"आपल्या"#,
    r#"आला"#, r#"आली"#, r#"आले"#, r#"आहे"#, r#"आहेत"#, r#"एक"#,
    r#"एका"#, r#"कमी"#, r#"करणयात"#, r#"करून"#, r#"का"#, r#"काम"#,
    r#"काय"#, r#"काही"#, r#"किवा"#, r#"की"#, r#"केला"#, r#"केली"#,
    r#"केले"#, r#"कोटी"#, r#"गेल्या"#, r#"घेऊन"#, r#"जात"#, r#"झाला"#,
    r#"झाली"#, r#"झाले"#, r#"झालेल्या"#, r#"टा"#, r#"डॉ"#, r#"तर"#,
    r#"तरी"#, r#"तसेच"#, r#"ता"#, r#"ती"#, r#"तीन"#, r#"ते"#,
    r#"तो"#, r#"त्या"#, r#"त्याचा"#, r#"त्याची"#, r#"त्याच्या"#, r#"त्याना"#,
    r#"त्यानी"#, r#"त्यामुळे"#, r#"त्री"#, r#"दिली"#, r#"दोन"#, r#"न"#,
    r#"नाही"#, r#"निर्ण्य"#, r#"पण"#, r#"पम"#, r#"परयतन"#, r#"पाटील"#,
    r#"म"#, r#"मात्र"#, r#"माहिती"#, r#"मी"#, r#"मुबी"#, r#"म्हणजे"#,
    r#"म्हणाले"#, r#"म्हणून"#, r#"या"#, r#"याचा"#, r#"याची"#, r#"याच्या"#,
    r#"याना"#, r#"यानी"#, r#"येणार"#, r#"येत"#, r#"येथील"#, r#"येथे"#,
    r#"लाख"#, r#"व"#, r#"व्यकत"#, r#"सर्व"#, r#"सागित्ले"#, r#"सुरू"#,
    r#"हजार"#, r#"हा"#, r#"ही"#, r#"हे"#, r#"होणार"#, r#"होत"#,
    r#"होता"#, r#"होती"#, r#"होते"#,
];

pub(crate) const NO: &[&str] = &[
    r#"alle"#, r#"andre"#, r#"arbeid"#, r#"at"#, r#"av"#, r#"bare"#,
    r#"begge"#, r#"ble"#, r#"blei"#, r#"bli"#, r#"blir"#, r#"blitt"#,
    r#"bort"#, r#"bra"#, r#"bruke"#, r#"både"#, r#"båe"#, r#"da"#,
    r#"de"#, r#"deg"#, r#"dei"#, r#"deim"#, r#"deira"#, r#"deires"#,
    r#"dem"#, r#"den"#, r#"denne"#, r#"der"#, r#"dere"#, r#"deres"#,
    r#"det"#, r#"dette"#, r#"di"#, r#"din"#, r#"disse"#, r#"ditt"#,
    r#"du"#, r#"dykk"#, r#"dykkar"#, r#"då"#, r#"eg"#, r#"ein"#,
    r#"eit"#, r#"eitt"#, r#"eller"#, r#"elles"#, r#"en"#, r#"ene"#,
    r#"eneste"#, r#"enhver"#, r#"enn"#, r#"er"#, r#"et"#, r#"ett"#,
    r#"etter"#, r#"folk"#, r#"for"#, r#"fordi"#, r#"forsûke"#, r#"fra"#,
    r#"få"#, r#"før"#, r#"fûr"#, r#"fûrst"#, r#"gjorde"#, r#"gjûre"#,
    r#"god"#, r#"gå"#, r#"ha"#, r#"hadde"#, r#"han"#, r#"hans"#,
    r#"har"#, r#"hennar"#, r#"henne"#, r#"hennes"#, r#"her"#, r#"hjå"#,
    r#"ho"#, r#"hoe"#, r#"honom"#, r#"hoss"#, r#"hossen"#, r#"hun"#,
    r#"hva"#, r#"hvem"#, r#"hver"#, r#"hvilke"#, r#"hvilken"#, r#"hvis"#,
    r#"hvor"#, r#"hvordan"#, r#"hvorfor"#, r#"i"#, r#"ikke"#, r#"ikkje"#,
    r#"ingen"#, r#"ingi"#, r#"inkje"#, r#"inn"#, r#"innen"#, r#"inni"#,
    r#"ja"#, r#"jeg"#, r#"kan"#, r#"kom"#, r#"korleis"#, r#"korso"#,
    r#"kun"#, r#"kunne"#, r#"kva"#, r#"kvar"#, r#"kvarhelst"#, r#"kven"#,
    r#"kvi"#, r#"kvifor"#, r#"lage"#, r#"lang"#, r#"lik"#, r#"like"#,
    r#"makt"#, r#"man"#, r#"mange"#, r#"me"#, r#"med"#, r#"medan"#,
    r#"meg"#, r#"meget"#, r#"mellom"#, r#"men"#, r#"mens"#, r#"mer"#,
    r#"mest"#, r#"mi"#, r#"min"#, r#"mine"#, r#"mitt"#, r#"mot"#,
    r#"mye"#, r#"mykje"#, r#"må"#, r#"måte"#, r#"navn"#, r#"ned"#,
    r#"nei"#, r#"no"#, r#"noe"#, r#"noen"#, r#"noka"#, r#"noko"#,
    r#"nokon"#, r#"nokor"#, r#"nokre"#, r#"ny"#, r#"nå"#, r#"når"#,
    r#"og"#, r#"også"#, r#"om"#, r#"opp"#, r#"oss"#, r#"over"#,
    r#"part"#, r#"punkt"#, r#"på"#, r#"rett"#, r#"riktig"#, r#"samme"#,
    r#"sant"#, r#"seg"#, r#"selv"#, r#"si"#, r#"sia"#, r#"sidan"#,
    r#"siden"#, r#"sin"#, r#"sine"#, r#"sist"#, r#"sitt"#, r#"sjøl"#,
    r#"skal"#, r#"skulle"#, r#"slik"#, r#"slutt"#, r#"so"#, r#"som"#,
    r#"somme"#, r#"somt"#, r#"start"#, r#"stille"#, r#"så"#, r#"sånn"#,
    r#"tid"#, r#"til"#, r#"tilbake"#, r#"tilstand"#, r#"um"#, r#"under"#,
    r#"upp"#, r#"ut"#, r#"uten"#, r#"var"#, r#"vart"#, r#"varte"#,
    r#"ved"#, r#"verdi"#, r#"vere"#, r#"verte"#, r#"vi"#, r#"vil"#,
    r#"ville"#, r#"vite"#, r#"vore"#, r#"vors"#, r#"vort"#, r#"vår"#,
    r#"være"#, r#"vært"#, r#"vöre"#, r#"vört"#, r#"å"#,
];

pub(crate) const FA: &[&str] = &[
    r#"!"#, r#","#, r#"."#, r#":"#, r#";"#, r#"،"#,
    r#"؛"#, r#"؟"#, r#"آباد"#, r#"آره"#, r#"آری"#, r#"آمد"#,
    r#"آمده"#, r#"آن"#, r#"آنان"#, r#"آنجا"#, r#"آنطور"#, r#"آنقدر"#,
    r#"آنكه"#, r#"آنها"#, r#"آنچه"#, r#"آنکه"#, r#"آورد"#, r#"آورده"#,
    r#"آيد"#, r#"آی"#, r#"آیا"#, r#"آیند"#, r#"اتفاقا"#, r#"اثرِ"#,
    r#"احتراما"#, r#"احتمالا"#, r#"اخیر"#, r#"اری"#, r#"از"#, r#"ازجمله"#,
    r#"اساسا"#, r#"است"#, r#"استفاد"#, r#"استفاده"#, r#"اش"#, r#"اشکارا"#,
    r#"اصلا"#, r#"اصولا"#, r#"اعلام"#, r#"اغلب"#, r#"اكنون"#, r#"الان"#,
    r#"البته"#, r#"البتّه"#, r#"ام"#, r#"اما"#, r#"امروز"#, r#"امروزه"#,
    r#"امسال"#, r#"امشب"#, r#"امور"#, r#"ان"#, r#"انجام"#, r#"اند"#,
    r#"انشاالله"#, r#"انصافا"#, r#"انطور"#, r#"انقدر"#, r#"انها"#, r#"انچنان"#,
    r#"انکه"#, r#"انگار"#, r#"او"#, r#"اول"#, r#"اولا"#, r#"اي"#,
    r#"ايشان"#, r#"ايم"#, r#"اين"#, r#"اينكه"#, r#"اکثرا"#, r#"اکنون"#,
    r#"اگر"#, r#"ای"#, r#"ایا"#, r#"اید"#, r#"ایشان"#, r#"ایم"#,
    r#"این"#, r#"اینجا"#, r#"ایند"#, r#"اینطور"#, r#"اینقدر"#, r#"اینها"#,
    r#"اینچنین"#, r#"اینک"#, r#"اینکه"#, r#"اینگونه"#, r#"با"#, r#"بار"#,
    r#"بارة"#, r#"باره"#, r#"بارها"#, r#"باز"#, r#"بازهم"#, r#"باش"#,
    r#"باشد"#, r#"باشم"#, r#"باشند"#, r#"باشيم"#, r#"باشی"#, r#"باشید"#,
    r#"باشیم"#, r#"بالا"#, r#"بالاخره"#, r#"بالایِ"#, r#"بالطبع"#, r#"بايد"#,
    r#"باید"#, r#"بتوان"#, r#"بتواند"#, r#"بتوانی"#, r#"بتوانیم"#, r#"بخش"#,
    r#"بخشی"#, r#"بخواه"#, r#"بخواهد"#, r#"بخواهم"#, r#"بخواهند"#, r#"بخواهی"#,
    r#"بخواهید"#, r#"بخواهیم"#, r#"بد"#, r#"بدون"#, r#"بر"#, r#"برابر"#,
    r#"برابرِ"#, r#"براحتی"#, r#"براساس"#, r#"براستی"#, r#"براي"#, r#"برای"#,
    r#"برایِ"#, r#"برخوردار"#, r#"برخي"#, r#"برخی"#, r#"برداري"#, r#"برعکس"#,
    r#"بروز"#, r#"بزرگ"#, r#"بزودی"#, r#"بسا"#, r#"بسيار"#, r#"بسياري"#,
    r#"بسیار"#, r#"بسیاری"#, r#"بطور"#, r#"بعد"#, r#"بعدا"#, r#"بعدها"#,
    r#"بعری"#, r#"بعضا"#, r#"بعضي"#, r#"بلافاصله"#, r#"بلكه"#, r#"بله"#,
    r#"بلکه"#, r#"بلی"#, r#"بنابراين"#, r#"بنابراین"#, r#"بندي"#, r#"به"#,
    r#"بهتر"#, r#"بهترين"#, r#"بود"#, r#"بودم"#, r#"بودن"#, r#"بودند"#,
    r#"بوده"#, r#"بودی"#, r#"بودید"#, r#"بودیم"#, r#"بویژه"#, r#"بي"#,
    r#"بيست"#, r#"بيش"#, r#"بيشتر"#, r#"بيشتري"#, r#"بين"#, r#"بکن"#,
    r#"بکند"#, r#"بکنم"#, r#"بکنند"#, r#"بکنی"#, r#"بکنید"#, r#"بکنیم"#,
    r#"بگو"#, r#"بگوید"#, r#"بگویم"#, r#"بگویند"#, r#"بگویی"#, r#"بگویید"#,
    r#"بگوییم"#, r#"بگیر"#, r#"بگیرد"#, r#"بگیرم"#, r#"بگیرند"#, r#"بگیری"#,
    r#"بگیرید"#, r#"بگیریم"#, r#"بی"#, r#"بیا"#, r#"بیاب"#, r#"بیابد"#,
    r#"بیابم"#, r#"بیابند"#, r#"بیابی"#, r#"بیابید"#, r#"بیابیم"#, r#"بیاور"#,
    r#"بیاورد"#, r#"بیاورم"#, r#"بیاورند"#, r#"بیاوری"#, r#"بیاورید"#, r#"بیاوریم"#,
    r#"بیاید"#, r#"بیایم"#, r#"بیایند"#, r#"بیایی"#, r#"بیایید"#, r#"بیاییم"#,
    r#"بیرون"#, r#"بیرونِ"#, r#"بیش"#, r#"بیشتر"#, r#"بیشتری"#, r#"بین"#,
    r#"ت"#, r#"تا"#, r#"تازه"#, r#"تاكنون"#, r#"تان"#, r#"تاکنون"#,
    r#"تحت"#, r#"تر"#, r#"تر  براساس"#, r#"ترين"#, r#"تقریبا"#, r#"تلویحا"#,
    r#"تمام"#, r#"تماما"#, r#"تمامي"#, r#"تنها"#, r#"تو"#, r#"تواند"#,
    r#"توانست"#, r#"توانستم"#, r#"توانستن"#, r#"توانستند"#, r#"توانسته"#, r#"توانستی"#,
    r#"توانستیم"#, r#"توانم"#, r#"توانند"#, r#"توانی"#, r#"توانید"#, r#"توانیم"#,
    r#"توسط"#, r#"تولِ"#, r#"تویِ"#, r#"ثانیا"#, r#"جا"#, r#"جاي"#,
    r#"جايي"#, r#"جای"#, r#"جدا"#, r#"جديد"#, r#"جدید"#, r#"جريان"#,
    r#"جریان"#, r#"جز"#, r#"جلوگيري"#, r#"جلویِ"#, r#"جمعا"#, r#"جناح"#,
    r#"جهت"#, r#"حاضر"#, r#"حال"#, r#"حالا"#, r#"حتما"#, r#"حتي"#,
    r#"حتی"#, r#"حداکثر"#, r#"حدودا"#, r#"حدودِ"#, r#"حق"#, r#"خارجِ"#,
    r#"خب"#, r#"خدمات"#, r#"خصوصا"#, r#"خلاصه"#, r#"خواست"#, r#"خواستم"#,
    r#"خواستن"#, r#"خواستند"#, r#"خواسته"#, r#"خواستی"#, r#"خواستید"#, r#"خواستیم"#,
    r#"خواهد"#, r#"خواهم"#, r#"خواهند"#, r#"خواهيم"#, r#"خواهی"#, r#"خواهید"#,
    r#"خواهیم"#, r#"خوب"#, r#"خود"#, r#"خودت"#, r#"خودتان"#, r#"خودش"#,
    r#"خودشان"#, r#"خودم"#, r#"خودمان"#, r#"خوشبختانه"#, r#"خويش"#, r#"خویش"#,
    r#"خویشتن"#, r#"خیاه"#, r#"خیر"#, r#"خیلی"#, r#"داد"#, r#"دادم"#,
    r#"دادن"#, r#"دادند"#, r#"داده"#, r#"دادی"#, r#"دادید"#, r#"دادیم"#,
    r#"دار"#, r#"دارد"#, r#"دارم"#, r#"دارند"#, r#"داريم"#, r#"داری"#,
    r#"دارید"#, r#"داریم"#, r#"داشت"#, r#"داشتم"#, r#"داشتن"#, r#"داشتند"#,
    r#"داشته"#, r#"داشتی"#, r#"داشتید"#, r#"داشتیم"#, r#"دانست"#, r#"دانند"#,
    r#"دایم"#, r#"دایما"#, r#"در"#, r#"درباره"#, r#"درمجموع"#, r#"درون"#,
    r#"دریغ"#, r#"دقیقا"#, r#"دنبالِ"#, r#"ده"#, r#"دهد"#, r#"دهم"#,
    r#"دهند"#, r#"دهی"#, r#"دهید"#, r#"دهیم"#, r#"دو"#, r#"دوباره"#,
    r#"دوم"#, r#"ديده"#, r#"ديروز"#, r#"ديگر"#, r#"ديگران"#, r#"ديگري"#,
    r#"دیر"#, r#"دیروز"#, r#"دیگر"#, r#"دیگران"#, r#"دیگری"#, r#"را"#,
    r#"راحت"#, r#"راسا"#, r#"راستی"#, r#"راه"#, r#"رسما"#, r#"رسید"#,
    r#"رفت"#, r#"رفته"#, r#"رو"#, r#"روب"#, r#"روز"#, r#"روزانه"#,
    r#"روزهاي"#, r#"روي"#, r#"روی"#, r#"رویِ"#, r#"ريزي"#, r#"زمان"#,
    r#"زمانی"#, r#"زمینه"#, r#"زود"#, r#"زياد"#, r#"زير"#, r#"زيرا"#,
    r#"زیر"#, r#"زیرِ"#, r#"سابق"#, r#"ساخته"#, r#"سازي"#, r#"سالانه"#,
    r#"سالیانه"#, r#"سایر"#, r#"سراسر"#, r#"سرانجام"#, r#"سریعا"#, r#"سریِ"#,
    r#"سعي"#, r#"سمتِ"#, r#"سوم"#, r#"سوي"#, r#"سوی"#, r#"سویِ"#,
    r#"سپس"#, r#"شان"#, r#"شايد"#, r#"شاید"#, r#"شخصا"#, r#"شد"#,
    r#"شدم"#, r#"شدن"#, r#"شدند"#, r#"شده"#, r#"شدی"#, r#"شدید"#,
    r#"شدیدا"#, r#"شدیم"#, r#"شش"#, r#"شش  نداشته"#, r#"شما"#, r#"شناسي"#,
    r#"شود"#, r#"شوم"#, r#"شوند"#, r#"شونده"#, r#"شوی"#, r#"شوید"#,
    r#"شویم"#, r#"صرفا"#, r#"صورت"#, r#"ضدِّ"#, r#"ضدِّ"#, r#"ضمن"#,
    r#"طبعا"#, r#"طبقِ"#, r#"طبیعتا"#, r#"طرف"#, r#"طريق"#, r#"طریق"#,
    r#"طور"#, r#"طي"#, r#"طی"#, r#"ظاهرا"#, r#"عدم"#, r#"عقبِ"#,
    r#"علّتِ"#, r#"علیه"#, r#"عمدا"#, r#"عمدتا"#, r#"عمل"#, r#"عملا"#,
    r#"عنوان"#, r#"عنوانِ"#, r#"غالبا"#, r#"غير"#, r#"غیر"#, r#"فردا"#,
    r#"فعلا"#, r#"فقط"#, r#"فكر"#, r#"فوق"#, r#"قابل"#, r#"قبل"#,
    r#"قبلا"#, r#"قدری"#, r#"قصدِ"#, r#"قطعا"#, r#"كرد"#, r#"كردم"#,
    r#"كردن"#, r#"كردند"#, r#"كرده"#, r#"كسي"#, r#"كل"#, r#"كمتر"#,
    r#"كند"#, r#"كنم"#, r#"كنند"#, r#"كنيد"#, r#"كنيم"#, r#"كه"#,
    r#"لااقل"#, r#"لطفا"#, r#"لطفاً"#, r#"ما"#, r#"مان"#, r#"مانند"#,
    r#"مانندِ"#, r#"مبادا"#, r#"متاسفانه"#, r#"متعاقبا"#, r#"مثل"#, r#"مثلا"#,
    r#"مثلِ"#, r#"مجانی"#, r#"مجددا"#, r#"مجموعا"#, r#"مختلف"#, r#"مدام"#,
    r#"مدت"#, r#"مدّتی"#, r#"مردم"#, r#"مرسی"#, r#"مستقیما"#, r#"مسلما"#,
    r#"مطمینا"#, r#"معمولا"#, r#"مقابل"#, r#"ممکن"#, r#"من"#, r#"موارد"#,
    r#"مورد"#, r#"موقتا"#, r#"مي"#, r#"ميليارد"#, r#"ميليون"#, r#"مگر"#,
    r#"می"#, r#"می شود"#, r#"میان"#, r#"می‌رسد"#, r#"می‌رود"#, r#"می‌شود"#,
    r#"می‌کنیم"#, r#"ناشي"#, r#"نام"#, r#"ناگاه"#, r#"ناگهان"#, r#"ناگهانی"#,
    r#"نبايد"#, r#"نباید"#, r#"نبود"#, r#"نخست"#, r#"نخستين"#, r#"نخواهد"#,
    r#"نخواهم"#, r#"نخواهند"#, r#"نخواهی"#, r#"نخواهید"#, r#"نخواهیم"#, r#"ندارد"#,
    r#"ندارم"#, r#"ندارند"#, r#"نداری"#, r#"ندارید"#, r#"نداریم"#, r#"نداشت"#,
    r#"نداشتم"#, r#"نداشتند"#, r#"نداشته"#, r#"نداشتی"#, r#"نداشتید"#, r#"نداشتیم"#,
    r#"نزديك"#, r#"نزدِ"#, r#"نزدیکِ"#, r#"نسبتا"#, r#"نشان"#, r#"نشده"#,
    r#"نظير"#, r#"نظیر"#, r#"نكرده"#, r#"نمايد"#, r#"نمي"#, r#"نمی"#,
    r#"نمی‌شود"#, r#"نه"#, r#"نهایتا"#, r#"نوع"#, r#"نوعي"#, r#"نوعی"#,
    r#"نيز"#, r#"نيست"#, r#"نگاه"#, r#"نیز"#, r#"نیست"#, r#"ها"#,
    r#"هاي"#, r#"هايي"#, r#"های"#, r#"هایی"#, r#"هبچ"#, r#"هر"#,
    r#"هرچه"#, r#"هرگز"#, r#"هزار"#, r#"هست"#, r#"هستم"#, r#"هستند"#,
    r#"هستيم"#, r#"هستی"#, r#"هستید"#, r#"هستیم"#, r#"هفت"#, r#"هم"#,
    r#"همان"#, r#"همه"#, r#"همواره"#, r#"همين"#, r#"همچنان"#, r#"همچنين"#,
    r#"همچنین"#, r#"همچون"#, r#"همیشه"#, r#"همین"#, r#"هنوز"#, r#"هنگام"#,
    r#"هنگامِ"#, r#"هنگامی"#, r#"هيچ"#, r#"هیچ"#, r#"هیچگاه"#, r#"و"#,
    r#"واقعا"#, r#"واقعی"#, r#"وجود"#, r#"وسطِ"#, r#"وضع"#, r#"وقتي"#,
    r#"وقتی"#, r#"وقتیکه"#, r#"ولی"#, r#"وي"#, r#"وگو"#, r#"وی"#,
    r#"ویژه"#, r#"يا"#, r#"يابد"#, r#"يك"#, r#"يكديگر"#, r#"يكي"#,
    r#"ّه"#, r#"٪"#, r#"پارسال"#, r#"پاعینِ"#, r#"پس"#, r#"پنج"#,
    r#"پيش"#, r#"پیدا"#, r#"پیش"#, r#"پیشاپیش"#, r#"پیشتر"#, r#"پیشِ"#,
    r#"چرا"#, r#"چطور"#, r#"چقدر"#, r#"چنان"#, r#"چنانچه"#, r#"چنانکه"#,
    r#"چند"#, r#"چندین"#, r#"چنين"#, r#"چنین"#, r#"چه"#, r#"چهار"#,
    r#"چو"#, r#"چون"#, r#"چيزي"#, r#"چگونه"#, r#"چیز"#, r#"چیزی"#,
    r#"چیست"#, r#"کاش"#, r#"کامل"#, r#"کاملا"#, r#"کتبا"#, r#"کجا"#,
    r#"کجاست"#, r#"کدام"#, r#"کرد"#, r#"کردم"#, r#"کردن"#, r#"کردند"#,
    r#"کرده"#, r#"کردی"#, r#"کردید"#, r#"کردیم"#, r#"کس"#, r#"کسانی"#,
    r#"کسی"#, r#"کل"#, r#"کلا"#, r#"کم"#, r#"کماکان"#, r#"کمتر"#,
    r#"کمتری"#, r#"کمی"#, r#"کن"#, r#"کنار"#, r#"کنارِ"#, r#"کند"#,
    r#"کنم"#, r#"کنند"#, r#"کننده"#, r#"کنون"#, r#"کنونی"#, r#"کنی"#,
    r#"کنید"#, r#"کنیم"#, r#"که"#, r#"کو"#, r#"کَی"#, r#"کی"#,
    r#"گاه"#, r#"گاهی"#, r#"گذاري"#, r#"گذاشته"#, r#"گذشته"#, r#"گردد"#,
    r#"گرفت"#, r#"گرفتم"#, r#"گرفتن"#, r#"گرفتند"#, r#"گرفته"#, r#"گرفتی"#,
    r#"گرفتید"#, r#"گرفتیم"#, r#"گروهي"#, r#"گفت"#, r#"گفتم"#, r#"گفتن"#,
    r#"گفتند"#, r#"گفته"#, r#"گفتی"#, r#"گفتید"#, r#"گفتیم"#, r#"گه"#,
    r#"گهگاه"#, r#"گو"#, r#"گويد"#, r#"گويند"#, r#"گویا"#, r#"گوید"#,
    r#"گویم"#, r#"گویند"#, r#"گویی"#, r#"گویید"#, r#"گوییم"#, r#"گيرد"#,
    r#"گيري"#, r#"گیرد"#, r#"گیرم"#, r#"گیرند"#, r#"گیری"#, r#"گیرید"#,
    r#"گیریم"#, r#"ی"#, r#"یا"#, r#"یابد"#, r#"یابم"#, r#"یابند"#,
    r#"یابی"#, r#"یابید"#, r#"یابیم"#, r#"یافت"#, r#"یافتم"#, r#"یافتن"#,
    r#"یافته"#, r#"یافتی"#, r#"یافتید"#, r#"یافتیم"#, r#"یعنی"#, r#"یقینا"#,
    r#"یه"#, r#"یک"#, r#"یکی"#, r#"۰"#, r#"۱"#, r#"۲"#,
    r#"۳"#, r#"۴"#, r#"۵"#, r#"۶"#, r#"۷"#, r#"۸"#,
    r#"۹"#,
];

pub(crate) const PL: &[&str] = &[
    r#"a"#, r#"aby"#, r#"ach"#, r#"acz"#, r#"aczkolwiek"#, r#"aj"#,
    r#"albo"#, r#"ale"#, r#"ależ"#, r#"ani"#, r#"aż"#, r#"bardziej"#,
    r#"bardzo"#, r#"bez"#, r#"bo"#, r#"bowiem"#, r#"by"#, r#"byli"#,
    r#"bym"#, r#"bynajmniej"#, r#"być"#, r#"był"#, r#"była"#, r#"było"#,
    r#"były"#, r#"będzie"#, r#"będą"#, r#"cali"#, r#"cała"#, r#"cały"#,
    r#"chce"#, r#"choć"#, r#"ci"#, r#"ciebie"#, r#"cię"#, r#"co"#,
    r#"cokolwiek"#, r#"coraz"#, r#"coś"#, r#"czasami"#, r#"czasem"#, r#"czemu"#,
    r#"czy"#, r#"czyli"#, r#"często"#, r#"daleko"#, r#"dla"#, r#"dlaczego"#,
    r#"dlatego"#, r#"do"#, r#"dobrze"#, r#"dokąd"#, r#"dość"#, r#"dr"#,
    r#"dużo"#, r#"dwa"#, r#"dwaj"#, r#"dwie"#, r#"dwoje"#, r#"dzisiaj"#,
    r#"dziś"#, r#"gdy"#, r#"gdyby"#, r#"gdyż"#, r#"gdzie"#, r#"gdziekolwiek"#,
    r#"gdzieś"#, r#"go"#, r#"godz"#, r#"hab"#, r#"i"#, r#"ich"#,
    r#"ii"#, r#"iii"#, r#"ile"#, r#"im"#, r#"inna"#, r#"inne"#,
    r#"inny"#, r#"innych"#, r#"inż"#, r#"iv"#, r#"ix"#, r#"iż"#,
    r#"ja"#, r#"jak"#, r#"jakaś"#, r#"jakby"#, r#"jaki"#, r#"jakichś"#,
    r#"jakie"#, r#"jakiś"#, r#"jakiż"#, r#"jakkolwiek"#, r#"jako"#, r#"jakoś"#,
    r#"je"#, r#"jeden"#, r#"jedna"#, r#"jednak"#, r#"jednakże"#, r#"jedno"#,
    r#"jednym"#, r#"jedynie"#, r#"jego"#, r#"jej"#, r#"jemu"#, r#"jest"#,
    r#"jestem"#, r#"jeszcze"#, r#"jeśli"#, r#"jeżeli"#, r#"już"#, r#"ją"#,
    r#"każdy"#, r#"kiedy"#, r#"kierunku"#, r#"kilka"#, r#"kilku"#, r#"kimś"#,
    r#"kto"#, r#"ktokolwiek"#, r#"ktoś"#, r#"która"#, r#"które"#, r#"którego"#,
    r#"której"#, r#"który"#, r#"których"#, r#"którym"#, r#"którzy"#, r#"ku"#,
    r#"lat"#, r#"lecz"#, r#"lub"#, r#"ma"#, r#"mają"#, r#"mam"#,
    r#"mamy"#, r#"mało"#, r#"mgr"#, r#"mi"#, r#"miał"#, r#"mimo"#,
    r#"między"#, r#"mnie"#, r#"mną"#, r#"mogą"#, r#"moi"#, r#"moim"#,
    r#"moja"#, r#"moje"#, r#"może"#, r#"możliwe"#, r#"można"#, r#"mu"#,
    r#"musi"#, r#"my"#, r#"mój"#, r#"na"#, r#"nad"#, r#"nam"#,
    r#"nami"#, r#"nas"#, r#"nasi"#, r#"nasz"#, r#"nasza"#, r#"nasze"#,
    r#"naszego"#, r#"naszych"#, r#"natomiast"#, r#"natychmiast"#, r#"nawet"#, r#"nic"#,
    r#"nich"#, r#"nie"#, r#"niech"#, r#"niego"#, r#"niej"#, r#"niemu"#,
    r#"nigdy"#, r#"nim"#, r#"nimi"#, r#"nią"#, r#"niż"#, r#"no"#,
    r#"nowe"#, r#"np"#, r#"nr"#, r#"o"#, r#"o.o."#, r#"obok"#,
    r#"od"#, r#"ok"#, r#"około"#, r#"on"#, r#"ona"#, r#"one"#,
    r#"oni"#, r#"ono"#, r#"oraz"#, r#"oto"#, r#"owszem"#, r#"pan"#,
    r#"pana"#, r#"pani"#, r#"pl"#, r#"po"#, r#"pod"#, r#"podczas"#,
    r#"pomimo"#, r#"ponad"#, r#"ponieważ"#, r#"powinien"#, r#"powinna"#, r#"powinni"#,
    r#"powinno"#, r#"poza"#, r#"prawie"#, r#"prof"#, r#"przecież"#, r#"przed"#,
    r#"przede"#, r#"przedtem"#, r#"przez"#, r#"przy"#, r#"raz"#, r#"razie"#,
    r#"roku"#, r#"również"#, r#"sam"#, r#"sama"#, r#"się"#, r#"skąd"#,
    r#"sobie"#, r#"sobą"#, r#"sposób"#, r#"swoje"#, r#"są"#, r#"ta"#,
    r#"tak"#, r#"taka"#, r#"taki"#, r#"takich"#, r#"takie"#, r#"także"#,
    r#"tam"#, r#"te"#, r#"tego"#, r#"tej"#, r#"tel"#, r#"temu"#,
    r#"ten"#, r#"teraz"#, r#"też"#, r#"to"#, r#"tobie"#, r#"tobą"#,
    r#"toteż"#, r#"totobą"#, r#"trzeba"#, r#"tu"#, r#"tutaj"#, r#"twoi"#,
    r#"twoim"#, r#"twoja"#, r#"twoje"#, r#"twym"#, r#"twój"#, r#"ty"#,
    r#"tych"#, r#"tylko"#, r#"tym"#, r#"tys"#, r#"tzw"#, r#"tę"#,
    r#"u"#, r#"ul"#, r#"vi"#, r#"vii"#, r#"viii"#, r#"vol"#,
    r#"w"#, r#"wam"#, r#"wami"#, r#"was"#, r#"wasi"#, r#"wasz"#,
    r#"wasza"#, r#"wasze"#, r#"we"#, r#"według"#, r#"wie"#, r#"wiele"#,
    r#"wielu"#, r#"więc"#, r#"więcej"#, r#"wszyscy"#, r#"wszystkich"#, r#"wszystkie"#,
    r#"wszystkim"#, r#"wszystko"#, r#"wtedy"#, r#"www"#, r#"wy"#, r#"właśnie"#,
    r#"wśród"#, r#"xi"#, r#"xii"#, r#"xiii"#, r#"xiv"#, r#"xv"#,
    r#"z"#, r#"za"#, r#"zapewne"#, r#"zawsze"#, r#"zaś"#, r#"ze"#,
    r#"zeznowu"#, r#"znowu"#, r#"znów"#, r#"został"#, r#"zł"#, r#"żaden"#,
    r#"żadna"#, r#"żadne"#, r#"żadnych"#, r#"że"#, r#"żeby"#,
];

pub(crate) const PT: &[&str] = &[
    r#"a"#, r#"acerca"#, r#"adeus"#, r#"agora"#, r#"ainda"#, r#"alem"#,
    r#"algmas"#, r#"algo"#, r#"algumas"#, r#"alguns"#, r#"ali"#, r#"além"#,
    r#"ambas"#, r#"ambos"#, r#"ano"#, r#"anos"#, r#"antes"#, r#"ao"#,
    r#"aonde"#, r#"aos"#, r#"apenas"#, r#"apoio"#, r#"apontar"#, r#"apos"#,
    r#"após"#, r#"aquela"#, r#"aquelas"#, r#"aquele"#, r#"aqueles"#, r#"aqui"#,
    r#"aquilo"#, r#"as"#, r#"assim"#, r#"através"#, r#"atrás"#, r#"até"#,
    r#"aí"#, r#"baixo"#, r#"bastante"#, r#"bem"#, r#"boa"#, r#"boas"#,
    r#"bom"#, r#"bons"#, r#"breve"#, r#"cada"#, r#"caminho"#, r#"catorze"#,
    r#"cedo"#, r#"cento"#, r#"certamente"#, r#"certeza"#, r#"cima"#, r#"cinco"#,
    r#"coisa"#, r#"com"#, r#"como"#, r#"comprido"#, r#"conhecido"#, r#"conselho"#,
    r#"contra"#, r#"contudo"#, r#"corrente"#, r#"cuja"#, r#"cujas"#, r#"cujo"#,
    r#"cujos"#, r#"custa"#, r#"cá"#, r#"da"#, r#"daquela"#, r#"daquelas"#,
    r#"daquele"#, r#"daqueles"#, r#"dar"#, r#"das"#, r#"de"#, r#"debaixo"#,
    r#"dela"#, r#"delas"#, r#"dele"#, r#"deles"#, r#"demais"#, r#"dentro"#,
    r#"depois"#, r#"desde"#, r#"desligado"#, r#"dessa"#, r#"dessas"#, r#"desse"#,
    r#"desses"#, r#"desta"#, r#"destas"#, r#"deste"#, r#"destes"#, r#"deve"#,
    r#"devem"#, r#"deverá"#, r#"dez"#, r#"dezanove"#, r#"dezasseis"#, r#"dezassete"#,
    r#"dezoito"#, r#"dia"#, r#"diante"#, r#"direita"#, r#"dispoe"#, r#"dispoem"#,
    r#"diversa"#, r#"diversas"#, r#"diversos"#, r#"diz"#, r#"dizem"#, r#"dizer"#,
    r#"do"#, r#"dois"#, r#"dos"#, r#"doze"#, r#"duas"#, r#"durante"#,
    r#"dá"#, r#"dão"#, r#"dúvida"#, r#"e"#, r#"ela"#, r#"elas"#,
    r#"ele"#, r#"eles"#, r#"em"#, r#"embora"#, r#"enquanto"#, r#"entao"#,
    r#"entre"#, r#"então"#, r#"era"#, r#"eram"#, r#"essa"#, r#"essas"#,
    r#"esse"#, r#"esses"#, r#"esta"#, r#"estado"#, r#"estamos"#, r#"estar"#,
    r#"estará"#, r#"estas"#, r#"estava"#, r#"estavam"#, r#"este"#, r#"esteja"#,
    r#"estejam"#, r#"estejamos"#, r#"estes"#, r#"esteve"#, r#"estive"#, r#"estivemos"#,
    r#"estiver"#, r#"estivera"#, r#"estiveram"#, r#"estiverem"#, r#"estivermos"#, r#"estivesse"#,
    r#"estivessem"#, r#"estiveste"#, r#"estivestes"#, r#"estivéramos"#, r#"estivéssemos"#, r#"estou"#,
    r#"está"#, r#"estás"#, r#"estávamos"#, r#"estão"#, r#"eu"#, r#"exemplo"#,
    r#"falta"#, r#"fará"#, r#"favor"#, r#"faz"#, r#"fazeis"#, r#"fazem"#,
    r#"fazemos"#, r#"fazer"#, r#"fazes"#, r#"fazia"#, r#"faço"#, r#"fez"#,
    r#"fim"#, r#"final"#, r#"foi"#, r#"fomos"#, r#"for"#, r#"fora"#,
    r#"foram"#, r#"forem"#, r#"forma"#, r#"formos"#, r#"fosse"#, r#"fossem"#,
    r#"foste"#, r#"fostes"#, r#"fui"#, r#"fôramos"#, r#"fôssemos"#, r#"geral"#,
    r#"grande"#, r#"grandes"#, r#"grupo"#, r#"ha"#, r#"haja"#, r#"hajam"#,
    r#"hajamos"#, r#"havemos"#, r#"havia"#, r#"hei"#, r#"hoje"#, r#"hora"#,
    r#"horas"#, r#"houve"#, r#"houvemos"#, r#"houver"#, r#"houvera"#, r#"houveram"#,
    r#"houverei"#, r#"houverem"#, r#"houveremos"#, r#"houveria"#, r#"houveriam"#, r#"houvermos"#,
    r#"houverá"#, r#"houverão"#, r#"houveríamos"#, r#"houvesse"#, r#"houvessem"#, r#"houvéramos"#,
    r#"houvéssemos"#, r#"há"#, r#"hão"#, r#"iniciar"#, r#"inicio"#, r#"ir"#,
    r#"irá"#, r#"isso"#, r#"ista"#, r#"iste"#, r#"isto"#, r#"já"#,
    r#"lado"#, r#"lhe"#, r#"lhes"#, r#"ligado"#, r#"local"#, r#"logo"#,
    r#"longe"#, r#"lugar"#, r#"lá"#, r#"maior"#, r#"maioria"#, r#"maiorias"#,
    r#"mais"#, r#"mal"#, r#"mas"#, r#"me"#, r#"mediante"#, r#"meio"#,
    r#"menor"#, r#"menos"#, r#"meses"#, r#"mesma"#, r#"mesmas"#, r#"mesmo"#,
    r#"mesmos"#, r#"meu"#, r#"meus"#, r#"mil"#, r#"minha"#, r#"minhas"#,
    r#"momento"#, r#"muito"#, r#"muitos"#, r#"máximo"#, r#"mês"#, r#"na"#,
    r#"nada"#, r#"nao"#, r#"naquela"#, r#"naquelas"#, r#"naquele"#, r#"naqueles"#,
    r#"nas"#, r#"nem"#, r#"nenhuma"#, r#"nessa"#, r#"nessas"#, r#"nesse"#,
    r#"nesses"#, r#"nesta"#, r#"nestas"#, r#"neste"#, r#"nestes"#, r#"no"#,
    r#"noite"#, r#"nome"#, r#"nos"#, r#"nossa"#, r#"nossas"#, r#"nosso"#,
    r#"nossos"#, r#"nova"#, r#"novas"#, r#"nove"#, r#"novo"#, r#"novos"#,
    r#"num"#, r#"numa"#, r#"numas"#, r#"nunca"#, r#"nuns"#, r#"não"#,
    r#"nível"#, r#"nós"#, r#"número"#, r#"o"#, r#"obra"#, r#"obrigada"#,
    r#"obrigado"#, r#"oitava"#, r#"oitavo"#, r#"oito"#, r#"onde"#, r#"ontem"#,
    r#"onze"#, r#"os"#, r#"ou"#, r#"outra"#, r#"outras"#, r#"outro"#,
    r#"outros"#, r#"para"#, r#"parece"#, r#"parte"#, r#"partir"#, r#"paucas"#,
    r#"pegar"#, r#"pela"#, r#"pelas"#, r#"pelo"#, r#"pelos"#, r#"perante"#,
    r#"perto"#, r#"pessoas"#, r#"pode"#, r#"podem"#, r#"poder"#, r#"poderá"#,
    r#"podia"#, r#"pois"#, r#"ponto"#, r#"pontos"#, r#"por"#, r#"porque"#,
    r#"porquê"#, r#"portanto"#, r#"posição"#, r#"possivelmente"#, r#"posso"#, r#"possível"#,
    r#"pouca"#, r#"pouco"#, r#"poucos"#, r#"povo"#, r#"primeira"#, r#"primeiras"#,
    r#"primeiro"#, r#"primeiros"#, r#"promeiro"#, r#"propios"#, r#"proprio"#, r#"própria"#,
    r#"próprias"#, r#"próprio"#, r#"próprios"#, r#"próxima"#, r#"próximas"#, r#"próximo"#,
    r#"próximos"#, r#"puderam"#, r#"pôde"#, r#"põe"#, r#"põem"#, r#"quais"#,
    r#"qual"#, r#"qualquer"#, r#"quando"#, r#"quanto"#, r#"quarta"#, r#"quarto"#,
    r#"quatro"#, r#"que"#, r#"quem"#, r#"quer"#, r#"quereis"#, r#"querem"#,
    r#"queremas"#, r#"queres"#, r#"quero"#, r#"questão"#, r#"quieto"#, r#"quinta"#,
    r#"quinto"#, r#"quinze"#, r#"quáis"#, r#"quê"#, r#"relação"#, r#"sabe"#,
    r#"sabem"#, r#"saber"#, r#"se"#, r#"segunda"#, r#"segundo"#, r#"sei"#,
    r#"seis"#, r#"seja"#, r#"sejam"#, r#"sejamos"#, r#"sem"#, r#"sempre"#,
    r#"sendo"#, r#"ser"#, r#"serei"#, r#"seremos"#, r#"seria"#, r#"seriam"#,
    r#"será"#, r#"serão"#, r#"seríamos"#, r#"sete"#, r#"seu"#, r#"seus"#,
    r#"sexta"#, r#"sexto"#, r#"sim"#, r#"sistema"#, r#"sob"#, r#"sobre"#,
    r#"sois"#, r#"somente"#, r#"somos"#, r#"sou"#, r#"sua"#, r#"suas"#,
    r#"são"#, r#"sétima"#, r#"sétimo"#, r#"só"#, r#"tal"#, r#"talvez"#,
    r#"tambem"#, r#"também"#, r#"tanta"#, r#"tantas"#, r#"tanto"#, r#"tarde"#,
    r#"te"#, r#"tem"#, r#"temos"#, r#"tempo"#, r#"tendes"#, r#"tenha"#,
    r#"tenham"#, r#"tenhamos"#, r#"tenho"#, r#"tens"#, r#"tentar"#, r#"tentaram"#,
    r#"tente"#, r#"tentei"#, r#"ter"#, r#"terceira"#, r#"terceiro"#, r#"terei"#,
    r#"teremos"#, r#"teria"#, r#"teriam"#, r#"terá"#, r#"terão"#, r#"teríamos"#,
    r#"teu"#, r#"teus"#, r#"teve"#, r#"tinha"#, r#"tinham"#, r#"tipo"#,
    r#"tive"#, r#"tivemos"#, r#"tiver"#, r#"tivera"#, r#"tiveram"#, r#"tiverem"#,
    r#"tivermos"#, r#"tivesse"#, r#"tivessem"#, r#"tiveste"#, r#"tivestes"#, r#"tivéramos"#,
    r#"tivéssemos"#, r#"toda"#, r#"todas"#, r#"todo"#, r#"todos"#, r#"trabalhar"#,
    r#"trabalho"#, r#"treze"#, r#"três"#, r#"tu"#, r#"tua"#, r#"tuas"#,
    r#"tudo"#, r#"tão"#, r#"tém"#, r#"têm"#, r#"tínhamos"#, r#"um"#,
    r#"uma"#, r#"umas"#, r#"uns"#, r#"usa"#, r#"usar"#, r#"vai"#,
    r#"vais"#, r#"valor"#, r#"veja"#, r#"vem"#, r#"vens"#, r#"ver"#,
    r#"verdade"#, r#"verdadeiro"#, r#"vez"#, r#"vezes"#, r#"viagem"#, r#"vindo"#,
    r#"vinte"#, r#"você"#, r#"vocês"#, r#"vos"#, r#"vossa"#, r#"vossas"#,
    r#"vosso"#, r#"vossos"#, r#"vários"#, r#"vão"#, r#"vêm"#, r#"vós"#,
    r#"zero"#, r#"à"#, r#"às"#, r#"área"#, r#"é"#, r#"éramos"#,
    r#"és"#, r#"último"#,
];

pub(crate) const RO: &[&str] = &[
    r#"a"#, r#"abia"#, r#"acea"#, r#"aceasta"#, r#"această"#, r#"aceea"#,
    r#"aceeasi"#, r#"acei"#, r#"aceia"#, r#"acel"#, r#"acela"#, r#"acelasi"#,
    r#"acele"#, r#"acelea"#, r#"acest"#, r#"acesta"#, r#"aceste"#, r#"acestea"#,
    r#"acestei"#, r#"acestia"#, r#"acestui"#, r#"aceşti"#, r#"aceştia"#, r#"acolo"#,
    r#"acord"#, r#"acum"#, r#"adica"#, r#"ai"#, r#"aia"#, r#"aibă"#,
    r#"aici"#, r#"aiurea"#, r#"al"#, r#"ala"#, r#"alaturi"#, r#"ale"#,
    r#"alea"#, r#"alt"#, r#"alta"#, r#"altceva"#, r#"altcineva"#, r#"alte"#,
    r#"altfel"#, r#"alti"#, r#"altii"#, r#"altul"#, r#"am"#, r#"anume"#,
    r#"apoi"#, r#"ar"#, r#"are"#, r#"as"#, r#"asa"#, r#"asemenea"#,
    r#"asta"#, r#"astazi"#, r#"astea"#, r#"astfel"#, r#"astăzi"#, r#"asupra"#,
    r#"atare"#, r#"atat"#, r#"atata"#, r#"atatea"#, r#"atatia"#, r#"ati"#,
    r#"atit"#, r#"atita"#, r#"atitea"#, r#"atitia"#, r#"atunci"#, r#"au"#,
    r#"avea"#, r#"avem"#, r#"aveţi"#, r#"avut"#, r#"azi"#, r#"aş"#,
    r#"aşadar"#, r#"aţi"#, r#"b"#, r#"ba"#, r#"bine"#, r#"bucur"#,
    r#"bună"#, r#"c"#, r#"ca"#, r#"cam"#, r#"cand"#, r#"capat"#,
    r#"care"#, r#"careia"#, r#"carora"#, r#"caruia"#, r#"cat"#, r#"catre"#,
    r#"caut"#, r#"ce"#, r#"cea"#, r#"ceea"#, r#"cei"#, r#"ceilalti"#,
    r#"cel"#, r#"cele"#, r#"celor"#, r#"ceva"#, r#"chiar"#, r#"ci"#,
    r#"cinci"#, r#"cind"#, r#"cine"#, r#"cineva"#, r#"cit"#, r#"cita"#,
    r#"cite"#, r#"citeva"#, r#"citi"#, r#"citiva"#, r#"conform"#, r#"contra"#,
    r#"cu"#, r#"cui"#, r#"cum"#, r#"cumva"#, r#"curând"#, r#"curînd"#,
    r#"când"#, r#"cât"#, r#"câte"#, r#"câtva"#, r#"câţi"#, r#"cînd"#,
    r#"cît"#, r#"cîte"#, r#"cîtva"#, r#"cîţi"#, r#"că"#, r#"căci"#,
    r#"cărei"#, r#"căror"#, r#"cărui"#, r#"către"#, r#"d"#, r#"da"#,
    r#"daca"#, r#"dacă"#, r#"dar"#, r#"dat"#, r#"datorită"#, r#"dată"#,
    r#"dau"#, r#"de"#, r#"deasupra"#, r#"deci"#, r#"decit"#, r#"degraba"#,
    r#"deja"#, r#"deoarece"#, r#"departe"#, r#"desi"#, r#"despre"#, r#"deşi"#,
    r#"din"#, r#"dinaintea"#, r#"dintr"#, r#"dintr-"#, r#"dintre"#, r#"doar"#,
    r#"doi"#, r#"doilea"#, r#"două"#, r#"drept"#, r#"dupa"#, r#"după"#,
    r#"dă"#, r#"e"#, r#"ea"#, r#"ei"#, r#"el"#, r#"ele"#,
    r#"era"#, r#"eram"#, r#"este"#, r#"eu"#, r#"exact"#, r#"eşti"#,
    r#"f"#, r#"face"#, r#"fara"#, r#"fata"#, r#"fel"#, r#"fi"#,
    r#"fie"#, r#"fiecare"#, r#"fii"#, r#"fim"#, r#"fiu"#, r#"fiţi"#,
    r#"foarte"#, r#"fost"#, r#"frumos"#, r#"fără"#, r#"g"#, r#"geaba"#,
    r#"graţie"#, r#"h"#, r#"halbă"#, r#"i"#, r#"ia"#, r#"iar"#,
    r#"ieri"#, r#"ii"#, r#"il"#, r#"imi"#, r#"in"#, r#"inainte"#,
    r#"inapoi"#, r#"inca"#, r#"incit"#, r#"insa"#, r#"intr"#, r#"intre"#,
    r#"isi"#, r#"iti"#, r#"j"#, r#"k"#, r#"l"#, r#"la"#,
    r#"le"#, r#"li"#, r#"lor"#, r#"lui"#, r#"lângă"#, r#"lîngă"#,
    r#"m"#, r#"ma"#, r#"mai"#, r#"mare"#, r#"mea"#, r#"mei"#,
    r#"mele"#, r#"mereu"#, r#"meu"#, r#"mi"#, r#"mie"#, r#"mine"#,
    r#"mod"#, r#"mult"#, r#"multa"#, r#"multe"#, r#"multi"#, r#"multă"#,
    r#"mulţi"#, r#"mulţumesc"#, r#"mâine"#, r#"mîine"#, r#"mă"#, r#"n"#,
    r#"ne"#, r#"nevoie"#, r#"ni"#, r#"nici"#, r#"niciodata"#, r#"nicăieri"#,
    r#"nimeni"#, r#"nimeri"#, r#"nimic"#, r#"niste"#, r#"nişte"#, r#"noastre"#,
    r#"noastră"#, r#"noi"#, r#"noroc"#, r#"nostri"#, r#"nostru"#, r#"nou"#,
    r#"noua"#, r#"nouă"#, r#"noştri"#, r#"nu"#, r#"numai"#, r#"o"#,
    r#"opt"#, r#"or"#, r#"ori"#, r#"oricare"#, r#"orice"#, r#"oricine"#,
    r#"oricum"#, r#"oricând"#, r#"oricât"#, r#"oricînd"#, r#"oricît"#, r#"oriunde"#,
    r#"p"#, r#"pai"#, r#"parca"#, r#"patra"#, r#"patru"#, r#"patrulea"#,
    r#"pe"#, r#"pentru"#, r#"peste"#, r#"pic"#, r#"pina"#, r#"plus"#,
    r#"poate"#, r#"pot"#, r#"prea"#, r#"prima"#, r#"primul"#, r#"prin"#,
    r#"printr-"#, r#"putini"#, r#"puţin"#, r#"puţina"#, r#"puţină"#, r#"până"#,
    r#"pînă"#, r#"r"#, r#"rog"#, r#"s"#, r#"sa"#, r#"sa-mi"#,
    r#"sa-ti"#, r#"sai"#, r#"sale"#, r#"sau"#, r#"se"#, r#"si"#,
    r#"sint"#, r#"sintem"#, r#"spate"#, r#"spre"#, r#"sub"#, r#"sunt"#,
    r#"suntem"#, r#"sunteţi"#, r#"sus"#, r#"sută"#, r#"sînt"#, r#"sîntem"#,
    r#"sînteţi"#, r#"să"#, r#"săi"#, r#"său"#, r#"t"#, r#"ta"#,
    r#"tale"#, r#"te"#, r#"ti"#, r#"timp"#, r#"tine"#, r#"toata"#,
    r#"toate"#, r#"toată"#, r#"tocmai"#, r#"tot"#, r#"toti"#, r#"totul"#,
    r#"totusi"#, r#"totuşi"#, r#"toţi"#, r#"trei"#, r#"treia"#, r#"treilea"#,
    r#"tu"#, r#"tuturor"#, r#"tăi"#, r#"tău"#, r#"u"#, r#"ul"#,
    r#"ului"#, r#"un"#, r#"una"#, r#"unde"#, r#"undeva"#, r#"unei"#,
    r#"uneia"#, r#"unele"#, r#"uneori"#, r#"unii"#, r#"unor"#, r#"unora"#,
    r#"unu"#, r#"unui"#, r#"unuia"#, r#"unul"#, r#"v"#, r#"va"#,
    r#"vi"#, r#"voastre"#, r#"voastră"#, r#"voi"#, r#"vom"#, r#"vor"#,
    r#"vostru"#, r#"vouă"#, r#"voştri"#, r#"vreme"#, r#"vreo"#, r#"vreun"#,
    r#"vă"#, r#"x"#, r#"z"#, r#"zece"#, r#"zero"#, r#"zi"#,
    r#"zice"#, r#"îi"#, r#"îl"#, r#"îmi"#, r#"împotriva"#, r#"în"#,
    r#"înainte"#, r#"înaintea"#, r#"încotro"#, r#"încât"#, r#"încît"#, r#"între"#,
    r#"întrucât"#, r#"întrucît"#, r#"îţi"#, r#"ăla"#, r#"ălea"#, r#"ăsta"#,
    r#"ăstea"#, r#"ăştia"#, r#"şapte"#, r#"şase"#, r#"şi"#, r#"ştiu"#,
    r#"ţi"#, r#"ţie"#,
];
