//! Stop word lists — VI, YO, ZU.

pub(crate) const VI: &[&str] = &[
    r#"a ha"#, r#"a-lô"#, r#"ai"#, r#"ai ai"#, r#"ai nấy"#, r#"alô"#,
    r#"amen"#, r#"anh"#, r#"bao giờ"#, r#"bao lâu"#, r#"bao nhiêu"#, r#"bao nả"#,
    r#"bay biến"#, r#"biết"#, r#"biết bao"#, r#"biết bao nhiêu"#, r#"biết chừng nào"#, r#"biết mấy"#,
    r#"biết đâu"#, r#"biết đâu chừng"#, r#"biết đâu đấy"#, r#"bà"#, r#"bài"#, r#"bác"#,
    r#"bây bẩy"#, r#"bây chừ"#, r#"bây giờ"#, r#"bây nhiêu"#, r#"bèn"#, r#"béng"#,
    r#"bông"#, r#"bạn"#, r#"bản"#, r#"bất chợt"#, r#"bất cứ"#, r#"bất giác"#,
    r#"bất kì"#, r#"bất kể"#, r#"bất kỳ"#, r#"bất luận"#, r#"bất nhược"#, r#"bất quá"#,
    r#"bất thình lình"#, r#"bất tử"#, r#"bất đồ"#, r#"bấy"#, r#"bấy chầy"#, r#"bấy chừ"#,
    r#"bấy giờ"#, r#"bấy lâu"#, r#"bấy lâu nay"#, r#"bấy nay"#, r#"bấy nhiêu"#, r#"bập bà bập bõm"#,
    r#"bập bõm"#, r#"bắt đầu từ"#, r#"bằng"#, r#"bằng không"#, r#"bằng nấy"#, r#"bằng ấy"#,
    r#"bển"#, r#"bệt"#, r#"bị"#, r#"bỏ mẹ"#, r#"bỗng"#, r#"bỗng chốc"#,
    r#"bỗng dưng"#, r#"bỗng không"#, r#"bỗng nhiên"#, r#"bỗng đâu"#, r#"bộ"#, r#"bội phần"#,
    r#"bớ"#, r#"bởi"#, r#"bởi chưng"#, r#"bởi nhưng"#, r#"bởi thế"#, r#"bởi vì"#,
    r#"bởi vậy"#, r#"bức"#, r#"cao"#, r#"cha"#, r#"cha chả"#, r#"chao ôi"#,
    r#"chiếc"#, r#"cho"#, r#"cho nên"#, r#"cho tới"#, r#"cho tới khi"#, r#"cho đến"#,
    r#"cho đến khi"#, r#"choa"#, r#"chu cha"#, r#"chui cha"#, r#"chung cục"#, r#"chung qui"#,
    r#"chung quy"#, r#"chung quy lại"#, r#"chuyện"#, r#"chành chạnh"#, r#"chí chết"#, r#"chính"#,
    r#"chính là"#, r#"chính thị"#, r#"chùn chùn"#, r#"chùn chũn"#, r#"chú"#, r#"chú mày"#,
    r#"chú mình"#, r#"chúng mình"#, r#"chúng ta"#, r#"chúng tôi"#, r#"chăn chắn"#, r#"chăng"#,
    r#"chưa"#, r#"chầm chập"#, r#"chậc"#, r#"chắc"#, r#"chắc hẳn"#, r#"chẳng lẽ"#,
    r#"chẳng những"#, r#"chẳng nữa"#, r#"chẳng phải"#, r#"chết nỗi"#, r#"chết thật"#, r#"chết tiệt"#,
    r#"chỉ"#, r#"chỉn"#, r#"chốc chốc"#, r#"chớ"#, r#"chớ chi"#, r#"chợt"#,
    r#"chủn"#, r#"chứ"#, r#"chứ lị"#, r#"coi bộ"#, r#"coi mòi"#, r#"con"#,
    r#"cu cậu"#, r#"cuốn"#, r#"cuộc"#, r#"càng"#, r#"các"#, r#"cái"#,
    r#"cây"#, r#"còn"#, r#"có"#, r#"có chăng là"#, r#"có dễ"#, r#"có thể"#,
    r#"có vẻ"#, r#"cóc khô"#, r#"cô"#, r#"cô mình"#, r#"công nhiên"#, r#"cùng"#,
    r#"cùng cực"#, r#"cùng nhau"#, r#"cùng với"#, r#"căn"#, r#"căn cắt"#, r#"cũng"#,
    r#"cũng như"#, r#"cũng vậy"#, r#"cũng vậy thôi"#, r#"cơ"#, r#"cơ chừng"#, r#"cơ hồ"#,
    r#"cơ mà"#, r#"cơn"#, r#"cả"#, r#"cả thảy"#, r#"cả thể"#, r#"cảm ơn"#,
    r#"cần"#, r#"cật lực"#, r#"cật sức"#, r#"cậu"#, r#"cổ lai"#, r#"của"#,
    r#"cứ"#, r#"cứ việc"#, r#"cực lực"#, r#"do"#, r#"do vì"#, r#"do vậy"#,
    r#"do đó"#, r#"duy"#, r#"dào"#, r#"dì"#, r#"dù cho"#, r#"dù rằng"#,
    r#"dưới"#, r#"dạ"#, r#"dần dà"#, r#"dần dần"#, r#"dầu sao"#, r#"dẫu"#,
    r#"dẫu sao"#, r#"dễ sợ"#, r#"dễ thường"#, r#"dở chừng"#, r#"dữ"#, r#"em"#,
    r#"giữa"#, r#"gì"#, r#"hay"#, r#"hoàn toàn"#, r#"hoặc"#, r#"hơn"#,
    r#"hầu hết"#, r#"họ"#, r#"hỏi"#, r#"khi"#, r#"khác"#, r#"không"#,
    r#"luôn"#, r#"là"#, r#"làm"#, r#"lên"#, r#"lúc"#, r#"lại"#,
    r#"lần"#, r#"lớn"#, r#"muốn"#, r#"mà"#, r#"mình"#, r#"mỗi"#,
    r#"một"#, r#"một cách"#, r#"mới"#, r#"mợ"#, r#"ngay"#, r#"ngay cả"#,
    r#"ngay khi"#, r#"ngay lúc"#, r#"ngay lập tức"#, r#"ngay tức khắc"#, r#"ngay từ"#, r#"nghe chừng"#,
    r#"nghe đâu"#, r#"nghen"#, r#"nghiễm nhiên"#, r#"nghỉm"#, r#"ngoài"#, r#"ngoài ra"#,
    r#"ngoải"#, r#"ngày"#, r#"ngày càng"#, r#"ngày ngày"#, r#"ngày xưa"#, r#"ngày xửa"#,
    r#"ngôi"#, r#"ngõ hầu"#, r#"ngăn ngắt"#, r#"ngươi"#, r#"người"#, r#"ngọn"#,
    r#"ngọt"#, r#"ngộ nhỡ"#, r#"nh"#, r#"nhau"#, r#"nhiên hậu"#, r#"nhiều"#,
    r#"nhiệt liệt"#, r#"nhung nhăng"#, r#"nhà"#, r#"nhân dịp"#, r#"nhân tiện"#, r#"nhé"#,
    r#"nhón nhén"#, r#"như"#, r#"như chơi"#, r#"như không"#, r#"như quả"#, r#"như thể"#,
    r#"như tuồng"#, r#"như vậy"#, r#"nhưng"#, r#"nhưng mà"#, r#"nhược bằng"#, r#"nhất"#,
    r#"nhất loạt"#, r#"nhất luật"#, r#"nhất mực"#, r#"nhất nhất"#, r#"nhất quyết"#, r#"nhất sinh"#,
    r#"nhất thiết"#, r#"nhất tâm"#, r#"nhất tề"#, r#"nhất đán"#, r#"nhất định"#, r#"nhận"#,
    r#"nhỉ"#, r#"nhỡ ra"#, r#"những"#, r#"những ai"#, r#"những như"#, r#"nào"#,
    r#"này"#, r#"nên"#, r#"nên chi"#, r#"nó"#, r#"nóc"#, r#"nói"#,
    r#"năm"#, r#"nơi"#, r#"nấy"#, r#"nếu"#, r#"nếu như"#, r#"nền"#,
    r#"nọ"#, r#"nớ"#, r#"nức nở"#, r#"nữa"#, r#"oai oái"#, r#"oái"#,
    r#"pho"#, r#"phè"#, r#"phóc"#, r#"phót"#, r#"phăn phắt"#, r#"phương chi"#,
    r#"phải"#, r#"phải chi"#, r#"phải chăng"#, r#"phắt"#, r#"phỉ phui"#, r#"phỏng"#,
    r#"phỏng như"#, r#"phốc"#, r#"phụt"#, r#"phứt"#, r#"qua"#, r#"qua quít"#,
    r#"qua quýt"#, r#"quyết"#, r#"quyết nhiên"#, r#"quyển"#, r#"quá"#, r#"quá chừng"#,
    r#"quá lắm"#, r#"quá sá"#, r#"quá thể"#, r#"quá trời"#, r#"quá xá"#, r#"quá đỗi"#,
    r#"quá độ"#, r#"quá ư"#, r#"quý hồ"#, r#"quả"#, r#"quả là"#, r#"quả tang"#,
    r#"quả thật"#, r#"quả tình"#, r#"quả vậy"#, r#"quả đúng"#, r#"ra"#, r#"ra phết"#,
    r#"ra sao"#, r#"ra trò"#, r#"ren rén"#, r#"riu ríu"#, r#"riêng"#, r#"riệt"#,
    r#"rày"#, r#"ráo"#, r#"ráo trọi"#, r#"rén"#, r#"rích"#, r#"rón rén"#,
    r#"rút cục"#, r#"răng"#, r#"rất"#, r#"rằng"#, r#"rằng là"#, r#"rốt cuộc"#,
    r#"rốt cục"#, r#"rồi"#, r#"rứa"#, r#"sa sả"#, r#"sao"#, r#"sau"#,
    r#"sau chót"#, r#"sau cuối"#, r#"sau cùng"#, r#"sau đó"#, r#"so"#, r#"song le"#,
    r#"suýt"#, r#"sì"#, r#"sạch"#, r#"sất"#, r#"sắp"#, r#"sẽ"#,
    r#"số"#, r#"số là"#, r#"sốt sột"#, r#"sở dĩ"#, r#"sự"#, r#"tanh"#,
    r#"tha hồ"#, r#"than ôi"#, r#"thanh"#, r#"theo"#, r#"thi thoảng"#, r#"thoạt"#,
    r#"thoạt nhiên"#, r#"thoắt"#, r#"thuần"#, r#"thà"#, r#"thà là"#, r#"thà rằng"#,
    r#"thành ra"#, r#"thành thử"#, r#"thái quá"#, r#"tháng"#, r#"thì"#, r#"thì thôi"#,
    r#"thình lình"#, r#"thím"#, r#"thôi"#, r#"thúng thắng"#, r#"thương ôi"#, r#"thường"#,
    r#"thảo hèn"#, r#"thảo nào"#, r#"thấy"#, r#"thẩy"#, r#"thậm"#, r#"thậm chí"#,
    r#"thật lực"#, r#"thật ra"#, r#"thật vậy"#, r#"thế"#, r#"thế là"#, r#"thế mà"#,
    r#"thế nào"#, r#"thế nên"#, r#"thế ra"#, r#"thế thì"#, r#"thế à"#, r#"thếch"#,
    r#"thỉnh thoảng"#, r#"thỏm"#, r#"thốc"#, r#"thốc tháo"#, r#"thốt"#, r#"thốt nhiên"#,
    r#"thộc"#, r#"thời gian"#, r#"thục mạng"#, r#"thửa"#, r#"thực ra"#, r#"thực sự"#,
    r#"thực vậy"#, r#"tiếp theo"#, r#"tiếp đó"#, r#"tiện thể"#, r#"toà"#, r#"toé khói"#,
    r#"toẹt"#, r#"trong"#, r#"trên"#, r#"trước"#, r#"trước kia"#, r#"trước nay"#,
    r#"trước tiên"#, r#"trước đây"#, r#"trước đó"#, r#"trếu tráo"#, r#"trển"#, r#"trệt"#,
    r#"trệu trạo"#, r#"trỏng"#, r#"trời đất ơi"#, r#"trừ phi"#, r#"tuy"#, r#"tuy nhiên"#,
    r#"tuy rằng"#, r#"tuy thế"#, r#"tuy vậy"#, r#"tuyệt nhiên"#, r#"tuần tự"#, r#"tuốt luốt"#,
    r#"tuốt tuồn tuột"#, r#"tuốt tuột"#, r#"tà tà"#, r#"tênh"#, r#"tít mù"#, r#"tò te"#,
    r#"tôi"#, r#"tông tốc"#, r#"tù tì"#, r#"tăm tắp"#, r#"tại"#, r#"tại vì"#,
    r#"tấm"#, r#"tấn"#, r#"tất cả"#, r#"tất thảy"#, r#"tất tần tật"#, r#"tất tật"#,
    r#"tắp"#, r#"tắp lự"#, r#"tọt"#, r#"tỏ ra"#, r#"tỏ vẻ"#, r#"tốc tả"#,
    r#"tối ư"#, r#"tột"#, r#"tớ"#, r#"tới"#, r#"tức thì"#, r#"tức tốc"#,
    r#"từ"#, r#"từng"#, r#"tự vì"#, r#"tựu trung"#, r#"veo"#, r#"veo veo"#,
    r#"việc"#, r#"vung thiên địa"#, r#"vung tàn tán"#, r#"vung tán tàn"#, r#"và"#, r#"vào"#,
    r#"vâng"#, r#"vèo"#, r#"vì"#, r#"vì chưng"#, r#"vì thế"#, r#"vì vậy"#,
    r#"ví bằng"#, r#"ví dù"#, r#"ví phỏng"#, r#"ví thử"#, r#"vô hình trung"#, r#"vô kể"#,
    r#"vô luận"#, r#"vô vàn"#, r#"văng tê"#, r#"vạn nhất"#, r#"vả chăng"#, r#"vả lại"#,
    r#"vẫn"#, r#"vậy"#, r#"vậy là"#, r#"vậy thì"#, r#"về"#, r#"vị tất"#,
    r#"vốn dĩ"#, r#"với"#, r#"với lại"#, r#"vở"#, r#"vụt"#, r#"vừa"#,
    r#"vừa mới"#, r#"xa xả"#, r#"xiết bao"#, r#"xon xón"#, r#"xoành xoạch"#, r#"xoét"#,
    r#"xoẳn"#, r#"xoẹt"#, r#"xuất kì bất ý"#, r#"xuất kỳ bất ý"#, r#"xuể"#, r#"xuống"#,
    r#"xăm xúi"#, r#"xăm xăm"#, r#"xăm xắm"#, r#"xềnh xệch"#, r#"xệp"#, r#"à"#,
    r#"à ơi"#, r#"ào"#, r#"á"#, r#"á à"#, r#"ái"#, r#"ái chà"#,
    r#"ái dà"#, r#"áng"#, r#"âu là"#, r#"ô hay"#, r#"ô hô"#, r#"ô kê"#,
    r#"ô kìa"#, r#"ôi chao"#, r#"ôi thôi"#, r#"ông"#, r#"úi"#, r#"úi chà"#,
    r#"úi dào"#, r#"ý"#, r#"ý chừng"#, r#"ý da"#, r#"đang"#, r#"đi"#,
    r#"điều"#, r#"đành đạch"#, r#"đáng lí"#, r#"đáng lý"#, r#"đáng lẽ"#, r#"đánh đùng"#,
    r#"đáo để"#, r#"đây"#, r#"đã"#, r#"đó"#, r#"được"#, r#"đại loại"#,
    r#"đại nhân"#, r#"đại phàm"#, r#"đại để"#, r#"đến"#, r#"đến nỗi"#, r#"đều"#,
    r#"để"#, r#"ơ"#, r#"ơ hay"#, r#"ơ kìa"#, r#"ơi"#, r#"ư"#,
    r#"ạ"#, r#"ạ ơi"#, r#"ấy"#, r#"ầu ơ"#, r#"ắt"#, r#"ắt hẳn"#,
    r#"ắt là"#, r#"ối dào"#, r#"ối giời"#, r#"ối giời ơi"#, r#"ồ"#, r#"ổng"#,
    r#"ớ"#, r#"ờ"#, r#"ở"#, r#"ở trên"#, r#"ủa"#, r#"ứ hự"#,
    r#"ứ ừ"#, r#"ừ"#, r#"ử"#,
];

pub(crate) const YO: &[&str] = &[
    r#"a"#, r#"an"#, r#"bá"#, r#"bí"#, r#"bẹ̀rẹ̀"#, r#"fún"#,
    r#"fẹ́"#, r#"gbogbo"#, r#"inú"#, r#"jù"#, r#"jẹ"#, r#"jẹ́"#,
    r#"kan"#, r#"kì"#, r#"kí"#, r#"kò"#, r#"láti"#, r#"lè"#,
    r#"lọ"#, r#"mi"#, r#"mo"#, r#"máa"#, r#"mọ̀"#, r#"ni"#,
    r#"náà"#, r#"ní"#, r#"nígbà"#, r#"nítorí"#, r#"nǹkan"#, r#"o"#,
    r#"padà"#, r#"pé"#, r#"púpọ̀"#, r#"pẹ̀lú"#, r#"rẹ̀"#, r#"sì"#,
    r#"sí"#, r#"sínú"#, r#"ṣ"#, r#"ti"#, r#"tí"#, r#"wà"#,
    r#"wá"#, r#"wọn"#, r#"wọ́n"#, r#"yìí"#, r#"àti"#, r#"àwọn"#,
    r#"é"#, r#"í"#, r#"òun"#, r#"ó"#, r#"ń"#, r#"ńlá"#,
    r#"ṣe"#, r#"ṣé"#, r#"ṣùgbọ́n"#, r#"ẹmọ́"#, r#"ọjọ́"#, r#"ọ̀pọ̀lọpọ̀"#,
];

pub(crate) const ZU: &[&str] = &[
    r#"futhi"#, r#"kahle"#, r#"kakhulu"#, r#"kanye"#, r#"khona"#, r#"kodwa"#,
    r#"kungani"#, r#"kusho"#, r#"la"#, r#"lakhe"#, r#"lapho"#, r#"mina"#,
    r#"ngesikhathi"#, r#"nje"#, r#"phansi"#, r#"phezulu"#, r#"u"#, r#"ukuba"#,
    r#"ukuthi"#, r#"ukuze"#, r#"uma"#, r#"wahamba"#, r#"wakhe"#, r#"wami"#,
    r#"wase"#, r#"wathi"#, r#"yakhe"#, r#"zakhe"#, r#"zonke"#,
];
