#!/usr/bin/env python3
"""A crate count stated in prose is a fact with no owner.

WHY(#4526): several public docs assert how many crates the workspace has. Nothing
derives that number and nothing re-checks it, so it is correct only for as long as
nobody adds a crate -- and when it goes wrong it goes wrong quietly, in exactly the
documents an operator or an agent reads first to orient.

WHY the count is taken from `[workspace] members` and not from the filesystem: this
check was written after a `find crates -name Cargo.toml` count reported 49 against a
true 48 and nearly "corrected" three accurate documents. The extra manifest is
`crates/theatron/proskenion`, which carries its own `Cargo.lock` and is deliberately
NOT a workspace member -- `docs/ARCHITECTURE.md` even says so on the same line as the
number. A count that walks the tree gets that wrong; the members list is the
declaration cargo itself resolves, so it is the one that cannot disagree with cargo.

WHY totality-phrased claims only, and why the rest are REPORTED rather than ignored:
`_llm/recipes.toml` says "Touched 7 crates", which is a true statement about a recipe
and not a claim about the workspace. Flagging it would make this check wrong; silently
skipping it would let a genuine total phrased some new way slip past while the check
still printed green. So unmatched mentions are listed in the output. A reader can then
see what was NOT judged, instead of reading a pass as "every count in the tree agrees."
"""

from __future__ import annotations

import logging
import re
import subprocess
import sys
from pathlib import Path

LOGGER = logging.getLogger("check-doc-inventory")

REPO_ROOT = Path(__file__).resolve().parents[1]

EXIT_CLEAN = 0
EXIT_DRIFT = 1
EXIT_UNVERIFIABLE = 2

# Phrasings that assert the number IS the workspace total. Anything else mentioning a
# crate count is a statement about some subset and is reported, not judged.
TOTALITY = re.compile(
    r"(?:of\s+(\d+)\s+crates"
    r"|(\d+)\s+crates\s+in\s+the\s+workspace"
    r"|workspace\s+with\s+(\d+)\s+crates)",
    re.IGNORECASE,
)

ANY_COUNT = re.compile(r"(\d+)\s+crates", re.IGNORECASE)

DOC_SUFFIXES = {".md", ".toml", ".txt"}

# CHANGELOG.md is generated by release-please from commit subjects. Every crate count in
# it describes what one past PR touched -- "add Prometheus metrics to 7 crates" -- and
# none of them is, or could become, a claim about the current workspace. Ten such lines
# drowned the two real unjudged mentions, which defeats the point of listing them. The
# count of what this skips is printed, so the exclusion is visible rather than silent.
GENERATED_HISTORY = {"CHANGELOG.md"}


class Unverifiable(Exception):
    """The canonical number could not be derived. Never report this as agreement."""


def workspace_member_count(repo_root: Path) -> int:
    """How many crates `[workspace] members` declares.

    # Errors

    Raises when the members list uses a glob, because expanding one correctly means
    resolving it the way cargo does -- and a parser that quietly counted the literal
    entries would undercount without saying so.
    """
    manifest = repo_root / "Cargo.toml"
    try:
        text = manifest.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise Unverifiable(f"cannot read {manifest.name}: {error}") from error

    match = re.search(r"members\s*=\s*\[(.*?)\]", text, re.S)
    if match is None:
        raise Unverifiable("Cargo.toml declares no [workspace] members list")

    entries = [
        line.strip().strip(',').strip('"')
        for line in match.group(1).splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    entries = [entry for entry in entries if entry]
    if not entries:
        raise Unverifiable("[workspace] members is empty")

    globbed = [entry for entry in entries if "*" in entry]
    if globbed:
        raise Unverifiable(
            f"[workspace] members uses glob(s) {globbed}; derive the count with "
            "`cargo metadata --no-deps` instead of parsing this list"
        )
    return len(entries)


def tracked_docs(repo_root: Path) -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True, text=True, check=False, cwd=repo_root,
    )
    if result.returncode != 0:
        raise Unverifiable(f"git ls-files failed: {result.stderr.strip()}")
    return [
        repo_root / line
        for line in result.stdout.splitlines()
        if line and Path(line).suffix in DOC_SUFFIXES and line not in GENERATED_HISTORY
    ]


def claims(paths: list[Path], repo_root: Path) -> tuple[list[tuple[str, int, int, str]], list[str]]:
    """Return (totality claims, other crate-count mentions).

    A totality claim is `(path, lineno, claimed_count, line)`.
    """
    totals: list[tuple[str, int, int, str]] = []
    others: list[str] = []

    for path in paths:
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            continue
        if "crates" not in text:
            continue
        rel = path.relative_to(repo_root).as_posix()
        for lineno, line in enumerate(text.splitlines(), start=1):
            for match in TOTALITY.finditer(line):
                value = next(group for group in match.groups() if group)
                totals.append((rel, lineno, int(value), line.strip()))
            if TOTALITY.search(line) is None:
                for match in ANY_COUNT.finditer(line):
                    others.append(f"  {rel}:{lineno}  {match.group(0)}  |  {line.strip()[:90]}")
    return totals, others


def main() -> int:
    try:
        expected = workspace_member_count(REPO_ROOT)
        totals, others = claims(tracked_docs(REPO_ROOT), REPO_ROOT)
    except Unverifiable as error:
        LOGGER.error("check-doc-inventory: could not establish the canonical count")
        LOGGER.error("  %s", error)
        LOGGER.error("  Nothing was checked. This is NOT a pass.")
        return EXIT_UNVERIFIABLE

    if not totals:
        # WHY this is an error: a check with nothing to compare reports success having
        # verified nothing, which is the same defect in the other direction. If the docs
        # genuinely no longer state a workspace total, delete this check deliberately
        # rather than leaving a green that means nothing.
        LOGGER.error(
            "check-doc-inventory: no document states a workspace crate total, so this "
            "check verified nothing."
        )
        LOGGER.error(
            "  Either a total was reworded out of the phrasings this recognises -- see "
            "TOTALITY in this file -- or the docs stopped making the claim."
        )
        LOGGER.error("  If the latter, remove this check rather than leaving it green.")
        return EXIT_UNVERIFIABLE

    wrong = [claim for claim in totals if claim[2] != expected]

    if wrong:
        LOGGER.error(
            "check-doc-inventory: %d document(s) state a workspace crate total that is "
            "not %d.",
            len(wrong), expected,
        )
        for rel, lineno, value, line in wrong:
            LOGGER.error("  %s:%d  says %d  |  %s", rel, lineno, value, line[:100])
        LOGGER.error("")
        LOGGER.error("`[workspace] members` in Cargo.toml declares %d crates.", expected)
        LOGGER.error("It is the canonical count: `crates/theatron/proskenion` has its own")
        LOGGER.error("Cargo.lock and is NOT a member, so counting Cargo.toml files on disk")
        LOGGER.error("returns one too many and makes correct documents look wrong.")
        return EXIT_DRIFT

    LOGGER.info(
        "check-doc-inventory: %d workspace crate(s); %d document(s) agree",
        expected, len(totals),
    )
    if others:
        # Not a finding. Printed so a green is not read as "every count was checked".
        LOGGER.info(
            "check-doc-inventory: %d crate-count mention(s) not phrased as a workspace "
            "total, so not judged (%s excluded as generated history):",
            len(others), ", ".join(sorted(GENERATED_HISTORY)),
        )
        for line in others:
            LOGGER.info("%s", line)
    return EXIT_CLEAN


if __name__ == "__main__":
    logging.basicConfig(format="%(message)s", level=logging.INFO, stream=sys.stderr)
    raise SystemExit(main())
