#!/usr/bin/env python3
"""Generate and maintain the diaporeia MCP tool inventory in CLAUDE.md.

Parses the live #[tool] methods in crates/diaporeia/src/tools/mod.rs and
rewrites the clearly marked generated block in crates/diaporeia/CLAUDE.md.

Usage:
    python3 scripts/generate-diaporeia-mcp-inventory.py
    python3 scripts/generate-diaporeia-mcp-inventory.py --check

--check exits 0 when the committed docs match the generated inventory and
non-zero with a clear instruction to regenerate.
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_PATH = REPO_ROOT / "crates" / "diaporeia" / "src" / "tools" / "mod.rs"
CLAUDE_PATH = REPO_ROOT / "crates" / "diaporeia" / "CLAUDE.md"

BEGIN_MARKER = "<!-- BEGIN MCP INVENTORY -- generated by scripts/generate-diaporeia-mcp-inventory.py -->"
END_MARKER = "<!-- END MCP INVENTORY -->"

# WHY: These are the concrete state-changing calls observed in the tool
# implementations. A tool is classified as mutating when its body contains any
# of these signatures. The heuristic is explicit, deterministic, and validated
# by the unit tests in this script.
MUTATION_SIGNATURES = [
    "find_or_create_session",
    "send_turn_streaming",
    "insert_fact_async",
    "forget_fact",
    "vault.store(",
    "vault.remove(",
    "store.add_note(",
    "store.delete_note(",
    "store.write(",
    "store.delete(",
]

TOOL_RE = re.compile(
    r"#\[tool\s*\((?P<attr>.*?)\)\]\s*async\s+fn\s+(?P<name>[a-z_][a-z0-9_]*)\s*\(",
    re.DOTALL,
)
DESCRIPTION_RE = re.compile(
    r'description\s*=\s*(?P<value>(?:"(?:\\.|[^"\\])*"\s*)+)',
    re.DOTALL,
)
STRING_LITERAL_RE = re.compile(r'"(?:\\.|[^"\\])*"', re.DOTALL)
TIER_RE = re.compile(r"self\.rate_limiter\.check\(Tier::(?P<tier>\w+)\)")
ROLE_RE = re.compile(r"require_role\s*\(\s*self\s*,\s*&context\s*,\s*Role::(?P<role>\w+)")


def _find_tool_spans(source: str) -> list[tuple[str, str, int, int]]:
    """Return (name, attr, body_start, body_end) for each #[tool] method."""
    spans = []
    for match in TOOL_RE.finditer(source):
        name = match.group("name")
        attr = match.group("attr")
        body_start = source.find("{", match.end())
        if body_start == -1:
            raise RuntimeError(f"could not find body start for tool {name}")
        depth = 1
        pos = body_start + 1
        while pos < len(source) and depth > 0:
            if source[pos] == "{":
                depth += 1
            elif source[pos] == "}":
                depth -= 1
            pos += 1
        if depth != 0:
            raise RuntimeError(f"unbalanced braces in tool {name}")
        spans.append((name, attr, body_start, pos))
    return spans


def _decode_rust_string_literal(literal: str) -> str:
    body = literal[1:-1]
    body = re.sub(r"\\\s*\n\s*", " ", body)
    return ast.literal_eval(f'"{body}"')


def _extract_description(attr: str, name: str) -> str:
    match = DESCRIPTION_RE.search(attr)
    if match is None:
        raise RuntimeError(f"could not determine description for {name}")
    parts = STRING_LITERAL_RE.findall(match.group("value"))
    description = " ".join(_decode_rust_string_literal(part) for part in parts)
    description = re.sub(r"\s+", " ", description).strip()
    return _escape_table_cell(description)


def _escape_table_cell(value: str) -> str:
    return value.replace("|", r"\|")


def _extract_tool(source: str, name: str, attr: str, body_start: int, body_end: int) -> dict:
    body = source[body_start:body_end]

    tier_match = TIER_RE.search(body)
    if tier_match is None:
        raise RuntimeError(f"could not determine rate-limit tier for {name}")
    tier = tier_match.group("tier")

    role_match = ROLE_RE.search(body)
    if role_match is None:
        raise RuntimeError(f"could not determine required role for {name}")
    role = role_match.group("role")

    mutates = any(sig in body for sig in MUTATION_SIGNATURES)

    return {
        "name": name,
        "tier": tier,
        "role": role,
        "mutates": "Yes" if mutates else "No",
        "purpose": _extract_description(attr, name),
    }


def _format_inventory(tools: list[dict]) -> str:
    lines = [
        f"## MCP tools ({len(tools)})",
        "",
        "| Tool | Tier | RBAC | Mutates | Purpose |",
        "|------|------|------|---------|---------|",
    ]
    for tool in sorted(tools, key=lambda t: t["name"]):
        lines.append(
            f"| `{tool['name']}` | {tool['tier']} | {tool['role']} | {tool['mutates']} | {tool['purpose']} |"
        )
    return "\n".join(lines)


def parse_tools(source: str) -> list[dict]:
    """Parse the source and return the list of tool metadata dicts."""
    spans = _find_tool_spans(source)
    return [_extract_tool(source, name, attr, start, end) for name, attr, start, end in spans]


def generate_block(source: str) -> str:
    """Return the full generated markdown block for CLAUDE.md."""
    tools = parse_tools(source)
    inventory = _format_inventory(tools)
    return (
        f"{BEGIN_MARKER}\n"
        f"{inventory}\n"
        f"\n"
        f"Knowledge graph tools require `mcp.knowledge_graph.enabled = true` in config (default `false`).\n"
        f"{END_MARKER}"
    )


def read_claude() -> str:
    return CLAUDE_PATH.read_text(encoding="utf-8")


def write_claude(content: str) -> None:
    CLAUDE_PATH.write_text(content, encoding="utf-8")


def replace_inventory(claude: str, generated: str) -> str:
    begin = claude.find(BEGIN_MARKER)
    end = claude.find(END_MARKER)
    if begin == -1 or end == -1:
        raise RuntimeError(
            f"could not find inventory markers in {CLAUDE_PATH}; "
            "ensure the file contains the generated-block anchors"
        )
    end += len(END_MARKER)
    return claude[:begin] + generated + claude[end:]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify the diaporeia MCP tool inventory."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed docs differ from the generated inventory",
    )
    args = parser.parse_args()

    source = TOOLS_PATH.read_text(encoding="utf-8")
    generated = generate_block(source)

    if args.check:
        claude = read_claude()
        begin = claude.find(BEGIN_MARKER)
        end = claude.find(END_MARKER)
        if begin == -1 or end == -1:
            print(
                "ERROR: generated-block markers missing from CLAUDE.md; "
                "run the generator to recreate them",
                file=sys.stderr,
            )
            return 1
        end += len(END_MARKER)
        actual = claude[begin:end]
        if actual != generated:
            print(
                "ERROR: diaporeia MCP tool inventory is out of date.\n"
                "Run the generator to update the docs:\n"
                "  python3 scripts/generate-diaporeia-mcp-inventory.py",
                file=sys.stderr,
            )
            return 1
        print("OK: diaporeia MCP tool inventory is up to date")
        return 0

    claude = read_claude()
    updated = replace_inventory(claude, generated)
    write_claude(updated)
    print(f"Updated {CLAUDE_PATH} with {len(parse_tools(source))} MCP tools")
    return 0


if __name__ == "__main__":
    sys.exit(main())
