#!/usr/bin/env python3
"""Generate and verify the field reference in docs/CONFIGURATION.md from the
`AletheiaConfig` schema in `crates/taxis/src/config/`.

`AletheiaConfig` (crates/taxis/src/config/mod.rs) is the SSOT for the TOML
config surface: every section, field, type, default, and `#[serde(...)]`
rename/alias lives there as compiled, type-checked source. This generator
walks that struct tree (following nested config structs, `Vec<Struct>`,
`HashMap<String, Struct>`, and cross-crate config types such as
`eidos::training::TrainingConfig`) and renders a field-reference table for
every section into the generated block of docs/CONFIGURATION.md, replacing
the prior hand-maintained tables that had drifted ~11 ways from the schema
(aletheia#5774).

Defaults are read from each struct's `impl Default` block (or, absent one,
derived from `#[derive(Default)]` primitive semantics and each enum's
`#[default]` variant). A default expression that is a local same-file
constant, or a single-hop cross-crate `path::CONST` / `path::Type::default()`
field access, is resolved to its literal value; anything not resolvable in a
bounded number of hops is rendered as the literal Rust expression rather than
guessed, so the doc never states a fabricated number.

Usage:
    python3 scripts/generate-configuration-doc.py
    python3 scripts/generate-configuration-doc.py --check

--check exits 0 when the committed doc's generated block matches freshly
generated output and non-zero with a clear instruction to regenerate.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO_ROOT / "crates" / "taxis" / "src" / "config"
DOC_PATH = REPO_ROOT / "docs" / "CONFIGURATION.md"
ROOT_TYPE = "AletheiaConfig"
ROOT_FILE = CONFIG_DIR / "mod.rs"

BEGIN_MARKER = (
    "<!-- BEGIN GENERATED CONFIG REFERENCE -- "
    "generated by scripts/generate-configuration-doc.py -->"
)
END_MARKER = "<!-- END GENERATED CONFIG REFERENCE -->"

# WHY: directories under crates/*/src holding non-schema code (build scripts,
# generated protobuf, etc.) that would otherwise cost time to scan and can
# never define a config struct. Kept short and structural, not a denylist of
# specific crates.
SEARCH_EXCLUDE_DIR_NAMES = {"target", "tests", "fuzz"}

# WHY: types with a custom (de)serialize wire form that a mechanical
# struct/enum reader would misrender if it either recursed into private
# fields never present in the wire format (SecretString) or fabricated a
# derived string it cannot verify (types with no rename_all to derive from).
# Each entry is the friendly Type-column label; never a guessed default.
OPAQUE_TYPE_LABELS: dict[str, str] = {
    "SecretString": "secret string",
    "PathBuf": "path",
    "Path": "path",
    "String": "string",
    "str": "string",
    "bool": "bool",
    "u8": "integer",
    "u16": "integer",
    "u32": "integer",
    "u64": "integer",
    "u128": "integer",
    "usize": "integer",
    "i8": "integer",
    "i16": "integer",
    "i32": "integer",
    "i64": "integer",
    "i128": "integer",
    "isize": "integer",
    "f32": "float",
    "f64": "float",
    "Timestamp": "timestamp",
}

PRIMITIVE_DEFAULTS: dict[str, str] = {
    "bool": "false",
    "u8": "0",
    "u16": "0",
    "u32": "0",
    "u64": "0",
    "u128": "0",
    "usize": "0",
    "i8": "0",
    "i16": "0",
    "i32": "0",
    "i64": "0",
    "i128": "0",
    "isize": "0",
    "f32": "0.0",
    "f64": "0.0",
    "String": '""',
    "str": '""',
}

MAX_RESOLVE_DEPTH = 8


# ── generic Rust-source utilities ──────────────────────────────────────────


def normalize_attrs(text: str) -> str:
    """Collapse every `#[...]` attribute (bracket-matched, so a value string
    containing `]` cannot truncate early) onto one physical line.

    WHY: several struct/field attributes in this schema span multiple source
    lines (`#[expect(\\n    clippy::x,\\n    reason = "...",\\n)]`). Every
    downstream parser here works line-by-line; collapsing first means "is
    this line an attribute" never has to reason about being mid-attribute.
    """
    out: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        if text[i] == "#" and i + 1 < n and text[i + 1] == "[":
            start = i
            depth = 0
            j = i + 1
            while j < n:
                if text[j] == "[":
                    depth += 1
                elif text[j] == "]":
                    depth -= 1
                    if depth == 0:
                        j += 1
                        break
                j += 1
            collapsed = re.sub(r"\s*\n\s*", " ", text[start:j])
            out.append(collapsed)
            i = j
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def strip_trailing_comments(text: str) -> str:
    """Remove `//...` line comments, preserving `///` doc and `//!` module
    doc lines verbatim and never touching `//` inside a string literal
    (e.g. a `"https://..."` default value)."""
    out_lines = []
    for line in text.split("\n"):
        if re.match(r"^\s*(///|//!)", line):
            out_lines.append(line)
            continue
        in_string = False
        cut = None
        i = 0
        n = len(line)
        while i < n:
            c = line[i]
            if in_string:
                if c == "\\":
                    i += 2
                    continue
                if c == '"':
                    in_string = False
            else:
                if c == '"':
                    in_string = True
                elif c == "/" and i + 1 < n and line[i + 1] == "/":
                    cut = i
                    break
            i += 1
        out_lines.append(line[:cut].rstrip() if cut is not None else line)
    return "\n".join(out_lines)


BRACKET_OPEN = "([{<"
BRACKET_CLOSE = ")]}>"


def split_top_level(text: str, sep: str = ",") -> list[str]:
    """Split on `sep` at bracket-depth 0, tracking `(){}[]<>` together (Rust
    generics reuse `<>` for both comparisons and type params, but within a
    struct-field or struct-literal list only the type-param usage appears).

    WHY doc-comment lines are copied verbatim, uninspected: `///` prose is
    natural-language text, not Rust syntax -- it routinely contains commas
    ("actor/manager health, restart, GC, ...") and unbalanced-looking
    brackets/angle-brackets (`` `Vec<T>` ``, `[text]`) that are not struct
    delimiters. Depth-tracking or comma-splitting inside a doc-comment line
    corrupts every subsequent field split in the same struct body.
    """
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    in_string = False
    i = 0
    n = len(text)
    while i < n:
        if i == 0 or text[i - 1] == "\n":
            line_end = text.find("\n", i)
            end = line_end if line_end != -1 else n
            line = text[i:end]
            if re.match(r"^\s*(///|//!)", line):
                current.append(line)
                if line_end != -1:
                    current.append("\n")
                    i = line_end + 1
                else:
                    i = n
                continue
        c = text[i]
        if in_string:
            current.append(c)
            if c == "\\":
                i += 1
                if i < n:
                    current.append(text[i])
            elif c == '"':
                in_string = False
            i += 1
            continue
        if c == '"':
            in_string = True
            current.append(c)
        elif c in BRACKET_OPEN:
            depth += 1
            current.append(c)
        elif c in BRACKET_CLOSE:
            depth -= 1
            current.append(c)
        elif c == sep and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(c)
        i += 1
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return [p for p in (p.strip() for p in parts) if p]


def find_matching_brace(text: str, open_pos: int) -> int:
    """Given the index of an opening `{`, return the index just past its
    matching `}`."""
    assert text[open_pos] == "{"
    depth = 0
    i = open_pos
    n = len(text)
    while i < n:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced braces")


def preceding_doc_and_attrs(text: str, match_start: int) -> tuple[str, list[str]]:
    """Collect the contiguous `///` / `#[...]` lines directly above
    `match_start`. Returns (doc_text, attr_lines) in source order."""
    line_start = text.rfind("\n", 0, match_start) + 1
    lines_before = text[:line_start].splitlines()
    collected: list[str] = []
    for line in reversed(lines_before):
        stripped = line.strip()
        if stripped.startswith("///") or re.match(r"^#\[.*\]$", stripped):
            collected.append(line)
        elif stripped == "":
            break
        else:
            break
    collected.reverse()
    doc_lines = [l.strip()[3:].strip() for l in collected if l.strip().startswith("///")]
    attr_lines = [l.strip() for l in collected if re.match(r"^#\[.*\]$", l.strip())]
    doc = " ".join(x for x in doc_lines if x)
    doc = re.sub(r"\s+", " ", doc).strip()
    return doc, attr_lines


def extract_rename_all(attr_lines: list[str]) -> str | None:
    for a in attr_lines:
        m = re.search(r'rename_all\s*=\s*"([^"]+)"', a)
        if m:
            return m.group(1)
    return None


def has_default_derive_or_impl(attr_lines: list[str]) -> bool:
    for a in attr_lines:
        m = re.search(r"derive\((.*)\)", a)
        if m and re.search(r"\bDefault\b", m.group(1)):
            return True
    return False


def has_serde_derive(attr_lines: list[str]) -> bool:
    for a in attr_lines:
        m = re.search(r"derive\((.*)\)", a)
        if m and re.search(r"\bDeserialize\b", m.group(1)):
            return True
    return False


# ── repo-wide file cache + type location ────────────────────────────────────

_FILE_CACHE: dict[Path, str] = {}


def read_file(path: Path) -> str:
    if path not in _FILE_CACHE:
        raw = path.read_text(encoding="utf-8")
        _FILE_CACHE[path] = normalize_attrs(strip_trailing_comments(raw))
    return _FILE_CACHE[path]


_CONFIG_FILES: list[Path] | None = None


def config_files() -> list[Path]:
    global _CONFIG_FILES
    if _CONFIG_FILES is None:
        files = sorted(CONFIG_DIR.rglob("*.rs"))
        _CONFIG_FILES = [
            f
            for f in files
            if "config_tests" not in f.parts and not f.name.endswith("_tests.rs")
        ]
    return _CONFIG_FILES


_TYPE_FILE_CACHE: dict[str, Path | None] = {}


_REPO_TYPE_INDEX: dict[tuple[str, str], Path] | None = None
_REPO_ALIAS_INDEX: dict[str, str] | None = None
_REPO_ITEM_RE = re.compile(r"^\s*pub\s+(struct|enum)\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.MULTILINE)
# WHY a separate regex rather than folding `type` into `_REPO_ITEM_RE`'s
# alternation: a `pub type X = Y;` item names its OWN identifier (X) but
# defines no fields of its own -- resolving it means following to Y, not
# indexing X as a definition site the way struct/enum are.
_REPO_ALIAS_RE = re.compile(
    r"^\s*pub\s+type\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([A-Za-z_][A-Za-z0-9_:]*)", re.MULTILINE
)


def build_repo_type_index() -> dict[tuple[str, str], Path]:
    """One-time repo-wide (struct|enum) name -> defining-file index, built
    from a single pass over raw file text (no normalize/comment-strip --
    that cost is paid lazily, only for files actually selected for parsing).
    The same pass also populates `_REPO_ALIAS_INDEX` (see
    `build_repo_alias_index`), so a name that collides across both a
    struct/enum decl and a `pub type` alias elsewhere in the repo pays the
    walk only once total.

    WHY: `locate_type_file`'s fallback exists for cross-crate config types
    (e.g. `eidos::training::TrainingConfig`), but several fields also
    reference genuinely opaque leaf types (`FactId`, `MemoryScope`, ...)
    that resolve to NOTHING in this repo's struct/enum surface. A naive
    per-unresolved-name repo scan pays a ~1900-file, ~30MB walk once per
    such name; this index pays it once total.
    """
    global _REPO_TYPE_INDEX, _REPO_ALIAS_INDEX
    if _REPO_TYPE_INDEX is not None and _REPO_ALIAS_INDEX is not None:
        return _REPO_TYPE_INDEX
    index: dict[tuple[str, str], Path] = {}
    alias_index: dict[str, str] = {}
    for f in sorted(REPO_ROOT.glob("crates/*/src/**/*.rs")):
        if any(part in SEARCH_EXCLUDE_DIR_NAMES for part in f.parts):
            continue
        if f.name.endswith("_tests.rs") or "tests" in f.parts:
            continue
        try:
            raw = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for m in _REPO_ITEM_RE.finditer(raw):
            index.setdefault((m.group(1), m.group(2)), f)
        for m in _REPO_ALIAS_RE.finditer(raw):
            alias_index.setdefault(m.group(1), m.group(2))
    _REPO_TYPE_INDEX = index
    _REPO_ALIAS_INDEX = alias_index
    return index


def build_repo_alias_index() -> dict[str, str]:
    """One-time repo-wide `pub type NAME = path::to::Target;` name -> target
    path index. Shares `build_repo_type_index`'s single file walk."""
    build_repo_type_index()
    assert _REPO_ALIAS_INDEX is not None
    return _REPO_ALIAS_INDEX


_TYPE_FILE_LOCAL_CACHE: dict[str, Path | None] = {}


def locate_type_file_local(type_name: str, item_kind: str) -> Path | None:
    """Search only the crate's own config module tree (`config_files()`) for
    `pub ITEM_KIND TYPE_NAME`, never falling back to the repo-wide name
    index. Split out from `locate_type_file` so callers that need to know
    "is this genuinely declared where AletheiaConfig's own tree lives"
    (as opposed to merely findable somewhere in the repo) can ask that
    question directly -- `parse_type` uses it to give a local `pub type`
    alias priority over a same-named struct/enum that merely happens to
    exist elsewhere."""
    cache_key = f"{item_kind}:{type_name}"
    if cache_key in _TYPE_FILE_LOCAL_CACHE:
        return _TYPE_FILE_LOCAL_CACHE[cache_key]
    pattern = re.compile(rf"^\s*pub\s+{item_kind}\s+{re.escape(type_name)}\b", re.MULTILINE)
    for f in config_files():
        if pattern.search(read_file(f)):
            _TYPE_FILE_LOCAL_CACHE[cache_key] = f
            return f
    _TYPE_FILE_LOCAL_CACHE[cache_key] = None
    return None


def locate_type_file(type_name: str, item_kind: str = r"(?:struct|enum)") -> Path | None:
    """Find the file defining `pub struct/enum TYPE_NAME`. Searches the taxis
    config module tree first (the common case, and stable under refactors of
    other crates), then falls back to the repo-wide index for cross-crate
    config types (e.g. `eidos::training::TrainingConfig`)."""
    cache_key = f"{item_kind}:{type_name}"
    if cache_key in _TYPE_FILE_CACHE:
        return _TYPE_FILE_CACHE[cache_key]
    local = locate_type_file_local(type_name, item_kind)
    if local is not None:
        _TYPE_FILE_CACHE[cache_key] = local
        return local
    index = build_repo_type_index()
    kinds = ("struct", "enum") if item_kind == r"(?:struct|enum)" else (item_kind,)
    for k in kinds:
        f = index.get((k, type_name))
        if f is not None:
            _TYPE_FILE_CACHE[cache_key] = f
            return f
    _TYPE_FILE_CACHE[cache_key] = None
    return None


_TYPE_ALIAS_CACHE: dict[str, str | None] = {}


def locate_type_alias(type_name: str, *, local_only: bool = False) -> str | None:
    """Find a `pub type TYPE_NAME = path::to::Target;` alias and return its
    target path text (e.g. `koina::models::ModelPrice`). Searches the taxis
    config module tree first, then (unless `local_only`) falls back to the
    repo-wide alias index.

    WHY this is a step distinct from `locate_type_file`: a `pub type X =
    Y;` item defines neither a struct nor an enum, so it is invisible to
    both the local struct/enum search and the repo-wide struct/enum index.
    Left unresolved, it silently degrades to that index's bare-name
    fallback, which returns the first SAME-NAMED struct/enum anywhere in
    the repo -- and when one exists by coincidence (a `ModelPricing` DTO in
    a REST-handler crate, unrelated to the taxis config alias of the same
    name), the fallback renders that unrelated type's fields, with that
    type's own field docs (or lack of them), instead of the aliased type.
    """
    cache_key = f"{'local:' if local_only else ''}{type_name}"
    if cache_key in _TYPE_ALIAS_CACHE:
        return _TYPE_ALIAS_CACHE[cache_key]
    pattern = re.compile(
        rf"^\s*pub\s+type\s+{re.escape(type_name)}\s*=\s*([A-Za-z_][A-Za-z0-9_:]*)", re.MULTILINE
    )
    for f in config_files():
        m = pattern.search(read_file(f))
        if m:
            _TYPE_ALIAS_CACHE[cache_key] = m.group(1)
            return m.group(1)
    if local_only:
        _TYPE_ALIAS_CACHE[cache_key] = None
        return None
    target = build_repo_alias_index().get(type_name)
    _TYPE_ALIAS_CACHE[cache_key] = target
    return target


def locate_const_file(crate: str, const_name: str) -> Path | None:
    cache_key = f"const:{crate}:{const_name}"
    if cache_key in _TYPE_FILE_CACHE:
        return _TYPE_FILE_CACHE[cache_key]
    pattern = re.compile(
        rf"^\s*pub(?:\(crate\))?\s+const\s+{re.escape(const_name)}\s*:", re.MULTILINE
    )
    crate_dir = REPO_ROOT / "crates" / crate / "src"
    result = None
    if crate_dir.is_dir():
        for f in sorted(crate_dir.rglob("*.rs")):
            if f.name.endswith("_tests.rs") or "tests" in f.parts:
                continue
            if pattern.search(read_file(f)):
                result = f
                break
    _TYPE_FILE_CACHE[cache_key] = result
    return result


# ── data model ───────────────────────────────────────────────────────────


@dataclass
class FieldDef:
    name: str
    ty: str
    doc: str
    rename: str | None
    aliases: list[str]
    flatten: bool
    skip: bool
    default_fn: str | None = None
    has_bare_default: bool = False


@dataclass
class VariantDef:
    name: str
    doc: str
    rename: str | None
    aliases: list[str]
    is_default: bool
    payload_kind: str  # "unit" | "tuple" | "struct"
    payload_fields: list[FieldDef] = field(default_factory=list)
    payload_type: str | None = None


@dataclass
class StructDef:
    kind: str  # "struct"
    name: str
    doc: str
    rename_all: str | None
    fields: list[FieldDef]
    defaults: dict[str, str]  # field name -> raw default expr text
    has_impl_default: bool
    has_derive_default: bool
    source_file: Path


@dataclass
class EnumDef:
    kind: str  # "enum"
    name: str
    doc: str
    rename_all: str | None
    variants: list[VariantDef]
    has_serde: bool
    source_file: Path


_TYPE_CACHE: dict[str, StructDef | EnumDef | None] = {}


def parse_field_chunk(chunk: str) -> FieldDef | None:
    lines = [l for l in chunk.split("\n")]
    doc_lines: list[str] = []
    attr_lines: list[str] = []
    decl_lines: list[str] = []
    for line in lines:
        s = line.strip()
        if not s:
            continue
        if s.startswith("///"):
            doc_lines.append(s[3:].strip())
        elif re.match(r"^#\[.*\]$", s):
            attr_lines.append(s)
        else:
            decl_lines.append(s)
    decl = " ".join(decl_lines).strip()
    # WHY `pub` is optional: this parser also handles enum struct-payload
    # variant fields (e.g. `Bearer { token: SecretString }`), which are
    # never `pub` in Rust -- only plain struct fields carry the keyword.
    m = re.match(r"^(?:pub\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+)$", decl)
    if not m:
        return None
    name, ty = m.group(1), m.group(2).strip()
    doc = re.sub(r"\s+", " ", " ".join(doc_lines)).strip()
    attrs_text = " ".join(attr_lines)
    rename_m = re.search(r'\bserde\([^)]*?\brename\s*=\s*"([^"]+)"', attrs_text)
    rename = rename_m.group(1) if rename_m else None
    aliases = re.findall(r'alias\s*=\s*"([^"]+)"', attrs_text)
    flatten = bool(re.search(r"\bflatten\b", attrs_text))
    skip = bool(re.search(r"\bserde\([^)]*\bskip\b(?!_serializing_if)", attrs_text))
    default_fn_m = re.search(r'\bdefault\s*=\s*"([^"]+)"', attrs_text)
    default_fn = default_fn_m.group(1) if default_fn_m else None
    has_bare_default = default_fn is None and bool(re.search(r"\bdefault\b(?!\s*=)", attrs_text))
    return FieldDef(
        name=name,
        ty=ty,
        doc=doc,
        rename=rename,
        aliases=aliases,
        flatten=flatten,
        skip=skip,
        default_fn=default_fn,
        has_bare_default=has_bare_default,
    )


def parse_fields_from_body(body: str) -> list[FieldDef]:
    inner = body[1:-1]  # strip outer { }
    fields: list[FieldDef] = []
    for chunk in split_top_level(inner, ","):
        fd = parse_field_chunk(chunk)
        if fd is not None:
            fields.append(fd)
    return fields


def parse_defaults_from_impl(text: str, struct_name: str) -> tuple[dict[str, str], dict[str, str]]:
    """Find `impl Default for STRUCT_NAME { fn default() -> Self { ... } }`
    and return (field -> default expr text, let-binding name -> rhs expr)."""
    m = re.search(
        rf"impl\s+Default\s+for\s+{re.escape(struct_name)}\s*\{{", text
    )
    if not m:
        return {}, {}
    body_end = find_matching_brace(text, text.index("{", m.end() - 1))
    impl_body = text[m.end() - 1 : body_end]
    fn_m = re.search(r"fn\s+default\s*\(\s*\)\s*->\s*Self\s*\{", impl_body)
    if not fn_m:
        return {}, {}
    fn_body_start = impl_body.index("{", fn_m.end() - 1)
    fn_body_end = find_matching_brace(impl_body, fn_body_start)
    fn_body = impl_body[fn_body_start + 1 : fn_body_end - 1]

    locals_map: dict[str, str] = {}
    use_aliases: dict[str, str] = {}
    self_m = re.search(r"Self\s*\{", fn_body)
    prelude = fn_body[: self_m.start()] if self_m else fn_body
    for use_m in re.finditer(r"use\s+([\w:]+)\s+as\s+(\w+)\s*;", prelude):
        use_aliases[use_m.group(2)] = use_m.group(1)
    for let_m in re.finditer(r"let\s+(?:mut\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?);", prelude, re.DOTALL):
        locals_map[let_m.group(1)] = re.sub(r"\s+", " ", let_m.group(2)).strip()

    def apply_use_aliases(expr: str) -> str:
        for alias, path in use_aliases.items():
            expr = re.sub(rf"(?<![A-Za-z0-9_]){re.escape(alias)}::", f"{path}::", expr)
        return expr

    if not self_m:
        return {}, locals_map
    struct_lit_start = self_m.end() - 1
    struct_lit_end = find_matching_brace(fn_body, struct_lit_start)
    inner = fn_body[struct_lit_start + 1 : struct_lit_end - 1]

    defaults: dict[str, str] = {}
    for chunk in split_top_level(inner, ","):
        km = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+)$", chunk.strip(), re.DOTALL)
        if km:
            defaults[km.group(1)] = apply_use_aliases(re.sub(r"\s+", " ", km.group(2)).strip())
        else:
            shorthand = chunk.strip()
            if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", shorthand):
                defaults[shorthand] = shorthand
    return defaults, locals_map


_LOCALS_CACHE: dict[str, dict[str, str]] = {}


def parse_struct_literal(expr: str) -> tuple[str | None, dict[str, str]] | None:
    """Parse a bare `TypeName { field: expr, ... }` struct-literal expression
    (as opposed to `TypeName::default()`) into (TypeName-or-None-if-elided,
    {field: expr})."""
    m = re.match(r"^(?:([A-Za-z_][A-Za-z0-9_:]*)\s*)?\{(.*)\}$", expr.strip(), re.DOTALL)
    if not m:
        return None
    fields: dict[str, str] = {}
    for chunk in split_top_level(m.group(2), ","):
        km = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+)$", chunk.strip(), re.DOTALL)
        if km:
            fields[km.group(1)] = re.sub(r"\s+", " ", km.group(2)).strip()
    return m.group(1), fields


def parse_local_consts(text: str) -> dict[str, str]:
    consts: dict[str, str] = {}
    for m in re.finditer(
        r"^\s*(?:pub(?:\(crate\))?\s+)?const\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*[^=]+=\s*(.+?);",
        text,
        re.MULTILINE | re.DOTALL,
    ):
        consts[m.group(1)] = re.sub(r"\s+", " ", m.group(2)).strip()
    return consts


def parse_type(name: str) -> StructDef | EnumDef | None:
    if name in _TYPE_CACHE:
        return _TYPE_CACHE[name]
    _TYPE_CACHE[name] = None  # cycle guard placeholder

    # INVARIANT: a local `pub type NAME = path::Target;` alias, when present,
    # is definitive -- it is how THIS crate's own compiler resolves NAME, not
    # a guess -- so it is tried before the repo-wide struct/enum name index
    # below, which is a last-resort bare-name fallback that a same-named
    # struct/enum living in an unrelated crate can satisfy incorrectly (a
    # `ModelPricing` alias to `koina::models::ModelPrice`, resolved instead
    # to an unrelated `ModelPricing` DTO struct in a REST-handler crate).
    if locate_type_file_local(name, "struct") is None and locate_type_file_local(name, "enum") is None:
        alias_target = locate_type_alias(name, local_only=True)
        if alias_target is not None:
            target_name = alias_target.rsplit("::", 1)[-1]
            if target_name and target_name != name:
                resolved = parse_type(target_name)
                _TYPE_CACHE[name] = resolved
                return resolved

    struct_file = locate_type_file(name, "struct")
    enum_file = locate_type_file(name, "enum")

    # A name absent locally AND absent from the repo-wide struct/enum index
    # may still be a `pub type` alias declared elsewhere in the repo. Tried
    # last, after the repo-wide struct/enum index, so it can never outrank a
    # genuine same-named struct/enum found there.
    if struct_file is None and enum_file is None:
        alias_target = locate_type_alias(name)
        if alias_target is not None:
            target_name = alias_target.rsplit("::", 1)[-1]
            if target_name and target_name != name:
                resolved = parse_type(target_name)
                _TYPE_CACHE[name] = resolved
                return resolved

    if struct_file is not None:
        text = read_file(struct_file)
        m = re.search(rf"^(\s*)pub\s+struct\s+{re.escape(name)}\b", text, re.MULTILINE)
        assert m
        doc, attrs = preceding_doc_and_attrs(text, m.start())
        after = text[m.end() :]
        brace_rel = after.index("{")
        # tuple/unit struct (no `{ ... }` body) -> not a config table; opaque.
        semi_rel = after.find(";")
        if semi_rel != -1 and (brace_rel == -1 or semi_rel < brace_rel):
            _TYPE_CACHE[name] = None
            return None
        body_start = m.end() + brace_rel
        body_end = find_matching_brace(text, body_start)
        body = text[body_start:body_end]
        fields = parse_fields_from_body(body)
        defaults, _locals = parse_defaults_from_impl(text, name)
        result = StructDef(
            kind="struct",
            name=name,
            doc=doc,
            rename_all=extract_rename_all(attrs),
            fields=fields,
            defaults=defaults,
            has_impl_default=bool(defaults) or bool(re.search(rf"impl\s+Default\s+for\s+{re.escape(name)}\s*\{{", text)),
            has_derive_default=has_default_derive_or_impl(attrs),
            source_file=struct_file,
        )
        _TYPE_CACHE[name] = result
        return result

    if enum_file is not None:
        text = read_file(enum_file)
        m = re.search(rf"^(\s*)pub\s+enum\s+{re.escape(name)}\b", text, re.MULTILINE)
        assert m
        doc, attrs = preceding_doc_and_attrs(text, m.start())
        after = text[m.end() :]
        body_start = m.end() + after.index("{")
        body_end = find_matching_brace(text, body_start)
        body = text[body_start:body_end]
        variants = parse_enum_variants(body)
        result = EnumDef(
            kind="enum",
            name=name,
            doc=doc,
            rename_all=extract_rename_all(attrs),
            variants=variants,
            has_serde=has_serde_derive(attrs),
            source_file=enum_file,
        )
        _TYPE_CACHE[name] = result
        return result

    _TYPE_CACHE[name] = None
    return None


def parse_enum_variants(body: str) -> list[VariantDef]:
    """WHY newlines survive into `decl` (unlike the flat single-space join
    used for simple fields): a struct-payload variant's `{ ... }` body has
    its OWN per-field doc comments, which must reach `parse_fields_from_body`
    intact rather than being vacuumed into the variant's own doc -- and that
    parser locates doc-comment lines by newline-adjacency (see
    `split_top_level`)."""
    inner = body[1:-1]
    variants: list[VariantDef] = []
    for chunk in split_top_level(inner, ","):
        lines = chunk.split("\n")
        doc_lines: list[str] = []
        attr_lines: list[str] = []
        decl_started = False
        decl_raw_lines: list[str] = []
        for line in lines:
            s = line.strip()
            if not decl_started:
                if not s:
                    continue
                if s.startswith("///"):
                    doc_lines.append(s[3:].strip())
                    continue
                if re.match(r"^#\[.*\]$", s):
                    attr_lines.append(s)
                    continue
                decl_started = True
            decl_raw_lines.append(line)
        decl = "\n".join(decl_raw_lines).strip()
        if not decl:
            continue
        vm = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*(\{.*\}|\(.*\))?$", decl, re.DOTALL)
        if not vm:
            continue
        vname = vm.group(1)
        payload = vm.group(2)
        doc = re.sub(r"\s+", " ", " ".join(doc_lines)).strip()
        attrs_text = " ".join(attr_lines)
        rename_m = re.search(r'\brename\s*=\s*"([^"]+)"', attrs_text)
        rename = rename_m.group(1) if rename_m else None
        variant_aliases = re.findall(r'alias\s*=\s*"([^"]+)"', attrs_text)
        is_default = "#[default]" in attrs_text
        if payload is None:
            variants.append(
                VariantDef(
                    name=vname, doc=doc, rename=rename, aliases=variant_aliases,
                    is_default=is_default, payload_kind="unit",
                )
            )
        elif payload.startswith("{"):
            fields = parse_fields_from_body(payload)
            variants.append(
                VariantDef(
                    name=vname,
                    doc=doc,
                    rename=rename,
                    aliases=variant_aliases,
                    is_default=is_default,
                    payload_kind="struct",
                    payload_fields=fields,
                )
            )
        else:
            variants.append(
                VariantDef(
                    name=vname,
                    doc=doc,
                    rename=rename,
                    aliases=variant_aliases,
                    is_default=is_default,
                    payload_kind="tuple",
                    payload_type=payload[1:-1].strip(),
                )
            )
    return variants


# ── case conversion ─────────────────────────────────────────────────────


def field_wire_name(fd: FieldDef, container_rename_all: str | None) -> str:
    if fd.rename:
        return fd.rename
    case = container_rename_all
    ident = fd.name
    if case is None or case == "snake_case":
        return ident
    words = ident.split("_")
    if case == "camelCase":
        return words[0] + "".join(w.capitalize() for w in words[1:] if w)
    if case == "kebab-case":
        return "-".join(words)
    if case == "lowercase":
        return "".join(words)
    if case == "UPPERCASE":
        return "".join(words).upper()
    return ident


def split_pascal(ident: str) -> list[str]:
    return re.findall(r"[A-Z][a-z0-9]*|[0-9]+", ident) or [ident]


def variant_wire_name(vd: VariantDef, case: str | None) -> str:
    if vd.rename:
        return vd.rename
    if case is None:
        return vd.name
    words = [w.lower() for w in split_pascal(vd.name)]
    if case == "snake_case":
        return "_".join(words)
    if case == "kebab-case":
        return "-".join(words)
    if case == "lowercase":
        return "".join(words)
    if case == "camelCase":
        return words[0] + "".join(w.capitalize() for w in words[1:])
    if case == "UPPERCASE":
        return "".join(words).upper()
    return vd.name


# ── default-expression resolution ───────────────────────────────────────


def strip_owned(expr: str) -> str:
    e = expr.strip()
    e = re.sub(r"\.to_owned\(\)\s*$", "", e)
    e = re.sub(r"\.to_string\(\)\s*$", "", e)
    e = re.sub(r"\.into\(\)\s*$", "", e)
    return e.strip()


_USE_IMPORTS_CACHE: dict[Path, dict[str, str]] = {}


def parse_use_imports(file_path: Path) -> dict[str, str]:
    """Map a plain (non-aliased-with-`as`, handled separately for `use X as
    d;` inside a fn body) `use` import's bare imported name to its full
    path, e.g. `use koina::http::DEFAULT_CSRF_HEADER_VALUE;` ->
    {"DEFAULT_CSRF_HEADER_VALUE": "koina::http::DEFAULT_CSRF_HEADER_VALUE"},
    and `use a::b::{X, Y as Z};` -> {"X": "a::b::X", "Z": "a::b::Y"}."""
    if file_path in _USE_IMPORTS_CACHE:
        return _USE_IMPORTS_CACHE[file_path]
    text = read_file(file_path)
    imports: dict[str, str] = {}
    for m in re.finditer(r"^\s*use\s+([\w:]+)(?:::\{([^}]*)\})?\s*;", text, re.MULTILINE):
        path, group = m.group(1), m.group(2)
        if group is None:
            segs = path.split("::")
            imports.setdefault(segs[-1], path)
        else:
            for item in split_top_level(group, ","):
                item = item.strip()
                if not item:
                    continue
                am = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+as\s+([A-Za-z_][A-Za-z0-9_]*)$", item)
                if am:
                    imports.setdefault(am.group(2), f"{path}::{am.group(1)}")
                else:
                    imports.setdefault(item, f"{path}::{item}")
    _USE_IMPORTS_CACHE[file_path] = imports
    return imports


def resolve_value(
    expr: str,
    *,
    local_consts: dict[str, str],
    locals_map: dict[str, str],
    depth: int = 0,
    source_file: Path | None = None,
) -> str:
    """Best-effort resolution of a Rust default-value expression to a
    reader-facing literal. Never fabricates: an unresolvable expression is
    returned as literal Rust source (backticked by the caller)."""
    e = strip_owned(expr)
    if depth > MAX_RESOLVE_DEPTH:
        return f"`{e}`"

    if e == "None":
        return "unset"
    if e in ("Vec::new()", "vec![]", "HashMap::new()", "PathBuf::new()"):
        return "[]" if "Vec" in e or "vec" in e else ("{}" if "HashMap" in e else '""')
    if e == "String::new()":
        return '""'
    if e in ("true", "false"):
        return e

    m_some = re.match(r"^Some\((.+)\)$", e, re.DOTALL)
    if m_some:
        return resolve_value(
            m_some.group(1),
            local_consts=local_consts,
            locals_map=locals_map,
            depth=depth + 1,
            source_file=source_file,
        )

    m_str = re.match(r'^"((?:\\.|[^"\\])*)"$', e)
    if m_str:
        return f'"{m_str.group(1)}"'

    m_num = re.match(r"^-?[0-9][0-9_]*(\.[0-9_]+)?$", e)
    if m_num:
        return e

    # Safe integer-literal arithmetic (e.g. `50 * 1024 * 1024`, `24 * 3600`).
    # WHY eval() is safe here: the pattern below constrains the ENTIRE
    # string to digits/underscores/whitespace/`*+-` before eval ever runs,
    # so there is no expression this can evaluate other than the arithmetic
    # it was just proven to consist of -- not a general Rust interpreter.
    if re.match(r"^[0-9_]+(\s*[*+\-]\s*[0-9_]+)+$", e):
        try:
            value = eval(e.replace("_", ""), {"__builtins__": {}}, {})  # noqa: S307
            return str(value)
        except Exception:
            pass

    m_vec = re.match(r"^vec!\[(.*)\]$", e, re.DOTALL)
    if m_vec:
        items = split_top_level(m_vec.group(1), ",")
        resolved = [
            resolve_value(
                it, local_consts=local_consts, locals_map=locals_map, depth=depth + 1, source_file=source_file
            )
            for it in items
        ]
        return "[" + ", ".join(resolved) + "]"

    m_secs = re.match(r"^(.+)\.as_secs\(\)$", e)
    if m_secs:
        base = resolve_raw_ref(
            m_secs.group(1).strip(), local_consts=local_consts, locals_map=locals_map, depth=depth
        )
        m_from = re.match(r"^Duration::from_secs\(([^)]+)\)$", base)
        if m_from:
            return resolve_value(
                m_from.group(1),
                local_consts=local_consts,
                locals_map=locals_map,
                depth=depth + 1,
                source_file=source_file,
            )
        return f"`{e}`"

    m_millis = re.match(r"^(.+)\.as_millis\(\)$", e)
    if m_millis:
        base = resolve_raw_ref(
            m_millis.group(1).strip(), local_consts=local_consts, locals_map=locals_map, depth=depth
        )
        m_from = re.match(r"^Duration::from_millis\(([^)]+)\)$", base)
        if m_from:
            return resolve_value(
                m_from.group(1),
                local_consts=local_consts,
                locals_map=locals_map,
                depth=depth + 1,
                source_file=source_file,
            )
        return f"`{e}`"

    # EnumName::Variant / path::to::EnumName::Variant (not followed by a call).
    # WHY the SCREAMING_SNAKE_CASE exclusion: this pattern is a superset of
    # `path::to::CONST_NAME` (a bare uppercase identifier is also valid
    # `[A-Za-z][A-Za-z0-9_]*`), and every Rust `const` in this codebase is
    # SCREAMING_SNAKE_CASE while every enum variant here is PascalCase with
    # no underscore -- so a trailing all-caps-with-underscore segment can
    # only ever be a constant, never a variant, and must fall through to the
    # path-const resolver below instead of failing here as "not an enum".
    m_variant = re.match(r"^(?:[A-Za-z_][A-Za-z0-9_]*::)*([A-Za-z][A-Za-z0-9_]*)::([A-Za-z][A-Za-z0-9_]*)$", e)
    if m_variant and not re.match(r"^[A-Z][A-Z0-9_]*$", m_variant.group(2)):
        enum_name, variant_name = m_variant.group(1), m_variant.group(2)
        parsed = parse_type(enum_name)
        if isinstance(parsed, EnumDef):
            for v in parsed.variants:
                if v.name == variant_name:
                    if parsed.has_serde:
                        return f'"{variant_wire_name(v, parsed.rename_all)}"'
                    return f"`{enum_name}::{variant_name}`"
        return f"`{e}`"

    # bare Type::default() as the whole value (no further field access)
    m_whole_default = re.match(
        r"^(?:[a-z_][A-Za-z0-9_]*::)*([A-Za-z][A-Za-z0-9_]*)::default\(\)$", e
    )
    if m_whole_default:
        structural = structural_default(m_whole_default.group(1))
        if structural is not None:
            return structural
        return f"`{e}`"

    # bare no-arg lowercase function call resolved from the same source file
    # (mirrors #[serde(default = "fn")] resolution, for defaults that call a
    # local helper function directly rather than naming it via that attr).
    m_fn_call = re.match(r"^([a-z_][A-Za-z0-9_]*)\(\)$", e)
    if m_fn_call and source_file is not None:
        fn_expr = resolve_named_default_fn(source_file, m_fn_call.group(1))
        if fn_expr is not None:
            return resolve_value(
                fn_expr, local_consts=local_consts, locals_map=locals_map, depth=depth + 1, source_file=source_file
            )

    # bare same-file / local const, imported const via `use path::CONST;`,
    # or arithmetic over one
    m_const = re.match(r"^[A-Z][A-Z0-9_]*$", e)
    if m_const:
        if e in local_consts:
            return resolve_value(
                local_consts[e],
                local_consts=local_consts,
                locals_map=locals_map,
                depth=depth + 1,
                source_file=source_file,
            )
        if source_file is not None:
            imported = parse_use_imports(source_file).get(e)
            if imported is not None:
                return resolve_value(
                    imported,
                    local_consts={},
                    locals_map={},
                    depth=depth + 1,
                    source_file=source_file,
                )

    # lowercase local let-binding field access: IDENT.field[.field2...]
    m_local_field = re.match(r"^([a-z_][A-Za-z0-9_]*)((?:\.[A-Za-z_][A-Za-z0-9_]*)+)$", e)
    if m_local_field and m_local_field.group(1) in locals_map:
        base_expr = locals_map[m_local_field.group(1)]
        field_path = m_local_field.group(2).lstrip(".").split(".")
        resolved = resolve_struct_field_chain(base_expr, field_path, depth=depth)
        if resolved is not None:
            return resolved
        return f"`{e}`"

    # path::to::CONST (cross- or same-crate constant)
    m_path_const = re.match(r"^([a-z_][A-Za-z0-9_]*)::((?:[a-z_][A-Za-z0-9_]*::)*)([A-Z][A-Z0-9_]*)$", e)
    if m_path_const:
        crate = m_path_const.group(1)
        const_name = m_path_const.group(3)
        const_file = locate_const_file(crate, const_name)
        if const_file is not None:
            text = read_file(const_file)
            file_consts = parse_local_consts(text)
            if const_name in file_consts:
                return resolve_value(
                    file_consts[const_name],
                    local_consts=file_consts,
                    locals_map={},
                    depth=depth + 1,
                    source_file=const_file,
                )
        return f"`{e}`"

    # path::to::Type::default().field access without an intermediate let
    m_default_field = re.match(
        r"^([a-z_][A-Za-z0-9_:]*::)?([A-Za-z][A-Za-z0-9_]*)::default\(\)((?:\.[A-Za-z_][A-Za-z0-9_]*)+)$",
        e,
    )
    if m_default_field:
        type_name = m_default_field.group(2)
        field_path = m_default_field.group(3).lstrip(".").split(".")
        resolved = resolve_struct_field_chain(f"{type_name}::default()", field_path, depth=depth)
        if resolved is not None:
            return resolved

    return f"`{e}`"


def resolve_raw_ref(expr: str, *, local_consts: dict[str, str], locals_map: dict[str, str], depth: int) -> str:
    """Like resolve_value but returns the raw (still-Rust) resolved form
    rather than a rendered literal -- used when the caller needs to pattern
    match the result further (e.g. Duration::from_secs(N))."""
    e = expr.strip()
    m_path_const = re.match(r"^([a-z_][A-Za-z0-9_]*)::((?:[a-z_][A-Za-z0-9_]*::)*)([A-Z][A-Z0-9_]*)$", e)
    if m_path_const:
        crate = m_path_const.group(1)
        const_name = m_path_const.group(3)
        const_file = locate_const_file(crate, const_name)
        if const_file is not None:
            file_consts = parse_local_consts(read_file(const_file))
            if const_name in file_consts:
                return file_consts[const_name]
    if e in local_consts:
        return local_consts[e]
    return e


def resolve_struct_field_chain(base_expr: str, field_path: list[str], *, depth: int) -> str | None:
    """base_expr is expected to look like `path::to::TypeName::default()`;
    walk TypeName's own impl-Default field map along field_path."""
    m = re.match(r"^(?:[A-Za-z_][A-Za-z0-9_]*::)*([A-Za-z][A-Za-z0-9_]*)::default\(\)$", base_expr.strip())
    if not m:
        return None
    type_name = m.group(1)
    parsed = parse_type(type_name)
    if not isinstance(parsed, StructDef):
        return None
    current_defaults = parsed.defaults
    current_file_text = read_file(parsed.source_file)
    current_locals = parse_local_consts(current_file_text)
    _, sub_locals_map = parse_defaults_from_impl(current_file_text, type_name)
    for i, fname in enumerate(field_path):
        if fname not in current_defaults:
            return None
        expr = current_defaults[fname]
        if i == len(field_path) - 1:
            return resolve_value(
                expr,
                local_consts=current_locals,
                locals_map=sub_locals_map,
                depth=depth + 1,
                source_file=parsed.source_file,
            )
        # descend further: expr must itself be TypeName::default() for a
        # struct-typed intermediate field
        inner_m = re.match(
            r"^(?:[A-Za-z_][A-Za-z0-9_]*::)*([A-Za-z][A-Za-z0-9_]*)::default\(\)$", expr.strip()
        )
        if not inner_m:
            return None
        current_defaults, current_locals, sub_locals_map = _defaults_for_type(inner_m.group(1))
        if current_defaults is None:
            return None
    return None


def _defaults_for_type(type_name: str):
    parsed = parse_type(type_name)
    if not isinstance(parsed, StructDef):
        return None, {}, {}
    text = read_file(parsed.source_file)
    consts = parse_local_consts(text)
    _, locals_map = parse_defaults_from_impl(text, type_name)
    return parsed.defaults, consts, locals_map


def enum_default_variant(enum_def: EnumDef) -> VariantDef | None:
    # WHY no fallback to variants[0]: a Rust enum only has a structural
    # `Default::default()` when one variant is tagged `#[default]` (or a
    # manual `impl Default` supplies one, which this function is never the
    # source of truth for). Guessing the first declared variant would
    # fabricate a default for a type this generator cannot actually prove
    # implements `Default`, violating the module's never-guess contract.
    for v in enum_def.variants:
        if v.is_default:
            return v
    return None


def resolve_named_default_fn(file_path: Path, fn_name: str) -> str | None:
    """Resolve a `#[serde(default = "fn_name")]` provider function to its
    return-value expression (tail expression or explicit `return`)."""
    text = read_file(file_path)
    m = re.search(rf"\bfn\s+{re.escape(fn_name)}\s*\([^)]*\)\s*(?:->\s*[^{{]+)?\{{", text)
    if not m:
        return None
    body_start = text.index("{", m.start())
    body_end = find_matching_brace(text, body_start)
    body = text[body_start + 1 : body_end - 1].strip()
    stmts = split_top_level(body, ";")
    if not stmts:
        return None
    tail = stmts[-1].strip()
    tail = re.sub(r"^return\s+", "", tail).strip()
    return tail or None


def resolve_tuple_newtype_default(type_name: str) -> str | None:
    """`impl Default for X { fn default() -> Self { Self(EXPR) } }` -- the
    tuple-struct-constructor shape `parse_type` deliberately does not
    recurse into (a single-field newtype has no TOML table shape), but its
    one wrapped value is still a real, resolvable default."""
    type_file = locate_type_file(type_name, "struct")
    if type_file is None:
        return None
    text = read_file(type_file)
    m = re.search(rf"impl\s+Default\s+for\s+{re.escape(type_name)}\s*\{{", text)
    if not m:
        return None
    body_end = find_matching_brace(text, text.index("{", m.end() - 1))
    impl_body = text[m.end() - 1 : body_end]
    fn_m = re.search(r"fn\s+default\s*\(\s*\)\s*->\s*Self\s*\{", impl_body)
    if not fn_m:
        return None
    fn_body_start = impl_body.index("{", fn_m.end() - 1)
    fn_body_end = find_matching_brace(impl_body, fn_body_start)
    fn_body = impl_body[fn_body_start + 1 : fn_body_end - 1].strip()
    tuple_m = re.match(r"^Self\((.+)\)$", fn_body, re.DOTALL)
    if not tuple_m:
        return None
    local_consts = parse_local_consts(text)
    return resolve_value(
        tuple_m.group(1), local_consts=local_consts, locals_map={}, depth=0, source_file=type_file
    )


def structural_default(base_ty: str) -> str | None:
    """The value `FieldType::default()` would produce, derived structurally
    (primitive Default semantics / `#[default]` enum variant) -- used both
    for `#[derive(Default)]` containers and for individually
    `#[serde(default)]`-marked fields on a container with no such derive."""
    head = strip_generics_name(base_ty)
    prim = PRIMITIVE_DEFAULTS.get(head)
    if prim is not None:
        return prim
    if base_ty.startswith("Vec<") or base_ty.startswith("vec!"):
        return "[]"
    if base_ty.startswith("HashMap<"):
        return "{}"
    parsed = parse_type(head)
    if isinstance(parsed, EnumDef):
        dv = enum_default_variant(parsed)
        if dv is not None:
            if parsed.has_serde:
                return f'"{variant_wire_name(dv, parsed.rename_all)}"'
            return f"`{parsed.name}::{dv.name}`"
    if parsed is None:
        return resolve_tuple_newtype_default(head)
    return None


def scalar_default(fd: FieldDef, container: StructDef) -> str:
    """Render the default-value text for a non-struct-bearing field."""
    text = read_file(container.source_file)
    local_consts = parse_local_consts(text)
    _, locals_map = parse_defaults_from_impl(text, container.name)

    if fd.name in container.defaults:
        return resolve_value(
            container.defaults[fd.name],
            local_consts=local_consts,
            locals_map=locals_map,
            depth=0,
            source_file=container.source_file,
        )

    if fd.default_fn:
        fn_expr = resolve_named_default_fn(container.source_file, fd.default_fn)
        if fn_expr is not None:
            return resolve_value(
                fn_expr,
                local_consts=local_consts,
                locals_map=locals_map,
                depth=0,
                source_file=container.source_file,
            )

    base_ty = unwrap_option(fd.ty)
    is_option = base_ty != fd.ty

    # WHY is_option is checked before structural_default: `Option<T>`'s
    # structural default is always `None` ("unset"), regardless of what
    # `T::default()` would produce. A field such as
    # `#[serde(default)] pub api_family: Option<OpenAiApiFamily>` on a
    # container with no `impl Default` has no resolvable literal for T, and
    # its real runtime default is `None` -- computing structural_default(T)
    # first would fabricate a value (e.g. T's first enum variant, or `""`
    # for `Option<String>`) that the field is never actually assigned.
    if is_option and (fd.has_bare_default or container.has_derive_default or container.has_impl_default):
        return "unset"

    if fd.has_bare_default or container.has_derive_default:
        structural = structural_default(base_ty)
        if structural is not None:
            return structural

    return "*required*"


# ── type classification for rendering ───────────────────────────────────


def strip_generics_name(ty: str) -> str:
    """`Option<Foo>` -> `Foo` is NOT what this does; this returns the bare
    head identifier of a possibly-generic type, e.g. `Vec<Foo>` -> `Vec`,
    `Foo` -> `Foo`."""
    m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*)", ty.strip())
    return m.group(1).rsplit("::", 1)[-1] if m else ty.strip()


def unwrap_option(ty: str) -> str:
    m = re.match(r"^Option\s*<\s*(.+)\s*>$", ty.strip(), re.DOTALL)
    return m.group(1).strip() if m else ty.strip()


def unwrap_vec(ty: str) -> str | None:
    m = re.match(r"^Vec\s*<\s*(.+)\s*>$", ty.strip(), re.DOTALL)
    return m.group(1).strip() if m else None


def unwrap_hashmap(ty: str) -> tuple[str, str] | None:
    m = re.match(r"^HashMap\s*<\s*(.+)\s*>$", ty.strip(), re.DOTALL)
    if not m:
        return None
    parts = split_top_level(m.group(1), ",")
    if len(parts) != 2:
        return None
    return parts[0].strip(), parts[1].strip()


def bare_type_name(ty: str) -> str:
    t = unwrap_option(ty)
    v = unwrap_vec(t)
    if v is not None:
        return strip_generics_name(v)
    hm = unwrap_hashmap(t)
    if hm is not None:
        return strip_generics_name(hm[1])
    return strip_generics_name(t)


def simplify_scalar_type(ty: str, fd: FieldDef | None = None) -> str:
    t = unwrap_option(ty)
    hm = unwrap_hashmap(t)
    if hm is not None:
        key_label = simplify_scalar_type(hm[0])
        val_label = simplify_scalar_type(hm[1])
        return f"map<{key_label}, {val_label}>"
    v = unwrap_vec(t)
    if v is not None:
        inner = simplify_scalar_type(v)
        return (f"({inner})[]" if "\\|" in inner else f"{inner}[]")
    head = strip_generics_name(t)
    if head in OPAQUE_TYPE_LABELS:
        return OPAQUE_TYPE_LABELS[head]
    parsed = parse_type(head)
    if isinstance(parsed, EnumDef):
        if parsed.has_serde and all(vv.payload_kind == "unit" for vv in parsed.variants):
            cells = []
            for v in parsed.variants:
                wire = variant_wire_name(v, parsed.rename_all)
                cell = f'"{wire}"'
                if v.aliases:
                    alias_txt = ", ".join(f'"{a}"' for a in v.aliases)
                    cell += f" (alias: {alias_txt})"
                cells.append(cell)
            return " \\| ".join(cells)
        return f"`{head}`"
    return f"`{t}`"


def is_struct_bearing(ty: str) -> StructDef | None:
    t = unwrap_option(ty)
    v = unwrap_vec(t)
    if v is not None:
        t = v
    hm = unwrap_hashmap(t)
    if hm is not None:
        t = hm[1]
    head = strip_generics_name(t)
    if head in OPAQUE_TYPE_LABELS:
        return None
    parsed = parse_type(head)
    if isinstance(parsed, StructDef):
        return parsed
    if isinstance(parsed, EnumDef) and any(vv.payload_kind != "unit" for vv in parsed.variants):
        return None  # rendered specially, not as a plain struct subsection
    return None


def container_note(ty: str) -> str | None:
    t = unwrap_option(ty)
    is_opt = t != ty.strip()
    if unwrap_vec(t) is not None:
        return "array of tables"
    if unwrap_hashmap(t) is not None:
        return "map of tables, keyed by name"
    if is_opt:
        return "optional table"
    return None


# ── markdown rendering ───────────────────────────────────────────────────


def esc(s: str) -> str:
    return s.replace("|", "\\|").strip()


def gfm_anchor(heading: str) -> str:
    a = heading.lower()
    a = re.sub(r"[^a-z0-9 _-]", "", a)
    a = a.replace(" ", "-")
    return a


@dataclass
class Section:
    heading: str
    level: int
    doc: str
    note: str | None
    rows: list[tuple[str, str, str, str]]  # field, type, default, description
    raw: str | None = None  # pre-rendered markdown, used instead of doc+rows


def non_unit_enum_for(ty: str) -> EnumDef | None:
    base_ty = unwrap_option(ty)
    head = strip_generics_name(unwrap_vec(base_ty) or base_ty)
    parsed = parse_type(head)
    # WHY has_serde is required, not just a non-unit variant: this classifies
    # the field as a `#[serde(tag = "...")]`-style tagged-variant subsection,
    # and `render_enum_variants_section` hardcodes "Tagged on `type`" prose.
    # An enum with a hand-written (non-derived) Serialize/Deserialize impl --
    # e.g. `AgentToolGroupPolicy`, which deserializes a bare string or a bare
    # sequence with no tag at all -- has no derived shape this generator can
    # verify, so asserting internal tagging for it would fabricate a wire
    # format the field does not use. `simplify_scalar_type` and
    # `resolve_value` already gate their own enum handling on `has_serde` for
    # the same reason; this mirrors that guard rather than introducing a new
    # rule.
    if (
        isinstance(parsed, EnumDef)
        and parsed.has_serde
        and any(v.payload_kind != "unit" for v in parsed.variants)
    ):
        return parsed
    return None


def collect_sections(
    struct_def: StructDef,
    dotted_path: str,
    level: int,
    sections: list[Section],
    seen: set[str],
    heading: str,
    intro_doc: str = "",
    note: str | None = None,
) -> None:
    key = f"{dotted_path}"
    if key in seen:
        return
    seen.add(key)

    rows: list[tuple[str, str, str, str]] = []
    nested: list[tuple[FieldDef, str, StructDef]] = []
    variant_blocks: list[tuple[FieldDef, str, EnumDef]] = []

    def walk_fields(sd: StructDef, prefix: str) -> None:
        for fd in sd.fields:
            if fd.skip:
                continue
            wire = field_wire_name(fd, sd.rename_all)
            child_path = f"{prefix}.{wire}" if prefix else wire
            struct_child = is_struct_bearing(fd.ty)
            if fd.flatten and struct_child is not None:
                walk_fields(struct_child, prefix)
                continue
            if struct_child is not None:
                nested.append((fd, child_path, struct_child))
                continue
            variant_enum = non_unit_enum_for(fd.ty)
            if variant_enum is not None:
                variant_blocks.append((fd, child_path, variant_enum))
                continue
            ty_label = simplify_scalar_type(fd.ty, fd)
            default_label = scalar_default(fd, sd)
            desc = fd.doc
            if fd.aliases:
                desc = (desc + f" Aliases: {', '.join('`' + a + '`' for a in fd.aliases)}.").strip()
            rows.append((f"`{wire}`", ty_label, default_label, esc(desc)))

    walk_fields(struct_def, dotted_path)

    sections.append(Section(heading=heading, level=level, doc=intro_doc, note=note, rows=rows))

    for fd, child_path, enum_def in variant_blocks:
        block_key = f"{child_path}::variants"
        if block_key in seen:
            continue
        seen.add(block_key)
        sections.append(
            Section(
                heading=child_path,
                level=min(level + 1, 6),
                doc="",
                note=None,
                rows=[],
                raw=render_enum_variants_section(fd, enum_def, child_path, min(level + 1, 6)),
            )
        )

    for fd, child_path, child_struct in nested:
        note = container_note(fd.ty)
        child_heading = f"{child_path}[]" if note == "array of tables" else child_path
        collect_sections(
            child_struct,
            child_path,
            min(level + 1, 6),
            sections,
            seen,
            child_heading,
            intro_doc=fd.doc,
            note=note,
        )


def render_variant_payload_table(vd: VariantDef) -> str:
    lines = ["| Field | Type | Description |", "|-------|------|-------------|"]
    for fd in vd.payload_fields:
        ty_label = simplify_scalar_type(fd.ty)
        lines.append(f"| `{fd.name}` | {ty_label} | {esc(fd.doc)} |")
    return "\n".join(lines)


def render_enum_variants_section(fd: FieldDef, enum_def: EnumDef, heading: str, level: int) -> str:
    out = [f"{'#' * level} {heading}", ""]
    if enum_def.doc:
        out.append(enum_def.doc)
        out.append("")
    if fd.doc:
        out.append(fd.doc)
        out.append("")
    out.append("Tagged on `type`. One of:")
    out.append("")
    for v in enum_def.variants:
        wire = variant_wire_name(v, enum_def.rename_all)
        out.append(f"- **`{wire}`** -- {v.doc}" if v.doc else f"- **`{wire}`**")
        if v.payload_kind == "struct" and v.payload_fields:
            out.append("")
            out.append(render_variant_payload_table(v))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_section(s: Section) -> str:
    if s.raw is not None:
        return s.raw
    out = [f"{'#' * s.level} {s.heading}", ""]
    if s.note:
        out.append(f"*({s.note})*")
        out.append("")
    if s.doc:
        out.append(s.doc)
        out.append("")
    if s.rows:
        out.append("| Field | Type | Default | Description |")
        out.append("|-------|------|---------|-------------|")
        for f_, t_, d_, desc_ in s.rows:
            out.append(f"| {f_} | {t_} | {d_} | {desc_} |")
        out.append("")
    return "\n".join(out)


TOP_LEVEL_DOC_OVERRIDES: dict[str, str] = {}


def build_reference() -> str:
    root_struct = parse_type(ROOT_TYPE)
    assert isinstance(root_struct, StructDef), f"could not parse `pub struct {ROOT_TYPE}` in {ROOT_FILE}"
    top_fields = root_struct.fields
    rename_all = root_struct.rename_all

    toc_entries_variant_only: list[str] = []
    blocks: list[str] = []
    all_sections: list[Section] = []
    seen: set[str] = set()

    for fd in top_fields:
        if fd.skip:
            continue
        wire = field_wire_name(fd, rename_all)
        struct_child = is_struct_bearing(fd.ty)
        note = container_note(fd.ty)
        if struct_child is not None:
            heading = f"{wire}[]" if note == "array of tables" else wire
            sections: list[Section] = []
            collect_sections(struct_child, wire, 2, sections, seen, heading, intro_doc=fd.doc, note=note)
            all_sections.extend(sections)
            continue

        base_ty = unwrap_option(fd.ty)
        head = strip_generics_name(unwrap_vec(base_ty) or base_ty)
        enum_parsed = parse_type(head)
        if isinstance(enum_parsed, EnumDef) and any(
            v.payload_kind != "unit" for v in enum_parsed.variants
        ):
            variant_md = render_enum_variants_section(fd, enum_parsed, wire, 2)
            blocks.append(variant_md)
            toc_entries_variant_only.append(wire)
            continue

        ty_label = simplify_scalar_type(fd.ty)
        default_label = scalar_default(fd, root_struct)
        section = Section(
            heading=wire,
            level=2,
            doc=fd.doc,
            note=note,
            rows=[(f"`{wire}`", ty_label, default_label, esc(fd.doc))],
        )
        all_sections.append(section)

    # Render in a single deterministic pass: top-level field declaration
    # order (from AletheiaConfig itself), with each top-level field's whole
    # subtree -- and any enum-variant block for that same field -- emitted
    # contiguously right after it.
    out_lines: list[str] = []
    grouped: dict[str, list[Section]] = {}
    variant_blocks_by_top: dict[str, str] = {}
    order: list[str] = []
    for s in all_sections:
        top = s.heading.split(".")[0].rstrip("[]")
        if top not in grouped:
            grouped[top] = []
            order.append(top)
        grouped[top].append(s)
    for wire, block_md in zip(toc_entries_variant_only, blocks):
        variant_blocks_by_top[wire] = block_md
        if wire not in order:
            order.append(wire)

    toc_lines = ["## Table of contents", ""]
    for top in order:
        toc_lines.append(f"- [{top}](#{gfm_anchor(top)})")
    out_lines.append("\n".join(toc_lines))
    out_lines.append("")

    for top in order:
        if top in grouped:
            for s in grouped[top]:
                out_lines.append(render_section(s))
        if top in variant_blocks_by_top:
            out_lines.append(variant_blocks_by_top[top])

    return "\n".join(out_lines).rstrip() + "\n"


# ── doc assembly / --check ───────────────────────────────────────────────


def read_doc() -> str:
    return DOC_PATH.read_text(encoding="utf-8")


def write_doc(content: str) -> None:
    DOC_PATH.write_text(content, encoding="utf-8")


def replace_generated_block(doc: str, generated: str) -> str:
    begin = doc.find(BEGIN_MARKER)
    end = doc.find(END_MARKER)
    if begin == -1 or end == -1:
        raise RuntimeError(
            f"could not find generated-block markers in {DOC_PATH}; "
            "ensure the file contains the BEGIN/END anchors"
        )
    end += len(END_MARKER)
    block = f"{BEGIN_MARKER}\n\n{generated}\n{END_MARKER}"
    return doc[:begin] + block + doc[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed doc's generated block differs from freshly generated output",
    )
    args = parser.parse_args()

    generated = build_reference()

    if args.check:
        try:
            doc = read_doc()
        except FileNotFoundError:
            print(f"ERROR: {DOC_PATH} does not exist; run the generator to create it", file=sys.stderr)
            return 1
        begin = doc.find(BEGIN_MARKER)
        end = doc.find(END_MARKER)
        if begin == -1 or end == -1:
            print(
                "ERROR: generated-block markers missing from docs/CONFIGURATION.md; "
                "run the generator to recreate them",
                file=sys.stderr,
            )
            return 1
        end += len(END_MARKER)
        expected_block = f"{BEGIN_MARKER}\n\n{generated}\n{END_MARKER}"
        actual_block = doc[begin:end]
        if actual_block != expected_block:
            print(
                "ERROR: docs/CONFIGURATION.md field reference is out of date "
                "with the AletheiaConfig schema.\n"
                "Run the generator to update it:\n"
                "  python3 scripts/generate-configuration-doc.py",
                file=sys.stderr,
            )
            return 1
        print("OK: docs/CONFIGURATION.md field reference matches the AletheiaConfig schema")
        return 0

    doc = read_doc()
    updated = replace_generated_block(doc, generated)
    write_doc(updated)
    print(f"Updated {DOC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
