#!/usr/bin/env python3
"""Generate and maintain the diaporeia MCP tool and resource inventory in CLAUDE.md.

Parses the live #[tool] methods in crates/diaporeia/src/tools/mod.rs and the
resource template definitions in crates/diaporeia/src/resources/ and rewrites
the clearly marked generated block in crates/diaporeia/CLAUDE.md.

Usage:
    python3 scripts/generate-diaporeia-mcp-inventory.py
    python3 scripts/generate-diaporeia-mcp-inventory.py --check

--check exits 0 when the committed docs match the generated inventory and
non-zero with a clear instruction to regenerate.
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS_PATH = REPO_ROOT / "crates" / "diaporeia" / "src" / "tools" / "mod.rs"
RESOURCES_DIR = REPO_ROOT / "crates" / "diaporeia" / "src" / "resources"
CLAUDE_PATH = REPO_ROOT / "crates" / "diaporeia" / "CLAUDE.md"

BEGIN_MARKER = "<!-- BEGIN MCP INVENTORY -- generated by scripts/generate-diaporeia-mcp-inventory.py -->"
END_MARKER = "<!-- END MCP INVENTORY -->"

# WHY: These are the concrete state-changing calls observed in the tool
# implementations. A tool is classified as mutating when its body contains any
# of these signatures. The heuristic is explicit, deterministic, and validated
# by the unit tests in this script.
MUTATION_SIGNATURES = [
    "find_or_create_session",
    "send_turn_streaming",
    "insert_fact_async",
    "forget_fact",
    "vault.store(",
    "vault.remove(",
    "store.add_note(",
    "store.delete_note(",
    "store.write(",
    "store.delete(",
]

TOOL_RE = re.compile(
    r"#\[tool\s*\((?P<attr>.*?)\)\]\s*async\s+fn\s+(?P<name>[a-z_][a-z0-9_]*)\s*\(",
    re.DOTALL,
)
DESCRIPTION_RE = re.compile(
    r'description\s*=\s*(?P<value>(?:"(?:\\.|[^"\\])*"\s*)+)',
    re.DOTALL,
)
STRING_LITERAL_RE = re.compile(r'"(?:\\.|[^"\\])*"', re.DOTALL)
TIER_RE = re.compile(r"self\.rate_limiter\.check\(Tier::(?P<tier>\w+)\)")
ROLE_RE = re.compile(r"require(?:_caller)?_role\s*\(\s*(?:self\s*,\s*&context|&caller)\s*,\s*Role::(?P<role>\w+)")

# WHY: resource templates are statically defined as tuples or RawResourceTemplate::new calls.
# Parse the WORKSPACE_FILES constant for the nous templates and the config resource separately.
WORKSPACE_FILES_RE = re.compile(
    r'WORKSPACE_FILES:\s*&\[\s*\(&str,\s*&str,\s*&str\)\]\s*=\s*&\[(.*?)\];',
    re.DOTALL,
)
WORKSPACE_TUPLE_RE = re.compile(
    r'\(\s*"(?P<slug>[^"]+)"\s*,\s*"(?P<name>[^"]+)"\s*,\s*"(?P<desc>[^"]+)"\s*\)',
)
RAW_RESOURCE_TEMPLATE_RE = re.compile(
    r'RawResourceTemplate::new\(\s*"(?P<uri>[^"]+)"\s*,\s*"(?P<name>[^"]+)"\s*\)'
    r'(?:.*?\.with_description\(\s*"(?P<desc>[^"]+)"\s*\))?',
    re.DOTALL,
)
# Extract RBAC role from require_resource_role call context in server.rs
RESOURCE_ROLE_RE = re.compile(
    r'require_resource_role\s*\(\s*&context\s*,\s*Role::(?P<role>\w+)\s*,\s*"[^"]*"\s*\)'
)
NOUS_URI_PREFIX = "aletheia://nous/{nous_id}/"


def _find_tool_spans(source: str) -> list[tuple[str, str, int, int]]:
    """Return (name, attr, body_start, body_end) for each #[tool] method."""
    spans = []
    for match in TOOL_RE.finditer(source):
        name = match.group("name")
        attr = match.group("attr")
        body_start = source.find("{", match.end())
        if body_start == -1:
            raise RuntimeError(f"could not find body start for tool {name}")
        depth = 1
        pos = body_start + 1
        while pos < len(source) and depth > 0:
            if source[pos] == "{":
                depth += 1
            elif source[pos] == "}":
                depth -= 1
            pos += 1
        if depth != 0:
            raise RuntimeError(f"unbalanced braces in tool {name}")
        spans.append((name, attr, body_start, pos))
    return spans


def _decode_rust_string_literal(literal: str) -> str:
    body = literal[1:-1]
    body = re.sub(r"\\\s*\n\s*", " ", body)
    return ast.literal_eval(f'"{body}"')


def _extract_description(attr: str, name: str) -> str:
    match = DESCRIPTION_RE.search(attr)
    if match is None:
        raise RuntimeError(f"could not determine description for {name}")
    parts = STRING_LITERAL_RE.findall(match.group("value"))
    description = " ".join(_decode_rust_string_literal(part) for part in parts)
    description = re.sub(r"\s+", " ", description).strip()
    return _escape_table_cell(description)


def _escape_table_cell(value: str) -> str:
    return value.replace("|", r"\|")


def _extract_tool(source: str, name: str, attr: str, body_start: int, body_end: int) -> dict:
    body = source[body_start:body_end]

    tier_match = TIER_RE.search(body)
    if tier_match is None:
        raise RuntimeError(f"could not determine rate-limit tier for {name}")
    tier = tier_match.group("tier")

    role_match = ROLE_RE.search(body)
    if role_match is None:
        raise RuntimeError(f"could not determine required role for {name}")
    role = role_match.group("role")

    mutates = any(sig in body for sig in MUTATION_SIGNATURES)

    return {
        "name": name,
        "tier": tier,
        "role": role,
        "mutates": "Yes" if mutates else "No",
        "purpose": _extract_description(attr, name),
    }


def _format_inventory(tools: list[dict]) -> str:
    lines = [
        f"## MCP tools ({len(tools)})",
        "",
        "| Tool | Tier | RBAC | Mutates | Purpose |",
        "|------|------|------|---------|---------|",
    ]
    for tool in sorted(tools, key=lambda t: t["name"]):
        lines.append(
            f"| `{tool['name']}` | {tool['tier']} | {tool['role']} | {tool['mutates']} | {tool['purpose']} |"
        )
    return "\n".join(lines)


def parse_tools(source: str) -> list[dict]:
    """Parse the source and return the list of tool metadata dicts."""
    spans = _find_tool_spans(source)
    return [_extract_tool(source, name, attr, start, end) for name, attr, start, end in spans]


def parse_resource_templates() -> list[dict]:
    """Parse resource template definitions from crates/diaporeia/src/resources/.

    Returns a list of dicts with keys: uri, name, description, rbac, source.
    RBAC is determined from the list_resource_templates handler in server.rs.
    """
    templates: list[dict] = []

    # Determine RBAC role from server.rs list_resource_templates handler.
    server_path = RESOURCES_DIR.parent / "server.rs"
    rbac_role = "Operator"  # WHY: default from server.rs require_resource_role call
    if server_path.exists():
        server_source = server_path.read_text(encoding="utf-8")
        role_match = RESOURCE_ROLE_RE.search(server_source)
        if role_match:
            rbac_role = role_match.group("role")

    # Parse nous workspace file templates from resources/nous.rs.
    nous_path = RESOURCES_DIR / "nous.rs"
    if nous_path.exists():
        nous_source = nous_path.read_text(encoding="utf-8")
        wf_match = WORKSPACE_FILES_RE.search(nous_source)
        if wf_match:
            for t in WORKSPACE_TUPLE_RE.finditer(wf_match.group(1)):
                slug = t.group("slug")
                templates.append({
                    "uri": f"{NOUS_URI_PREFIX}{slug}",
                    "name": t.group("name"),
                    "description": t.group("desc"),
                    "rbac": rbac_role,
                    "source": "crates/diaporeia/src/resources/nous.rs",
                    "mutates": "No",
                })

    # Parse config resource template from resources/config.rs.
    config_path = RESOURCES_DIR / "config.rs"
    if config_path.exists():
        config_source = config_path.read_text(encoding="utf-8")
        for m in RAW_RESOURCE_TEMPLATE_RE.finditer(config_source):
            uri = m.group("uri")
            name = m.group("name")
            desc = m.group("desc") or ""
            templates.append({
                "uri": uri,
                "name": name,
                "description": desc,
                "rbac": rbac_role,
                "source": "crates/diaporeia/src/resources/config.rs",
                "mutates": "No",
            })

    return templates


def _format_resource_inventory(resources: list[dict]) -> str:
    if not resources:
        return ""
    lines = [
        f"## MCP resource templates ({len(resources)})",
        "",
        "All resource templates require Operator role (enforced by `list_resource_templates`).",
        "Resources are read-only.",
        "",
        "| URI template | Name | Description | Source |",
        "|-------------|------|-------------|--------|",
    ]
    for r in resources:
        uri = _escape_table_cell(r["uri"])
        name = _escape_table_cell(r["name"])
        desc = _escape_table_cell(r["description"])
        src = _escape_table_cell(r["source"])
        lines.append(f"| `{uri}` | {name} | {desc} | `{src}` |")
    return "\n".join(lines)


def generate_block(source: str) -> str:
    """Return the full generated markdown block for CLAUDE.md."""
    tools = parse_tools(source)
    tool_inventory = _format_inventory(tools)
    resources = parse_resource_templates()
    resource_inventory = _format_resource_inventory(resources)
    return (
        f"{BEGIN_MARKER}\n"
        f"{tool_inventory}\n"
        f"\n"
        f"Knowledge graph tools require `mcp.knowledge_graph.enabled = true` in config (default `false`).\n"
        f"\n"
        f"{resource_inventory}\n"
        f"{END_MARKER}"
    )


def read_claude() -> str:
    return CLAUDE_PATH.read_text(encoding="utf-8")


def write_claude(content: str) -> None:
    CLAUDE_PATH.write_text(content, encoding="utf-8")


def replace_inventory(claude: str, generated: str) -> str:
    begin = claude.find(BEGIN_MARKER)
    end = claude.find(END_MARKER)
    if begin == -1 or end == -1:
        raise RuntimeError(
            f"could not find inventory markers in {CLAUDE_PATH}; "
            "ensure the file contains the generated-block anchors"
        )
    end += len(END_MARKER)
    return claude[:begin] + generated + claude[end:]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify the diaporeia MCP tool and resource inventory."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed docs differ from the generated inventory",
    )
    args = parser.parse_args()

    source = TOOLS_PATH.read_text(encoding="utf-8")
    generated = generate_block(source)

    if args.check:
        claude = read_claude()
        begin = claude.find(BEGIN_MARKER)
        end = claude.find(END_MARKER)
        if begin == -1 or end == -1:
            print(
                "ERROR: generated-block markers missing from CLAUDE.md; "
                "run the generator to recreate them",
                file=sys.stderr,
            )
            return 1
        end += len(END_MARKER)
        actual = claude[begin:end]
        if actual != generated:
            print(
                "ERROR: diaporeia MCP inventory (tools + resource templates) is out of date.\n"
                "Run the generator to update the docs:\n"
                "  python3 scripts/generate-diaporeia-mcp-inventory.py",
                file=sys.stderr,
            )
            return 1
        print("OK: diaporeia MCP inventory is up to date")
        return 0

    claude = read_claude()
    updated = replace_inventory(claude, generated)
    write_claude(updated)
    tools = parse_tools(source)
    resources = parse_resource_templates()
    print(f"Updated {CLAUDE_PATH} with {len(tools)} MCP tools and {len(resources)} resource templates")
    return 0


if __name__ == "__main__":
    sys.exit(main())
