#!/usr/bin/env bash
# Install the in-tree git hooks (one-time per clone; idempotent).
#
# Points git at scripts/githooks/ (version-controlled, so every clone gets the
# same fmt/clippy/_llm pre-push + instance-guard pre-commit). Auto-run by .envrc
# on direnv load; run manually if you don't use direnv.
#
# Do NOT run `pre-commit install` — the pre-commit framework is not used here.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
chmod +x scripts/githooks/* 2>/dev/null || true

# WHY(#6705): core.hooksPath is local > global in git's precedence, so setting it
# here unconditionally silently disables a box-wide global core.hooksPath (a
# fleet-wide push guard installed for every repo on the box — see
# ~/.config/git/hooks/lib/local-hook.sh). On a box with no global hooks path
# that's harmless; on a box with one, it is a safety regression, not a
# tradeoff. The global dispatcher already chains to
# "$(git rev-parse --git-common-dir)/hooks/<name>" when that file exists and is
# executable, so a chaining shim there activates this repo's hooks without ever
# touching core.hooksPath.
global_hooks_path="$(git config --global --get core.hooksPath 2>/dev/null || true)"

if [ -n "$global_hooks_path" ]; then
    common_dir="$(git rev-parse --git-common-dir)"
    mkdir -p "$common_dir/hooks"
    for hook in scripts/githooks/*; do
        [ -f "$hook" ] || continue
        name="$(basename "$hook")"
        shim="$common_dir/hooks/$name"
        # WHY resolved at RUN time via `git rev-parse --show-toplevel`, not baked in
        # at install time: git-common-dir/hooks/ is shared across every worktree of
        # this clone, so a shim written from one worktree must still resolve to
        # whichever worktree's own scripts/githooks/$name is invoking it.
        cat > "$shim" <<SHIM
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — chains the global core.hooksPath
# dispatcher to this repo's own scripts/githooks/$name without setting
# core.hooksPath locally (aletheia#6705). Re-run install-hooks.sh to refresh.
set -euo pipefail
exec "\$(git rev-parse --show-toplevel)/scripts/githooks/$name" "\$@"
SHIM
        chmod +x "$shim"
    done
    echo "git hooks installed: chaining shim(s) in $common_dir/hooks/ (global core.hooksPath=$global_hooks_path preserved)"
else
    git config core.hooksPath scripts/githooks
    echo "git hooks installed: core.hooksPath=scripts/githooks (pre-push, pre-commit)"
fi
