//! SSE event types and hermeneus→SSE bridge.

use serde::Serialize;
use utoipa::ToSchema;

/// SSE event emitted to the client during message streaming.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(tag = "type")]
pub enum SseEvent {
    /// Incremental text output from the assistant.
    #[serde(rename = "text_delta")]
    TextDelta { text: String },

    /// Incremental extended-thinking output.
    #[serde(rename = "thinking_delta")]
    ThinkingDelta { thinking: String },

    /// The assistant is invoking a tool.
    #[serde(rename = "tool_use")]
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },

    /// Result returned from a tool execution.
    #[serde(rename = "tool_result")]
    ToolResult {
        tool_use_id: String,
        content: String,
        is_error: bool,
    },

    /// Turn completed — final event in the stream.
    #[serde(rename = "message_complete")]
    MessageComplete {
        stop_reason: String,
        usage: UsageData,
    },

    /// An error occurred during the turn.
    #[serde(rename = "error")]
    Error { code: String, message: String },
}

/// Token usage summary sent with `message_complete`.
#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct UsageData {
    /// Tokens consumed by the system prompt and conversation history.
    pub input_tokens: u64,
    /// Tokens generated by the model in this turn.
    pub output_tokens: u64,
}

impl SseEvent {
    /// SSE event name for the `event:` field.
    pub fn event_type(&self) -> &'static str {
        match self {
            Self::TextDelta { .. } => "text_delta",
            Self::ThinkingDelta { .. } => "thinking_delta",
            Self::ToolUse { .. } => "tool_use",
            Self::ToolResult { .. } => "tool_result",
            Self::MessageComplete { .. } => "message_complete",
            Self::Error { .. } => "error",
        }
    }
}
