//! Chat session and message state for the desktop chat view.

use skene::id::{NousId, SessionId};

/// Session selected by another view for the chat route to activate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ChatSelection {
    /// Agent that owns the session.
    pub agent_id: NousId,
    /// Durable server session ID used for history fetches.
    pub session_id: Option<SessionId>,
    /// Server session key used when streaming turns.
    pub session_key: String, // kanon:ignore RUST/plain-string-secret
    /// Human-readable title shown in the chat tab bar.
    pub title: String, // kanon:ignore RUST/plain-string-secret
    /// Server-reported total message count, used to decide whether older pages exist.
    pub message_count: Option<i64>,
}

impl ChatSelection {
    /// Create an activation request for the chat route.
    #[must_use]
    pub(crate) fn new(
        agent_id: NousId,
        session_key: String, // kanon:ignore RUST/plain-string-secret
        title: String,
    ) -> Self {
        Self {
            agent_id,
            session_id: None,
            session_key,
            title,
            message_count: None,
        }
    }

    /// Create an activation request for a known durable server session.
    #[must_use]
    pub(crate) fn for_existing_session(
        agent_id: NousId,
        session_id: SessionId,
        session_key: String, // kanon:ignore RUST/plain-string-secret
        title: String,
        message_count: i64,
    ) -> Self {
        Self {
            agent_id,
            session_id: Some(session_id),
            session_key,
            title,
            message_count: Some(message_count),
        }
    }
}

/// Role of a chat message sender.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Role {
    /// Message sent by the user.
    User,
    /// Response generated by the assistant.
    Assistant,
    /// System-level message (context, errors).
    System,
}

/// A single chat message in the conversation history.
#[derive(Debug, Clone, PartialEq)]
pub struct ChatMessage {
    /// Unique message identifier (index-based or server-provided).
    pub id: u64,
    /// Who sent this message.
    pub role: Role,
    /// Raw markdown content.
    pub content: String,
    /// Unix timestamp in seconds.
    pub timestamp: i64,
    /// Agent that produced this message (assistant messages only).
    pub agent_id: Option<NousId>,
    /// Number of tool calls made during this turn.
    pub tool_calls: u32,
    /// Extended thinking content, if any.
    pub thinking_content: Option<String>,
    /// Whether this message is still being streamed.
    pub is_streaming: bool,
    /// Model that generated this message.
    pub model: Option<String>,
    /// Input tokens consumed.
    pub input_tokens: u32,
    /// Output tokens produced.
    pub output_tokens: u32,
}

/// Format a Unix timestamp as a relative time string.
#[must_use]
pub(crate) fn relative_time(timestamp: i64) -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| {
            #[expect(
                clippy::as_conversions,
                reason = "epoch seconds fit in i64 until year 292B"
            )]
            let secs = d.as_secs() as i64;
            secs
        })
        .unwrap_or(0);

    let delta = now - timestamp;
    if delta < 0 {
        return "just now".to_string();
    }

    #[expect(clippy::as_conversions, reason = "delta verified non-negative above")]
    let delta = delta as u64;
    match delta {
        0..=59 => "just now".to_string(),
        60..=3599 => {
            let m = delta / 60;
            format!("{m}m ago")
        }
        3600..=86399 => {
            let h = delta / 3600;
            format!("{h}h ago")
        }
        86400..=604799 => {
            let d = delta / 86400;
            format!("{d}d ago")
        }
        _ => {
            let w = delta / 604800;
            format!("{w}w ago")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn relative_time_just_now() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now), "just now");
    }

    #[test]
    fn relative_time_minutes() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now - 120), "2m ago");
    }

    #[test]
    fn relative_time_hours() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now - 7200), "2h ago");
    }

    #[test]
    fn relative_time_future_is_just_now() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now + 600), "just now");
    }

    #[test]
    fn relative_time_days() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        // 2 days = 172800 seconds.
        assert_eq!(relative_time(now - 172_800), "2d ago");
    }

    #[test]
    fn relative_time_weeks() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        // 3 weeks = 1814400 seconds.
        assert_eq!(relative_time(now - 1_814_400), "3w ago");
    }

    #[test]
    fn relative_time_under_one_minute_is_just_now() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        assert_eq!(relative_time(now - 30), "just now");
    }

    #[test]
    fn relative_time_one_hour_boundary() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        // 1 hour = 3600 seconds — boundary case (h pattern).
        assert_eq!(relative_time(now - 3600), "1h ago");
    }

    #[test]
    fn role_equality_and_copy() {
        // Role derives Copy/Eq; verify these traits work as expected.
        let r1 = Role::User;
        let r2 = r1;
        assert_eq!(r1, r2);
        assert_ne!(Role::User, Role::Assistant);
        assert_ne!(Role::Assistant, Role::System);
    }

    #[test]
    fn chat_message_clone_preserves_fields() {
        let msg = ChatMessage {
            id: 42,
            role: Role::Assistant,
            content: "hello".to_string(),
            timestamp: 100,
            agent_id: None,
            tool_calls: 3,
            thinking_content: Some("thinking...".to_string()),
            is_streaming: true,
            model: Some("claude-sonnet-4".to_string()),
            input_tokens: 100,
            output_tokens: 200,
        };
        let cloned = msg.clone();
        assert_eq!(cloned, msg);
        assert_eq!(cloned.id, 42);
        assert_eq!(cloned.tool_calls, 3);
        assert_eq!(cloned.input_tokens, 100);
        assert_eq!(cloned.output_tokens, 200);
        assert!(cloned.is_streaming);
    }
}
